### ISSUE TITLE
Choose a background task processing system

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#100]
## Overview

Discuss options and choose a system for processing uploaded facility lists in the background.

### Describe the solution you'd like

A description of the task processing systems that were considered and the reasoning behind our final selection. Could be in ADR format.

### Additional Context

Requirements:

  * Task processing code is written in Python and can use Django models to interact with the Postgres database.

Some systems to consider:

  * [Celery](http://www.celeryproject.org/)
  * [AWS Batch](https://aws.amazon.com/batch/)
  * [Dramatiq](https://dramatiq.io/)
  * [RQ](http://python-rq.org/)
  * [Django Q](https://github.com/Koed00/django-q)

**Comment by jwalgran** [comment]
Some notes from a discussion about AWS Batch

AWS Batch is a free service that schedules jobs to run on ECS clusters.

- Terraform has the ability to provision all the Batch resources.
- Jobs run within a docker container.
- Anything that can be an ECS tasks can be a Batch job.
- If an ECS cluster is not running at all times, starting one up to process new
  work can date on the order of minutes.
- Batch Jobs could reuse our existing Django app container.
- There is no out-of-the-box solution for local development. Azavea projects
  have used manually `docker run`ing and using a shared development ECS cluster
  as workarounds.
  - We should follow up with the Raster Foundry team for more local development
    details.
- Visualization of job status was bare bones.
  - We should follow up with Raster Foundry to see if this is still the case.

An ADR from another Azavea project: 
https://github.com/azavea/pfb-network-connectivity/blob/develop/docs/architecture/adr-0004-asynchronous-task-queue-2.md
Some concerns raised in this 2 year old analysis are no longer an issue
- Needing unmanaged mode for large volumes.
- Terraform support.

**Comment by rbreslow** [comment]
Some thoughts I have to enter the meeting with:

* Is it possible to add worker functionality as Django management commands, and then create ECS task definitions that invoke `manage.py` we could throw on AWS Batch?
* What mechanism would we use to submit a job to Batch?
* After having these thoughts, it does look like pfb-network-connectivity takes this exact approach, where [management commands](https://github.com/azavea/pfb-network-connectivity/tree/2fc3cb7f1ae9d7c6810bedadb257692fdb581462/src/django/pfb_analysis/management) invoke functions in the [`AnalysisJob`](https://github.com/azavea/pfb-network-connectivity/blob/2fc3cb7f1ae9d7c6810bedadb257692fdb581462/src/django/pfb_analysis/models.py#L431) class. 
* Is Boto3 the best mechanism for launching batch jobs? Are there any Django specific modules for Batch integration?
* Here are some "official" examples of launching Batch jobs with Boto3: https://github.com/awslabs/aws-batch-helpers/blob/master/gpu-example/submit-job.py

**Comment by jwalgran** [comment]
Ww have decided to go with AWS Batch

- We have successfully provisioned, maintained, and relied on Batch for other Azavea projects.
- We do not need to provision a broker service (i.e. Redis)
- We do not need to provision compute resources for processing. We provision Batch resources that will launch and scale compute for us.
- Our workflow aligns with the simple job dependency model offered by Batch.
- We will encapsulate our processing tasks in Django management commands
  - These  can be run in development, where Batch is not available.
  - If Batch does not deliver the performance or resiliency we need, we will be able to transition to a different system relatively easily since the processing functions will require little to no change.
