### ISSUE TITLE
Add CI support again

### ISSUE THREAD

**Issue by hectcastro** [open-apparel-registry/open-apparel-registry#102]
When the repository was migrated, we lost CI support via our local Jenkins instance.

**Comment by rbreslow** [comment]
* I invited the `azaveaci` user to the Open Apparel Registry GitHub organization and added it to the `Operations` team
* I added the Open Apparel Registry organization to `civicci01`
* I duplicated the configuration of the Azavea organization and scoped it to only build the `open-apparel-registry` repository
* I cycled `develop`, and everything looks :+1:
