### ISSUE TITLE
Additional dropdown entries in Claim a Facility form

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1029]
NOTE: Shares point with #1315 

## Overview

We would like to add some additional content to the "Affiliations" dropdown menu in the Claim a Facility form. 

### Is your feature request related to a problem? Please describe.

We need to add some additional entries to the "Affiliations" dropdown on the Claim a Facility form.

### Describe the solution you'd like

In the "Affiliations" dropdown in the Claim a Facility form, could we please add the following entries:

- HERhealth
- HERfinance
- HERrespect

### Additional Context

Optional. Add any other context, screenshots, gifs, etc about the feature request here.

**Comment by dboyer** [comment]
@katieashaw What's the date by which we need to have these added?

**Comment by katieashaw** [comment]
Absolutely no rush on this addition at all! There's no hard & fast deadline - I just included this as a small task to be logged alongside the other backlog work.

**Comment by katieashaw** [comment]
I'm going to add a running list of additions to these drop downs, starting with:

- Green Button (in the Certifications / Standards / Regulations section)

**Comment by katieashaw** [comment]
- Fairtrade USA (in the Certifications / Standards / Regulations section)
- ZDHC (in the Affiliations section)

**Comment by katieashaw** [comment]
There are other additions and edits we'd like to make to the Claim a Facility form, including:

- Allowing facilities to select multiple facility types (relevant for vertically integrated units)
- Switching the "Number of workers" entry from a free text box to a dropdown menu with ranges, e.g. Up to 100, 101 - 200, 201 - 300 etc
- I'd also like to have a discussion about whether some fields - particularly the Transparency Pledge data requirements - should become mandatory fields
cc @nataliegrillon

**Comment by hlennett** [comment]
Additional certification: Goodweave: https://goodweave.org/about/goodweave-label/
