### ISSUE TITLE
Mobile optimization: explainer text for Contributor Overlap not appearing 

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1033]
## Overview

The explainer text for Contributor Overlap is not appearing when you click the 'i' button having selected multiple Contributors. 

### Expected Behavior

Pop up text explaining Contributor Overlap should appear 

### Actual Behavior

Nothing happens when you click the 'i' button - the explanatory text does not appear. 

### Steps to Reproduce

* Visit staging.openapparel.org
* Select multiple Contributors
* Click the 'i' button

### Demo

![1E13CCF9-F443-41E7-A164-44B5504598B6](https://user-images.githubusercontent.com/46344729/85114230-99561d80-b210-11ea-93ff-dcb41c4542c2.png)

### Additional context

This is the text which should appear (taken from Production)

![Screenshot 2020-06-19 at 09 39 05](https://user-images.githubusercontent.com/46344729/85114324-c60a3500-b210-11ea-91d3-41c3c8fcda43.png)

**Comment by jwalgran** [comment]
Resolved by #1059
