### ISSUE TITLE
PPE language changes

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1047]
## Overview

Review the language around PPE in the UI and choose the most helpful text. Add popups as required.

**Comment by dboyer** [comment]
@katieashaw Sounds like we're good to continue using the phrase PPE. Would you like a help icon near the PPE only filter? I would suggest:

Personal protective equipment (PPE) includes masks, gloves, gowns, and other equipment.

**Comment by katieashaw** [comment]
Yes, I agree @dboyer 

And yes please to a help icon. Given the inclusion of data on 3D printed visor makers, could we tweak your suggestion sentence to:

Personal protective equipment (PPE) includes masks, gloves, gowns, visors and other equipment.

**Comment by jwalgran** [comment]
Moved back to the queue because we need to make an additional change.
