### ISSUE TITLE
Use organization attached to authenticated user when uploading CSV

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#105]
## Overview

Uploaded CSVs should be connected to the organization associated with the authenticated user.

### Describe the solution you'd like

  * Use token-auth to test this from the command line (see #86 and #110)
  * Associate the organization with the facilitylist
  * Reject unauthenticated uploads and uploads where the authenticated user does not have an organization

**Comment by kellyi** [comment]
Consider possibly doing this in passing too: https://github.com/open-apparel-registry/open-apparel-registry/issues/101
