### ISSUE TITLE
Make the replica of production the permanent staging database

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#1111]
Working through #1084, we set up a replica of the production database with sanitized email addresses. Folks at OAR were happy to have fresher data in staging and already went through the process of recreating the accounts they use there.

Making this new database the permanent staging database makes sense. The new database is a replica of production, so it's `db.t3.small` and multi-AZ vs. the smaller `db.t3.micro` and single-AZ. It also was upgraded to PostgreSQL 12.

The following questions are left unanswered:
- Do we want to leave it as-is, or scale it back?
- The upgrade process was fairly straight forward, but I didn't document anything as I went through. Do we want to keep the old database around so that we can walk through a PostgreSQL 12 upgrade with more-accurate info on the length of downtime?

The following things need to be done:
- Manipulate the Terraform state to remove the old database / parameter group and slot in the new set of resources.

**Comment by rbreslow** [comment]
I removed the old RDS instance from the Terraform state and then renamed it in the AWS console with the suffix `-old`. I renamed the new RDS instance to the old RDS instance's original name and imported it back into the Terraform state. Then, I cycled Terraform using the changes in #1125 to create and apply a new parameter group that is codified in Terraform. 

These AWS docs served as a useful sanity check: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_RenameInstance.html#USER_RenameInstance.RR

Everything looks clean now. I left the old database instance in a stopped state just in case and set up a 2 week Slack reminder to delete it in its entirety.

**Comment by rbreslow** [comment]
I've moved this to `in review`. @hectcastro If you could take a look at #1125, the description of events in this issue, and the state of things in the AWS console, I think we could then close this out.

**Comment by hectcastro** [comment]
Because https://github.com/open-apparel-registry/open-apparel-registry/pull/1125 makes the current staging database default to PostgreSQL 12, I think that now we need to accelerate the effort to get development and production on PostgreSQL 12 as well. There is a draft issue https://github.com/open-apparel-registry/open-apparel-registry/issues/948 to upgrade to PostgreSQL 12, but I think we may need to split that into at least two separate issues (one for upgrading to PostgreSQL 12 in development, and another for production). After they exist, we should aim to slot them into next sprint.

**Comment by rbreslow** [comment]
These are up and slotted in.

**Comment by hectcastro** [comment]
Can the `openapparelregistry-enc-stg-old` RDS instance be taken offline now?

**Comment by rbreslow** [comment]
I had a Slackbot reminder to do this tomorrow.

**Comment by hectcastro** [comment]
It looks like the `openapparelregistry-enc-stg-old` RDS instance is still online.
