### ISSUE TITLE
PAS Group (Public source) supplier list is not populating on the map

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#112]
## Overview

When searching the map, if you select PAS Group (Public Source) as a contributor, their supplier list does not populate. 

### Expected Behavior

There are 28 suppliers on the PAS Group (Public Source) list which should appear on the site when you filter by that Contributor.

### Actual Behavior

Zero facilities are returned. 

### Steps to Reproduce

- Filter search on OAR site by PAS Group (Public Source)
- Click "Search"
- N.B. There are two Contributors for PAS Group - be sure to select PAS Group (Public Source) when replicating this bug

### Demo

N/A

### Additional context

Natalie or Katie uploaded this public list prior to the October launch. Log in details for the account created are:

Username: info23@openapparel.org
Password: apparel23

**Comment by katieashaw** [comment]
The same issue is occurring with the Contributor "Hemingway". 

This account has been created by a member of the public, which I imagine is associated with this email address: cmarsh@hemingwayapparel.com (taken from the list of OAR users shared by Matt).

Steps to replicate the bug are the same:

- Filter search on OAR by Contributor "Hemingway"
- Click "Search"

**Comment by jwalgran** [comment]
This issue references old test data.
