### ISSUE TITLE
Add model and API methods to allow for reporting a facility as closed or reopened

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1136]
## Overview

Add models and an API to support mark a facility as closed.

For reference, here are the wireframes of the full "report as closed" feature: https://app.abstract.com/projects/441633f0-7d8c-11e9-af1e-972cbddca60a/branches/c06f3eda-8595-456e-a80f-397a63bbdcec/collections/210f6bf8-3804-4329-94c7-5c5912e7dea8

### Describe the solution you'd like

- Add a `FacilityActivityReport` model
  - required FK to facility
  - `reported_by_user` required FK to user
  - `reported_by_contributor` required FK to contributor
  - `closure_state` required choice OPEN or CLOSED
  - `created_at` and `updated_at` auto fields
  - `approved_at` nullable date time
  - `status` required default PENDING
    - PENDING, CONFIRMED, REJECTED
  - `status_change_reason `nullable text
  - `status_change_by` nullable FK to user 
  - `status_change_date` nullable datetime
  - Historical model integration
- Add a nullable `is_closed` field to Facility 
- Add an API to submit a facility as open or closed
  - Add method(s) to the facility ViewSet to handle `POST /facilities/{id}/report` and `POST /facilities/{id}/report/{id}/approve` and `POST /facilities/{id}/report/{id}/reject`
    - `approve` and `reject` view functions should accept a `status_change_reason` string and set the `status`, `status_change_by`, and `status_change_date` on the `FacilityActivityReport` and set the `is_closed` field on the `Facility` appropriately.
    - `approve` view function should set `approved_at`
  - Include the required docstring comments and related code so that Swagger API docs show the new endpoint.

**Comment by designmatty** [comment]
@jwalgran @dboyer Can you take a look at the designs here https://share.goabstract.com/ca589b7e-f23f-49a5-9f50-595d38a596af

**Comment by jwalgran** [comment]
Thanks for linking these designs. I added comments to Abstract.
