### ISSUE TITLE
Facilities not merging in Dashboard

### ISSUE THREAD

**Issue by OAR-Community** [open-apparel-registry/open-apparel-registry#1150]
## Overview

Facilities are not merging in the OAR Dashboard (neither facility is claimed).

### Expected Behavior

Facilities should merge when prompted to in the dashboard. 

### Actual Behavior

The facilities do not merge, even when flipped. 

### Steps to Reproduce

1. Target Facility for Merge - EG201908530REZD
2. Facility to Merge into Target - EG2019262X11NRE
3. Attempt Merge
4. Click 'Flip Facilities'
5. Attempt Merge

### Demo

![Screen Shot 2020-10-21 at 3 37 33 PM](https://user-images.githubusercontent.com/68333623/96774039-6d5fca00-13b3-11eb-9779-f527dd2ae314.png)
![Screen Shot 2020-10-21 at 3 24 24 PM](https://user-images.githubusercontent.com/68333623/96774043-6d5fca00-13b3-11eb-8098-edcb40900642.png)

### Additional context

Optional. Add any other context about the problem here.

**Comment by OAR-Community** [comment]
Additional OAR ID examples:

Target: IN20192977A8Y7K
To be Merged: IN2020246223YM0 & IN2019294RX6KZZ

Target: IN2020034JHZKWK
To be Merged: IN2020106QS5FAG

Target: IN20192685N2JEF
To be Merged: IN20201065W1RHD

Target: IN20192974AVN1M
To be Merged: IN2020191ZZ4J93, IN2019087QJKTKV, IN202019125GWJB

Target: TH20191720K37ZE
To be Merged: TH2019085ATD4X7

**Comment by jwalgran** [comment]
I reproduced this on production and saw a 500 error logged in Rollbar

https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/538/

<img width="1179" alt="Screen Shot 2020-11-24 at 9 40 01 AM" src="https://user-images.githubusercontent.com/17363/100124601-12e5dd80-2e39-11eb-8254-047cd4b29cd1.png">

There is a pending claim on the merge facility that is blocking the merge.

I am working on a fix that will move the claim over to the target facility.
