### ISSUE TITLE
It's becoming difficult to navigate in Django with so many single facility submissions

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1155]
## Overview

As users connect with our push pull API and submit multiple single facility queries / contributions, the volume of entries in the Django admin dashboard is growing exponentially. This makes it difficult to quickly search and make changes following user requests.

### Expected Behavior

A more efficient way to search through different sections of Django. 

### Actual Behavior

There are numerous pages in each section of Django, e.g. 54,773 pages of Sources, 537 facility lists (6 pages)

### Additional context

The most frequent user requests we receive which are becoming more cumbersome as the database grows and users make use of our API are:

- Deactivating lists, when users forget to select "replace a list" when uploading an updated list
- Moving facility lists from one Contributor account to another, e.g. when moving data uploaded by the OAR team over to a user, or when one person leaves an organisation and a colleague takes over managing data in the OAR

**Comment by katieashaw** [comment]
An example of this in practice: I've just spent over 20 mins searching for a Public List in the Sources menu in Django and still not been able to find it, due to the volume of single item sources that we now have.

Is there a way we could separate out list sources from single item sources that have been contributed via API?

**Comment by jwalgran** [comment]
Enabling `list_filter` on the admin paged may get us what we need quickly and easily.

https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter
