### ISSUE TITLE
Re-enable the temporary survey dialog

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1157]
## Overview

Re-enable the temporary survey dialog created in #869 for a new survey.

### Describe the solution you'd like

* Get the new survey details from @katieashaw 
* Re-enable the dialog

**Comment by katieashaw** [comment]
You may want to merge this with #1151 @jwalgran

**Comment by jwalgran** [comment]
Thanks.

Duplicate of #1151.
