### ISSUE TITLE
Request to edit the text on the "Contribute" page

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1164]
## Overview

We would like to update the text on the "Contribute" page of OAR accounts. 

### Is your feature request related to a problem? Please describe.

3 facilities have uploaded data to the OAR using the PPE Contributor template when they do not manufacture PPE. This is enabling them to add additional information e.g. product type, email address / telephone number and URL directly through an upload, rather than claiming their facility.

We would like to update the text on the "Contribute" page to make it clear which template users should use when, being mindful that many users will not speak English as a first language. 

### Describe the solution you'd like

We will submit revised text for this page. 

### Additional Context

@jwalgran Let us know when you can include this update in a new release and we'll get the text ready for you. 

Shares point with #1158

**Comment by dboyer** [comment]
@katieashaw We can expect a release in about two weeks so it would be good to have text by 11/11.

**Comment by katieashaw** [comment]
@dboyer @jwalgran 

The revised text is ready at this link:

https://docs.google.com/document/d/14PzXmoq7AhVH-PF0PM6QgwpWi-SiGA4jhZ-9xLPaQpA/edit?usp=sharing

**Comment by katieashaw** [comment]
@nataliegrillon I'd forgotten we also wanted to update the text to guide people more explicitly to confirm / reject. I've added my suggestion to the doc - could you double check you're happy with it?

**Comment by nataliegrillon** [comment]
looks great - accepted

Best,

Natalie
----
Natalie Grillon
Executive Director, Open Apparel Registry <http://openapparel.org>
natalie@openapparel.org // + 1 413 884 3355
Share your feedback on the OAR in our user survey here
<https://openapparelregistry.typeform.com/to/ue3mV6OD>
LinkedIn <http://linkedin.com/company/open-apparel-registry>
