### ISSUE TITLE
Switch the social media preview feature for Contributor URLs to mention the Contributor's name

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1168]
## Overview

We would like to change the social media preview feature for Contributor URLs to mention the Contributor's name, rather than simply generating the generic OAR blurb.

### Is your feature request related to a problem? Please describe.

URLs pointing to specific Contributors currently only generate generic OAR blurb, rather than including the name of the Contributor.

### Describe the solution you'd like

We would like the social media preview to include the name of the Contributor 

### Additional Context

![Screenshot 2020-11-06 at 18 06 37](https://user-images.githubusercontent.com/46344729/98399777-d81f2f80-205a-11eb-820c-17970d65378c.png)

**Comment by jwalgran** [comment]
Merging this with #961.
