### ISSUE TITLE
Trim whitespace when looking up country codes

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1179]
## Overview

When looking up the country code for submitted facility data as part of the "parse" step, trim leading and trailing whitespace to increase the chances of a successful lookup.

### Is your feature request related to a problem? Please describe.

Country names with leading or trailing whitespace result in parse errors.

### Describe the solution you'd like

* Update the "parse" task to ignore leading and trailing white space when looking up a country code.

**Comment by katieashaw** [comment]
A new contributor has been unable to upload this morning due to this issue. Could we bump this up the priority list please?

**Comment by katieashaw** [comment]
Noting that another contributor has been unable to upload this morning due to this issue.

**Comment by katieashaw** [comment]
This has generated over 1,000 error messages in a big list upload from an additional user this morning.
