### ISSUE TITLE
Confirm / Reject: Multiple Potential Matches Linked as 1

### ISSUE THREAD

**Issue by OAR-Community** [open-apparel-registry/open-apparel-registry#1185]
## Overview

During confirm/reject analysis of a list, the following bug was noticed. When an entry has multiple potential matches, names and address of the multiple facilities are not broken by line items. Instead, the facilities are linked via 1 hyperlink formatted as "https://openapparel.org/facilities/[OAR ID 1],[OAR ID 2],[OAR ID 3], etc.". Additionally, the confirm and reject button shows only for the top-most potential match. If confirmed, the other matches are ignored as expected. If rejected, the button moves to the second entry. 

### Expected Behavior

When facilities have multiple potential matches, the matches should show in individual line items with a Confirm and Reject option for each potential match. 

### Actual Behavior

Multiple potential matches show as a singular entry, with hyperlink combining all OAR IDs into one Error-producing link. 

### Steps to Reproduce

* Using Google Chrome Browser. 
* Dashboard > View Contributor Lists > Any List with Potential Matches
* Example List: Better Cotton Initiative 
* Line 595

![Screen Shot 2020-12-09 at 9 25 28 AM](https://user-images.githubusercontent.com/68333623/101642878-83782700-3a01-11eb-9bbd-4f67a55bdab5.png)

### Demo

Hyperlink creation from click the above example: 
![Screen Shot 2020-12-09 at 9 33 15 AM](https://user-images.githubusercontent.com/68333623/101642943-9a1e7e00-3a01-11eb-8f9b-274bc3f6d344.png)

### Additional context

Optional. Add any other context about the problem here.

**Comment by jwalgran** [comment]
This issue exists in development list 8 item 25. "Hanes Choloma"

<img width="1554" alt="Screen Shot 2020-12-11 at 9 00 05 AM" src="https://user-images.githubusercontent.com/17363/101925708-683b2200-3b8f-11eb-9366-75f113c55a88.png">

**Comment by jwalgran** [comment]
Likely a regression caused by restyling the table in https://github.com/open-apparel-registry/open-apparel-registry/pull/1152

**Comment by TaiWilkin** [comment]
Reopening to pursue a more permanent fix through refactoring.
