### ISSUE TITLE
Add page to manage cookie preferences

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#1191]
## Overview

The user should have the option to access a cookies preferences page where they can choose to change the opt in or out preference that they set when first visiting OAR.

### Describe the solution you'd like

* If `GA_TRACKING` is in local storage add a section to the https://openapparel.org/profile/{id} page that shows the same cookie message that is shown in the initial popup

<img width="624" alt="Screen Shot 2021-01-19 at 8 41 40 PM" src="https://user-images.githubusercontent.com/17363/105124213-ea740b80-5a96-11eb-9e42-51fba6b085d6.png">

* Show either an accept or reject button based on the value of GA_TRACKING (reference `app/src/util/util.ga.js`)
* If a button is clicked, call the same helper functions as the popup to change the preference. Ensure that the profile page rerenders to show the updated state.

**Comment by katieashaw** [comment]
Could we prioritize this when we're back in January please.
