### ISSUE TITLE
You cannot search the map by OAR ID number

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#121]
## Overview

You cannot search the map using an OAR ID number.

### Expected Behavior

If an OAR ID number is entered as the search term in the site, you would expect the facility that the ID number relates to to be returned in the results. 

### Actual Behavior

No matches are returned when you search the site by OAR ID number.

### Steps to Reproduce

* Log onto the site
* Enter an OAR ID number into the "facility name' search box

### Demo

N/A

### Additional context

It's also not intuitive for users who want to search the site using an OAR ID number to put this into the "Facility name" search box. Could we either re-name this search box, or add an additional free text search box?

**Comment by katieashaw** [comment]
We received an instance of a user reporting an issue on the OAR using just the ID number - see screenshot from their email:

![Screenshot 2019-04-03 at 17 41 00](https://user-images.githubusercontent.com/46344729/55497277-f039fc00-5638-11e9-87ec-c3ccccaa2f53.png)

**Comment by katieashaw** [comment]
This was another instance of an issue being reported using the OAR ID number:

![Screenshot 2019-04-03 at 17 55 21](https://user-images.githubusercontent.com/46344729/55497646-b74e5700-5639-11e9-9b87-04f9d88a3075.png)

**Comment by katieashaw** [comment]
We've had a further instance of a user reporting an issue using the OAR ID number - see screenshot below.

![Screenshot 2019-04-23 at 10 15 35](https://user-images.githubusercontent.com/46344729/56569551-1526ec80-65b1-11e9-9982-8ed52939ed6c.png)

**Comment by jwalgran** [comment]
As a stopgap until we implement this feature, it is possible to jump straight to a facility by adding the OAR ID to this URL: `https://openapparel.org/facilities/`. For example, to see the facility mentions in the error report:

https://openapparel.org/facilities/PK20191085SEHP3

**Comment by katieashaw** [comment]
Oh, this is great - thank you @jwalgran !
