### ISSUE TITLE
When filtering by country, the search box does not include predictive text function

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#122]
## Overview

When users go to filter their search by country, they cannot start to enter the letters of the country they are looking for and have the list jump to that country - they have to manually scroll down the list instead. 

### Expected Behavior

Entering the first letters of a country should jump to that country in the list, e.g. entering "Fr" should jump down the list to France.

### Actual Behavior

Users have to manually scroll through the list of all countries until they find the country they want to select. 

### Steps to Reproduce

* Log onto the site
* Select the Country filter dropdown
* Try entering the first letters of the name of a country

### Demo

N/A

### Additional context

N/A

**Comment by katieashaw** [comment]
I realise I should have added this as a New Feature request, rather than a Bug - not sure if there's a way I can change that? Apologies!

**Comment by jwalgran** [comment]
No problem, Katie. The only difference is the structure of the template.

**Comment by kellyi** [comment]
This was completed in #159 https://github.com/open-apparel-registry/open-apparel-registry/pull/159
