### ISSUE TITLE
When data is downloaded from the site, it doesn't have a separate column for Country

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#123]
## Overview

When data is downloaded from the site, it does not have a separate column for Country. This does not match the upload format. 

### Expected Behavior

When downloading data from the site, Country information should have its own separate column. 

### Actual Behavior

When downloading data from the site, the file contains the following columns:

- nameID (the column title that has been given to the OAR ID number)
- longitude
- latitude
- name
- address

### Steps to Reproduce

* Search the site in order to return a set of results
* Click "download" button

### Demo

Here's an example of data downloaded from the site:

https://drive.google.com/open?id=1BLm1VnPhKej8Aefi9QIkzMg5SQhK5LRJ

### Additional context

I also think the title of the OAR ID number column being "nameID" is unhelpful. Could this be renamed to "OAR ID"?

A lot of organisations organise their supplier lists by country, so having this information in a separate column, which people can filter by, is crucial if it's going to be useful to users of the site.

**Comment by kellyi** [comment]
Shares a point with #127
