### ISSUE TITLE
You cannot see the entire description of a Contributor when you view their profile

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#124]
## Overview

When you click on a Contributor to view their profile, you cannot see the entire description of the Contributor that has been entered. 

### Expected Behavior

Users would expect to be able to see the entire description of a Contributor that has been entered onto a profile. 

### Actual Behavior

When you view a Contributor profile, the description is cut short at the end of the Description box and you cannot read it in its entirety. 

### Steps to Reproduce

* Filter the site by a Contributor
* Click on a facility
* Click on a Contributor's profile

### Demo

N/A

### Additional context

N/A

**Comment by kellyi** [comment]
While re-implementing the contributor profile form we adjusted things to display the full contributor description:

![Screen Shot 2019-06-21 at 11.02.24 AM.png](https://images.zenhubusercontent.com/5c8fb0e4d74bd07972c84b67/89cfe6fc-532b-4cf2-8e0e-c6ce09bd1a59)
