### ISSUE TITLE
Display issues on confirm / reject page

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1242]
## Overview

There are display issues with the way that potential matches are being presented to users on the confirm / reject page

### Expected Behavior

Each potential match should align with the associated confirm / reject buttons

### Actual Behavior

The alignment of confirm / reject buttons is off. 

### Demo

![Screenshot 2021-02-14 at 16 54 07](https://user-images.githubusercontent.com/46344729/108051240-8ff0af80-7042-11eb-80f4-3101c3def5da.png)

**Comment by jwalgran** [comment]
We started work on fixing this yesterday and we should have it resolved today (#1243) and deployed in the near future.

**Comment by jwalgran** [comment]
Thanks for reporting this. I am closing this specific issue because we tracked our work fixing is as a continuation of #1185.
