### ISSUE TITLE
Could profile photos / logos appear alongside Contributor names?

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#126]
## Overview

Could profile photos / logos appear alongside contributor names in the facility contributor list?

### Is your feature request related to a problem? Please describe.

Currently, Contributors of facility information are currently just listed as hyperlinked text entries (clicking through to their Contributor profile) on the facility information page. It would be more visually engaging for the user if Contributor logos / photos appeared alongside their entries on facility information pages. 

### Describe the solution you'd like

You can see the original designs for this on the Envision site built for the tool: https://projects.invisionapp.com/share/2RFG3XLB6XP#/screens

And also in this screenshot of the Envision site: https://drive.google.com/open?id=1SbSJffWgcp6VEqbifX1RPj7zSIpFUNQ4

Is it possible to build this?

### Additional Context

N/A

**Comment by jwalgran** [comment]
The application does not currently store any uploaded media (CSV/XLSX facility lists are not stored as-is, but parsed and stored as individual rows at upload time)

To implement this we would need to configure Django media uploads, likely via [django-storages and the S3 backend](https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html) which we have used successfully on other projects.

We would also need to give superusers a way to remove abusive content.

**Comment by katieashaw** [comment]
This makes sense, thank you. Tagging @nataliegrillon for info. This _may_ be something we want to consider further down the line.

**Comment by katieashaw** [comment]
Closing as no longer considered necessary.
