### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1261]
# Overview

Our lawyer's have flagged that:

_Under the GDPR, OAR’s site should allow all users to easily withdraw consent to using cookies, not just registered users._

### Is your feature request related to a problem? Please describe.

Legal compliance with GDPR

### Describe the solution you'd like

1) A link in the footer of the application to a page which any user can access, regardless of whether or not they are logged into an account, which enables them to easily opt-in or opt-out of cookies. 

2) Have the Cookie pop-up appear every time a non-logged in user visits the app on mobile (where the footer is not visible), regardless of how frequently the user visits the site. 
  - Consult with @lederer on how to make this available on mobile without being overly frustrating.

### Additional Context

The links created will be inserted into the OAR's Ts&Cs

**Comment by dboyer** [comment]
Instead of #2, we may also want to think about just making the footer appear on mobile.
