### ISSUE TITLE
When you click "View facility list" the facilities are not listed in alphabetical order

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#127]
## Overview

After searching the OAR site, when you select "View facility list" the results returned are not listed in alphabetical order. 

### Expected Behavior

When viewing a list of facilities, I would expect them to be listed in alphabetical order. 

### Actual Behavior

I'm not certain whether there is a logic behind the way the results are presented (e.g. by country), or whether they are listed randomly, but they are not presented in alphabetical order.  

### Steps to Reproduce

* Run a search on the site
* Click 'View facility list"

### Demo

N/A

### Additional context

N/A

**Comment by kellyi** [comment]
I'll make this change as part of working on #209 / #237
