### ISSUE TITLE
Connect embed section of setting page to API

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1312]
## Overview

Make sure embed setting can be loaded and saved

### Describe the solution you'd like

- No redux needed
- Fetch fields from the API in #1313 and incorporate them into the list of contributor fields along with a hard-coded set of standard fields
  - parent_company
  - type_of_product
  - number_of_workers
- Fetch embed config from the EmbedConfig API and use it to populate the config fields ('width', 'height', 'color', 'font', 'contributor', 'show_other_contributor_information', 'embed_fields') and contributor fields for the configuration settings
  - The list of contributor fields should include both the fields from the nonstandard fields API and the fields from the embed config, but should not contain duplicates. Fields from the embed config take priority in case of duplicates. 
- Update/create the embed config when the user changes the config fields
- Update the contributor embed fields when the user changes the contributor fields

**Comment by TaiWilkin** [comment]
@jwalgran I expanded a bit on this for the sake of completeness. Is there any additional information you think we need here before we officially call it 'undrafted'?

**Comment by jwalgran** [comment]
👍 This looks good. Thanks for adding the additional detail.
