### ISSUE TITLE
Reorder embed fields with buttons or drag and drop on the settings page

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1314]
## Overview

Allow the order of the embed fields to be changed via drag and drop or move up/down buttons.

### Describe the solution you'd like

- Import a drag and drop library (check with other projects to determine the standards)
- When hovering over a field, show a drag-and-drop "handle" along with ⬆️ and ⬇️ buttons.
- After dragging and releasing a field, `PUT` an update to the config with the fields in the new sequence
- After clicking one of the up or down buttons on a field move the field up or down and `PUT` an update to the config with the fields in the new sequence.

### Additional Context

See wireframes [here ](https://app.abstract.com/projects/441633f0-7d8c-11e9-af1e-972cbddca60a/branches/272eff0b-3229-482f-a003-fad1e9558a87/commits/f6ea0c402509c5030af8156fc58c81fb830a5e76/files/fc1791e3-b8d2-4182-b240-fef32fabe978/layers/526E562F-5629-4C92-AA7D-81A6ABC16283?collectionId=8ac19367-6932-43c2-95fa-7483af019a26&collectionLayerId=d47aa166-c33c-4abe-b476-4c3887970441)

<img width="404" alt="Screen Shot 2021-05-24 at 1 35 20 PM" src="https://user-images.githubusercontent.com/17363/119404824-36c59700-bc95-11eb-8d83-9c2511ac6dfd.png">

**Comment by caseycesari** [comment]
I did some research into finding a library that supported drag and drop, and I think this is the best option: https://github.com/atlassian/react-beautiful-dnd.

It also supports using a separate button to move things up and down the list, though the example is a little different than our use case: https://react-beautiful-dnd.netlify.app/?path=/story/programmatic-dragging--with-controls

Other options I looked at:

https://github.com/react-dnd/react-dnd - Too low level
https://github.com/JakeSidSmith/react-reorder - Potentially not maintained anymore (there is a more recent, unpublished version that is more active, but still not much activity).
