### ISSUE TITLE
DRAFT: Set up API push notification when facility has a new affiliation

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#1316]
Enable API users to subscribe to push notifications so that they can receive updates on: (a) the facilities with which they are associated, (b) facilities which they specify by existing filters.

Details about what changed are not included in the notification.

## Overview

A clear description of the feature request.

### Describe the solution you'd like

- Set a webhook API on profile
- Design POST payload with MSIs
- POST from match batch task and single item API to all contributors connected to facility (?? disascociated)
- Send email too with opt-out in profile
- Include opt-out link in email / view to handle it
- 

### Supporting documents
[Technical description](https://docs.google.com/document/d/1LHGGKBwP2u7BUkKHf3fr9PaY_05sUMy5Ax0cXWvEdCc/edit)

[Design notebook](https://docs.google.com/document/d/1jwaEHVdfPpd96Xw9ZOq_UnBcCcyRkAOr8ZPTuUlkYAI/edit#)

**Comment by jwalgran** [comment]
Closing because this has been replaced by Epic issue #1997 which is connected to related sub-issues
