### ISSUE TITLE
Display "Powered by" footer in embed mode

### ISSUE THREAD

**Issue by TaiWilkin** [open-apparel-registry/open-apparel-registry#1336]
## Overview

Restore the footer in embed mode, and update content. 

### Describe the solution you'd like

- Restore the footer 
     - Change content in embed mode to be just the fixed image in the lower left corner
     - Link the image to `https://openapparel.org`

### Additional Context

![image.png](https://images.zenhubusercontent.com/5e41c4f13da639155d2ee456/0691275b-72fe-4732-b38a-7b2c97e111bd)
![image.png](https://images.zenhubusercontent.com/5e41c4f13da639155d2ee456/af82deff-f8c8-44b5-81ef-e16453c122af)

**Comment by jwalgran** [comment]
The new "Powered by" logo
[OAR_PoweredBy_white.svg.zip](https://github.com/open-apparel-registry/open-apparel-registry/files/6480156/OAR_PoweredBy_white.svg.zip)
