### ISSUE TITLE
Additional report request

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1346]
## Overview

We'd like to request some additional monthly reports

### Is your feature request related to a problem? Please describe.

We need additional reports to enable us to track against our external and internal KPIs

### Describe the solution you'd like

Could we please have the following reports:

- [x] Percent of facilities claimed
- [ ] Platform % Uptime (Is there a way we can see this?)
- [x] Duplicates merged
- [x] Facilities marked as closed
- [x] Names and addresses promoted ~(quarterly)~ monthly
  - Count history rows where `created_from` changed from one non-null value to another.
- [ ] Seconds per submitted item to geocode (the time from when an item was submitted to when it was processed (including time waiting in a queue))
  - Monthly and weekly versions
- [ ] Seconds per submitted item to process a match (the actual processing time, excluding any wait time)
  - Monthly and weekly versions
- [x] Number of API users (cumulative)
  - Distinct users in the request log
- [x] Number of Embedded map users
  - Cumulative create_date on the embdconfg row

cc @hlennett

**Comment by dboyer** [comment]
@hlennett Could you put these in a most important to least important priority order so we add them in an order that's most helpful to you?

**Comment by hlennett** [comment]
Yes! Here you go @dboyer: 

- Percent of facilities claimed
- Platform % Uptime (Is there a way we can see this?)
- Duplicates merged
- Facilities marked as closed
- Names and addresses promoted (quarterly) monthly
- Seconds per submitted item to geocode (the time from when an item was submitted to when it was processed (including time waiting in a queue))
- Seconds per submitted item to process a match (the actual processing time, excluding any wait time)
- Number of API users (cumulative)
- Number of Embedded map users

**Comment by jwalgran** [comment]
I rearranged the checklist in the issue description to match the priority order provided by Hannah.
