### ISSUE TITLE
Deactivate contributor lists automatically only AFTER a new list has finished processing

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#1388]
## Overview

We would like old contributor lists to be deactivated only when the new list has completed the processing stage.

### Is your feature request related to a problem? Please describe.

Currently, when a Contributor replaces a list with new data in the OAR, the old list is immediately deactivated. For those Contributors which only have one active list associated with their account, this means that the Contributor temporarily disappears from the Contributor dropdown menu & displays no data until the new list has finished processing. 

### Describe the solution you'd like

We would like the old data to be deactivated only after the new list has finished processing, so that the Contributor does not disappear from the Contributor dropdown.

#### Technical implementation 

- Move the deactivation of the old list items to just before (but in the same transaction as) saving new matches https://github.com/open-apparel-registry/open-apparel-registry/blob/develop/src/django/api/management/commands/batch_process.py#L79
- Test

**Comment by obrienad** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/1388?planning-poker) with Zenhub @nanotubing @jwalgran
