### ISSUE TITLE
Error opening these two OAR reports (COPY UPDATE)

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1389]
@isaacokunato commented on [Wed Jun 09 2021](https://github.com/open-apparel-registry/open-apparel-registry-clients/issues/34)

### Overview
Some unexpected error have been produced when trying to view Reports

### Expected Behavior
Reports are to be on display when opened

### Actual Behavior
It continues to load for a long time before displaying **504 Error, Request could not be satisfied** 

### Suggested remediation

- Rewrite SQL reports as Python

### Error Links
The two links are 
- Percent Facilities With Multiple Matches openapparel.org/admin/reports/percent-facilities-with-multiple-matches/ and
- Average Affiliations openapparel.org/admin/reports/average-affiliations/

Attached is the image of the display error 

![Report error message](https://user-images.githubusercontent.com/82677956/121401510-b23f6d80-c950-11eb-8f44-5fa7526c1107.JPG)

@hlennett @katieashaw 

## Note

This creates outages that are not caused by ECS tasks being cycled. Determine what resource is being consumed and determine how to rewrite the report to avoid it.

Use `makecsvs` management command to build large files.

**Comment by jwalgran** [comment]
Thanks for opening this. I moved it to our public repository because it is not related to a specific contributor.

**Comment by mariel-oar** [comment]
Can the name on the reporting page be updated to say "Do not open" for these list entries? 
(This is assuming that they actual fix for these reports is too involved for right now)

**Comment by jwalgran** [comment]
We actually pull the name of the report from the name of the SQL file in which the query is saved so, for instance, renaming `average_affiliations.sql` to `do_not_open_average_affiliations.sql` is a short-term option.

**Comment by mariel-oar** [comment]
ok, that works. The point is just to make safeguard ourselves from accidentally clicking these (especially as new team members are onboarding)

**Comment by obrienad** [comment]
@mariel-oar - just checkin if you only want us to do the copy update (1 point) OR look at report problem too (3 points).

**Comment by mariel-oar** [comment]
Just the copy update @obrienad

**Comment by obrienad** [comment]
Thanks!
