### ISSUE TITLE
Browser is unresponsive when clicking the Claim this Facility link on the facility details page

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1392]
## Overview

Browser is unresponsive when clicking the Claim this Facility link on the facility details page

### Steps to Reproduce

* Log in
* Click the "Facilities" tab
* Select a facility
* Click "Claim this Facility"

**Comment by TaiWilkin** [comment]
Is it possible this is related to [#1297](https://github.com/open-apparel-registry/open-apparel-registry/issues/1297)?

**Comment by jwalgran** [comment]
> Is it possible this is related to #1297?

Cant rule it out yet.

I checked out `2.41.1`, ran `./scripts/update`, and restarted my server.

When I click the claim link the claim wizard loads and renders, but then an error page from WDS is shown

![2021-06-10 12 01 01](https://user-images.githubusercontent.com/17363/121582352-c08a9980-c9e3-11eb-8261-7ce094c976b3.gif)

When browsing the collected static files without WDS on http://localhost:8081/ there is no visible issue and no error is logged to the console.
