### ISSUE TITLE
Accommodate non-Azavea personnel interactions with development setup

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#14]

**Comment by hectcastro** [comment]
What were the issues that needed to be addressed as part of this?

**Comment by rbreslow** [comment]
I don't really remember. I think there was a desire to make it easy to spin up the OAR locally so folks could contribute. For example, `scripts/setup` will fail for an outside contributor because there isn't documentation on how to setup the `.env` files on S3.

This issue was also created before the transition to Django, when we had inherited the NodeJS application, so the landscape may have been super different at that time too.
