### ISSUE TITLE
New report of downloaded searches

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1408]
## Overview

Through Google Analytics, we can see which searches users are making but we don't know which searches result in a download. That information is very valuable, so we can understand which data is most interesting and useful to our users. However, we don't want to violate privacy of our users, so would want this report to be generated separately from the report tracking individual users and the number of records they download. 

### Is your feature request related to a problem? Please describe.

We don't know which downloads our users are running from our data. 

### Describe the solution you'd like

We'd like a report  of searches users are downloading. This should not be connected to specific users in this report (we have a separate report for that for tracking abuse). For the rolled up report, we'd love the report to show most to least popular searches and convert contributor ID to contributor name for easy analysis. 

Making data will be visible in Django is covered by #1698

### Implementation

- Create a new Python report
- Normalize the URL query string  arguments (a or b is the same as b or a)
- Process query string arguments  into list of human-readable items (convert IDs to names)
- Group by month and count
  - **QYESTION** Should be group by month, quarter, something else? 

### Additional Context

cc @katieashaw @isaacokunato

**Comment by katieashaw** [comment]
Is this work that could be done in tandem with [issue 1496](https://github.com/open-apparel-registry/open-apparel-registry/issues/1496)?

**Comment by obrienad** [comment]
Clarity required from OAR re: what they're looking for: common URL strings? Common contributor search? Country search?

**Comment by mariel-oar** [comment]
Captured in 1698, we can close this ticket 

the report spec'd in 1698 should match the other one justin pulled (@mariel-oar , link that file here and to 1698)
