### ISSUE TITLE
Address getting cut off on facility profile

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1413]
## Overview

The full address of this facility (and maybe others) is being cut off: https://openapparel.org/facilities/LK2019085651YA4

### Expected Behavior

We should easily be able to view the whole facility name and address.

### Actual Behavior

The bottom line of the address is cut off. It seems to be related to long names and addresses going beyond a certain number of lines. 

### Steps to Reproduce

https://openapparel.org/facilities/LK2019085651YA4
https://openapparel.org/facilities/LK2019083BPWQY0

### Demo

![Screen Shot 2021-07-01 at 3 21 11 PM](https://user-images.githubusercontent.com/80268596/124178853-fcaf9800-da7f-11eb-8f79-aea51ebf9cad.png)
![Screen Shot 2021-07-01 at 3 21 05 PM](https://user-images.githubusercontent.com/80268596/124178876-01744c00-da80-11eb-90a2-833722570229.png)

### Additional context

cc @katieashaw

**Comment by jwalgran** [comment]
@lederer Could you please recommend a fix for this?

**Comment by lederer** [comment]
👍   Deleting the `max-height` declaration from `.panel-header` oughta do it.

https://github.com/open-apparel-registry/open-apparel-registry/blob/9adbf77caed1add5dc0789b80ba19c3cf9124418/src/app/src/styles/css/Map.css#L35

**Comment by katieashaw** [comment]
@jwalgran If this is a quick fix and can be snuck into the next sprint, that would be great!
