### ISSUE TITLE
Replace the filter dropdowns on the map page with autocomplete lists and populate them with data fetched from the new API

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#145]
## Overview

The contributor and country lists will have dozens or hundreds of items. Make it easy to select items by using an autocomplete

### Describe the solution you'd like

* Choose an autocomplete UI component and add it to the page.
* Populate the autocompletes with data fetched from new API endpoints.

### Additional Context

<img width="731" alt="screen shot 2019-01-24 at 11 43 00 am" src="https://user-images.githubusercontent.com/17363/51700918-77ca1580-1fcd-11e9-9fb3-021543ae58ed.png">

**Comment by kellyi** [comment]
Material-UI, the UI library being used in the application, has this:

https://material-ui.com/demos/autocomplete/
