### ISSUE TITLE
When an additional data point field is empty for a facility, data point should not show up on a facility profile

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1522]
## Overview

As pictured in this screenshot, a user has uploaded data for a particular data point, but not for all of their facilities. For the facilities that don't have data in this data point, the field still shows up on the facility profile but is blank:

![Screen Shot 2021-11-04 at 10 54 46 AM](https://user-images.githubusercontent.com/80268596/140336925-0d8578e4-7cca-4daa-87f2-1039eea8e65b.png)

### Expected Behavior

Instead, when a field is empty, that data point should not show up on the facility profile. 

### Actual Behavior

Explanation from Tai:

Looking back at our notes on the issue, we had intended empty fields to be hidden. It looks like the value of the field being returned for that facility is a different form of “empty” than we expected, so it’s not hiding the field correctly.

Essentially, they did “submit” the field for the facility, but it was an empty string (“”) and we’re only checking for null (no value at all). In a list where some facilities have values for a field and some don’t, I think it’s going to come through as an empty string for the rows without the field, since the field/column is technically present for the facility list item. Ideally, we should adjust how we’re checking for empty fields on our end and exclude fields that are empty strings.

cc @katieashaw

**Comment by jwalgran** [comment]
Moved out of the sprint in favor of #1522

**Comment by emilyhu0106** [comment]
I am having issue recreating this error - I contributed this [test list](https://app.zenhub.com/files/159699912/7324e1e3-a3e7-4d30-bc42-f5e3c0aff8fa/download) to see how it will behave for `'    '`, `''`, or `null` in both embed and normal mode. The "Type of Facility" and "Type of Product" is not showing and `''`, and `null` will be empty value

**Comment by jwalgran** [comment]
I think we can move this issue to `Verified`, and I will do so. In #1627 we reworked how the embed sidebar renders fields to work with the new extended profile fields.

**Comment by mariel-oar** [comment]
Seeing this again on embedded maps in production, where parent company and product type fields are displayed but empty.

![Screen Shot 2022-03-07 at 10 04 40 AM](https://user-images.githubusercontent.com/97469356/157052271-87a258e8-06c8-4d35-9e58-9b198cfb5201.png)

**Comment by jwalgran** [comment]
When we switch on the new facility detail sidebar in production we will also switch to using our new extended field handling on embedded maps rather than using the old "custom field" handling that is resulting in these empty fields being displayed on embedded maps.
