### ISSUE TITLE
Add space between GPS coordinates and sentence about amending them

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1526]
## Overview

We have implemented a new feature that allows us to add a sentence after GPS coordinates that have been amended. Currently, that sentence comes directly after the GPS coordinates with no space or line break:

![Screen Shot 2021-11-11 at 1 00 27 PM](https://user-images.githubusercontent.com/80268596/141294582-c9098afc-29e5-4edf-b7a3-79500f8460d0.png)
https://openapparel.org/facilities/CN2020070MPR4Z1?q=CN2020070MPR4Z1

### Expected Behavior

We would like the amending sentence to start directly below the GPS coordinates (rather than immediately after them), to make it easier to read and digest.

**Comment by TaiWilkin** [comment]
Specific facilities where this is occurring can be found here: https://github.com/open-apparel-registry/open-apparel-registry-clients/issues/45

**Comment by hlennett** [comment]
Formatting ok in this one: https://openapparel.org/facilities/CN2019310YD1N57?q=CN2019310YD1N57

But not this one: https://openapparel.org/facilities/CN2021188TE73PF?q=CN2021188TE73PF

As additional examples.

**Comment by hlennett** [comment]
@mariel-oar This was resolved with EP launch. Feel free to close.
