### ISSUE TITLE
Edit embed field config to allow marking a field as searchable

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1533]
## Overview

Edit embed field config to allow marking a field as searchable and add model and API support for persistence.

### Describe the solution you'd like

- Model changes
  - Add `searchable` to `EmbedField`, non null default False
  - Add `text_search_label` to ` EmbedConfig`, nullable string
  - Add `custom_text` to `FacilityIndex`, nullable string
- Update API to allow passing a `searchable` value
- Update UI to allow making embed fields as "Searchable"

**Comment by TaiWilkin** [comment]
Design notes: Use a checkbox to the right of the fields (but before the hidden draggable buttons). Make this disabled and a very pale grey unless a box is marked 'visible'; deselect the checkbox if a box was visible and searchable but is marked invisible. Have a 'header'/label above the list of fields' checkboxes marked 'Searchable' with an 'i' icon; on hover, show instructions/definition for searchability.
