### ISSUE TITLE
Pull Reports for our end of 2021 funder reporting

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1555]
## Overview

We will need Azavea to manually pull the following for us, so that we can satisfy our 2021 funder reporting requirements:

Number of affiliations per facility (average) (at time of report)

- We cannot pull this report as it crashes the OAR. We would like the monthly figures for this for July 2021 - December 2021. 

Percentage of database with more than one affiliation

- We cannot pull this report as it crashes the OAR. We would like the monthly figures for this for July 2021 - December 2021. 

Platform % Uptime

- We would like this pulled for Q3 (July 1 - September 30 2021) and Q4 (October 1 - December 31 2021)

We will need this information by mid-January 2022 (January 14 at the latest).

**Comment by hlennett** [comment]
cc @katieashaw

**Comment by jwalgran** [comment]
To run the SQL reports, I ran `psql` 

- Set the separator to `,`

```
\f ','
```

- Set the output format to unaligned

```
\a
```

- Copy/pasted the contents of `average_affiliations.sql` into the `psql` session and ran it. Copied the output to a CSV file.
- Copy/pasted the contents of `percent_facilities_with_multiple_matches.sql` into the `psql` session and ran it. Copied the output to a CSV file.

To get the percent uptime reports I 

- Logged into Panopta
- Visited the reports page https://my.panopta.com/report/ListReports#reports
- Under "Availability Report" clicked "Create"
- Specified a data range and filtered by OpenApparelRegistry
- Ran through the process twice, once for Q3 2021 and again for Q4 2021

I emailed the report outputs to @hlennett and @katieashaw
