### ISSUE TITLE
Embedded Map CSV/Excel downloads not including all fields

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1559]
## Overview

When you download CSV/Excel files from an Embedded Map, it is currently only downloading the fields that are listed on the full OAR, not all of the fields loaded into the Embedded Map. 

See examples of maps with additional data points:
https://www.levistrauss.com/sustainability-report/community/supplier-map/
https://www.kathmandu.co.nz/worker-wellbeing

Part of the draw of this feature is that users will be able to have all of their data points downloaded into a machine-readable format. Is this a bug and is expected to be working or something that needs to be built? 

cc @katieashaw

**Comment by jwalgran** [comment]
The additional fields are already available in the sidebar, and we assemble CSVs/Excel on in the browser, so it should be relatively straightforward to add the additional fields to the download.
