### ISSUE TITLE
Vanessa & Mariel Super Admin Access on Staging and Prod

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1574]
## Overview

Please give Vanessa and Mariel super admin access on Staging and Prod. They have both created accounts on each:

Vanessa:
https://openapparel.org/admin/api/contributor/2362/change/
https://staging.openapparel.org/admin/api/contributor/860/change/

Mariel:
https://openapparel.org/admin/api/contributor/2367/change/
https://staging.openapparel.org/admin/api/contributor/861/change/

cc @katieashaw

**Comment by jwalgran** [comment]
I reopened this just so that we can report on it's completion at our next sprint review on Thursday. Will re-close it then.

**Comment by hlennett** [comment]
@jwalgran I ended up submitting this in issue #1576 which was why I closed it. I couldn't figure out how to get it from Draft to regular issue haha
