### ISSUE TITLE
Vanessa and Mariel Super Admin Access on Staging and Prod

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1576]
Please give Vanessa and Mariel super admin access on Staging and Prod. They have both created accounts on each:

Vanessa:
https://openapparel.org/admin/api/contributor/2362/change/
https://staging.openapparel.org/admin/api/contributor/860/change/

Mariel:
https://openapparel.org/admin/api/contributor/2367/change/
https://staging.openapparel.org/admin/api/contributor/861/change/

cc @katieashaw

**Comment by jwalgran** [comment]
Via the database I set `is_staff` and `is_superuser` to true for these 2 accounts in both staging and production.
