### ISSUE TITLE
Add Terraform configuration for AWS Batch

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#158]
* `aws_batch_compute_environment`
* `aws_batch_job_queue`
* `aws_batch_job_definition`
* Create an ECS Container Instance IAM Role and thread to `aws_iam_instance_profile`
* Create Batch IAM role
* Create Spot Fleet IAM role
* Utilize [ECS-Optimized Amazon Linux AMI](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html)

Once everything's wired up, things should look similar to what we have here: https://github.com/azavea/raster-foundry-deployment/tree/develop/core/terraform

**Comment by rbreslow** [comment]
Not sure if we considered utilizing GPU workloads, but that would require creating a custom AMI: https://docs.aws.amazon.com/batch/latest/userguide/batch-gpu-ami.html.

**Comment by jwalgran** [comment]
As of right now I don't anticipate needing much compute power at runtime and expect running on the CPU will be sufficient.
