### ISSUE TITLE
Persist filter selections as query string arguments to allow bookmarking/sharing a search

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#162]
## Overview

Persist the facility filter choices on the map page in the query string. Restore the filter selections from the query string arguments when the page is loaded. 

### Additional Context

Depends on #159

**Comment by kellyi** [comment]
The app also current has a "Share" button on the map which generates some kind of string -- we should change how that "Share" button works to use the same querystring.

**Comment by kellyi** [comment]
As part of #166 I updated the "Share this search" button on the map to copy `window.location.href` to the clipboard, which means it'll just copy the base url along with any querystring added here.
