### ISSUE TITLE
Improve searchability of contributor drop down (admin site) 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1643]
## Overview

In the admin site, there are several pages that have a contributor drop down field (e.g. Source page - [https://openapparel.org/admin/api/source/](https://www.google.com/url?q=https://openapparel.org/admin/api/source/&sa=D&source=docs&ust=1648644038317996&usg=AOvVaw3gBOHEJoxBjHZPeNoJd9u8)). When the items in the dropdown are viewed, there seems to be no order to how the items are displayed. This creates issues in using the tool given the growing number of contributors. 

Proposal: update the display of the items in the dropdown to be either alphabetical or chronological, based on their associated number that identifies the sequence in which they were added to the OAR. 

If it is straightforward, it would be ideal that the dropdown be searchable with partial-matches enabled. 

Demo: 
The drop down in question appears on this page when you click on a specific source: [https://openapparel.org/admin/api/source/341398/change/](https://www.google.com/url?q=https://openapparel.org/admin/api/source/341398/change/&sa=D&source=docs&ust=1648644038318100&usg=AOvVaw1zb63TM9tJ4va_unGKTG05)

**Comment by mariel-oar** [comment]
![Screen Shot 2022-02-11 at 12 53 52 PM](https://user-images.githubusercontent.com/97469356/153662850-9663f581-d754-40e1-ad97-9e5f3b789dde.png)

**Comment by jwalgran** [comment]
I estimated this as a :one: since the Django admin provides a method for sorting the options list

https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_for_foreignkey
