### ISSUE TITLE
PUT request to update embed map settings takes 5 to 12 seconds to complete on staging

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1660]
## Overview

PUR request to update embed map settings takes 5 to 12 seconds to complete on staging. To date we have not reproduced the issue in development or production.

This issue covers investigation into the issue and a fix if it is small. If it is not a small fix create a follow up issue.

We suspect that the issue may be that we are reindexing searchable fields when any change is made to the map. We should only trigger re indexing when searchable fields change

**Comment by emilyhu0106** [comment]
After modifying embedded custom text search in #1652, the PUT request speed on staging for map style changes and field visibility changes is significantly faster and as fast as in development, but still takes 5-12 seconds for the searchability update.

Tai and I think we can either add a sentence to acknowledge the users in the description or keep investigating in the cause. @jwalgran What's your opinion on this?

**Comment by emilyhu0106** [comment]
@jwalgran Do you mind giving your input on this [comment](https://github.com/open-apparel-registry/open-apparel-registry/issues/1660#issuecomment-1047234582)?

**Comment by jwalgran** [comment]
Sorry I missed the previous notification.

I do think a "toast" message saying that updating search fields can take some time is a good idea but I also thing we should do what we regularly do for long running requests and a loading spinner while the PUT request is pending and clear the loading spinner when the the PUT request either succeeds or fails.

**Comment by jwalgran** [comment]
Adding the spinner should be implemented under https://github.com/open-apparel-registry/open-apparel-registry-clients/issues/79

The PR to add the spinner should reverence both this issue and https://github.com/open-apparel-registry/open-apparel-registry-clients/issues/79 so that everything is linked together and referenceable.
