### ISSUE TITLE
Add STRTA for running one-off tasks against the ECS cluster

### ISSUE THREAD

**Issue by hectcastro** [open-apparel-registry/open-apparel-registry#167]
Add a STRTA script that has the ability to identify the most recent CLI task definition, then creates an instance of it on the appropriate ECS cluster.

(Useful for running migrations and other one-off management command tasks.)

- Space separated arguments passed to deployment/scripts/manage are correctly passed as the command override (may need to be comma separated)
- A full url to the launched task is printed to the console i.e.
https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/ecsStagingCluster/tasks/GUID-d853-4774-a97a-6e226cf690b6/details

**Comment by jwalgran** [comment]
Is this a dependency of #165, or does this issue supersede it?

**Comment by hectcastro** [comment]
Ah, I created this without paying attention to the existing open issues. Are you OK with us doing it as part of our sprint, or did you already slot it into yours?

Also, happy to close this issue in favor of that once since it was opened first.

**Comment by jwalgran** [comment]
Yes, it makes sense for this to be part of your ops sprint. Thanks for adding it in.

I'll fold the requirements from the previous issue into this one.
