### ISSUE TITLE
Codify process of creating Batch AMI w/ ephemeral storage

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#168]
>An instance store provides temporary block-level storage for your instance. This storage is located on disks that are physically attached to the host computer. Instance store is ideal for temporary storage of information that changes frequently, such as buffers, caches, scratch data, and other temporary content, or for data that is replicated across a fleet of instances, such as a load-balanced pool of web servers.

>An instance store consists of one or more instance store volumes exposed as block devices. The size of an instance store as well as the number of devices available varies by instance type.

>The virtual devices for instance store volumes are `ephemeral[0-23]`. Instance types that support one instance store volume have `ephemeral0`. Instance types that support two instance store volumes have `ephemeral0` and `ephemeral1`, and so on.

In order to define the block device mapping required to mount ephemeral storage in AWS Batch, we need to create a custom AMI based on one of Amazon ECS AMIs. This process should be codified using Packer and captured within a Jenkins job that takes an ECS AMI ID as input.

Once this process is complete, ensure that the volume mounts for job definitions are updated to map the ephemeral storage mount on the host with wherever path the jobs use for scratch space inside of the container. Also, ensure that instances selected for the compute environment all support a fair amount of ephemeral storage.

We can probably use the same Packer templates from https://github.com/azavea/raster-foundry-deployment/tree/develop/batch/packer.

We can probably configure a Jenkins job on `civicci01` similar to http://jenkins.staging.rasterfoundry.com/job/raster-foundry-batch-ami/.

For additional reference, this was the issue where we implemented the same things in Raster Foundry: https://github.com/azavea/raster-foundry-platform/issues/123.

Additional AWS resources: 
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-ami-storage-config.html
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html

**Comment by rbreslow** [comment]
Blocked by #158

**Comment by rbreslow** [comment]
Also worth nothing, it looks like once https://github.com/terraform-providers/terraform-provider-aws/issues/6454 is closed out, we could use EC2 Launch Templates to mount ephemeral storage on an existing Amazon ECS AMI.

**Comment by jwalgran** [comment]
For what it's worth, I don't anticipate the container needing any scratch space. 
- We will be reading the data we need from the database and writing results back to the database. 
- Any other static data we need can be baked into the container.
- Logging will go to stdout/stderr or a service like Papertrail.

**Comment by hectcastro** [comment]
Closing due to last comment that suggests this functionality will be unnecessary.
