### ISSUE TITLE
Revise API documentation for Extended Profile

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1689]
## Overview

Update the draft extended profile API documentation to reflect the completed implementation and include the following

- New endpoints 
- New extended field query parameters on the facility search endpoint
- Updated examples of request and response JSON objects
- Details explanation of the data schema for extended profile values returned from the APIs

**Comment by jwalgran** [comment]
The document is available here

https://docs.google.com/document/d/1tfkLpzhIDbvsTKYUTWchHTq2yt-a_-_U6XSuwPhJniE/edit#

**Comment by TaiWilkin** [comment]
@jwalgran I added a few notes to the document, but it's looking good. We might want to add the new product_types endpoint (in progress) to the docs as well
