### ISSUE TITLE
Nirapon list issue 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1691]
Summary: 
The brand Nirapon uploaded a facility list with a total of 481 facilities to the OAR; however when you search for them on the public side of OAR, they show up as having 482 facilities. 

Additional context: 
They previously had uploaded a list and not completed confirm/reject. That list is not active and we have not split any of their facilities through manual moderation. 

You can see they have 481 facilities in their upload here:https://openapparel.org/lists/1482
You can see the 482 facilities here: https://openapparel.org/?contributors=2139

The original list that they uploaded: 
[OAR_Contributor_Nirapon CAP Closed_Feb 2022_481 Factories.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8178792/OAR_Contributor_Nirapon.CAP.Closed_Feb.2022_481.Factories.xlsx)

## Techical Implementation

- Review the research in https://docs.google.com/spreadsheets/d/1lz3BLLY6zM2MUOoGnA51hVj1ZEijUivs/edit?usp=sharing&ouid=104202036790313999359&rtpof=true&sd=true
- Ensure that facilities are reindexed when there is a list replacement.
- Reindex the Nirapon facilities in production

**Comment by TaiWilkin** [comment]
When we search by Nirapon, we return 482 facilities. However, when we search by the [Nirapon CAP Closed_Feb 2022](https://openapparel.org/?contributors=2139&lists=1482) list, we only return 474. I'm attaching a csv of the "stale" items that aren't linked to a list for future reference (in case the data state changes by the time we are able to look into this). 
[nirapon.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/8179136/nirapon.csv)
My suspicion is that we aren't correctly reindexing some facilities when we deactivate their list, but this will require additional research time to confirm.

**Comment by hlennett** [comment]
Did some investigation into discrepancies between the list that Nirapon uploaded and what's available via search/download in their list via the OAR. You can see the results/notes here: https://docs.google.com/spreadsheets/d/1lz3BLLY6zM2MUOoGnA51hVj1ZEijUivs/edit?usp=sharing&ouid=104202036790313999359&rtpof=true&sd=true

**Comment by mariel-oar** [comment]
@jwalgran @TaiWilkin , do you think it's worth having Nirapon upload their list again to see if this is still happening? I'm wondering if this could somehow have been affected by the other bug tickets that were closed last sprint. 

cc: @hlennett

**Comment by mariel-oar** [comment]
@jwalgran @obrienad, is there a way to make this a 1pt issue? 

Essentially, we don't want to spend 3 pts on this now (especially given the focus on infrastructure work else where - could this just sort itself out?) 

e.g. is there a way to manually make the Nirapon facilities on OAR match their list? 
there are a number of facilities on their list that are not showing as associated with them on OAR, and a number of facilities that are showing as associated with them that were not on their list. We are OK with this being a manual fix.

**Comment by jwalgran** [comment]
I added my notes to a column in @hlennett 's invaluable research workbook. https://docs.google.com/spreadsheets/d/1lz3BLLY6zM2MUOoGnA51hVj1ZEijUivs/edit?usp=sharing&ouid=104202036790313999359&rtpof=true&sd=true

AS of today searching for Nirapon and searching for Nirapon's single active list both return 474 records. For good measure I ran the "stale" items @TaiWilkin extracted into [nirapon.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/8179136/nirapon.csv) through the reindexing process with the following command

```
./scripts/manage ecsmanage -e production index_facilities BD2019108FJB8FY BD2019091AKQ9ZR BD2021337RJ83DT BD2019100QS9W08 BD20192594RMK05 BD2020021D86JPG BD2019083N1QFG9 BD2019083Z1QP5F
```
This did not change the search results.

As of today I did not encounter any remaining item that show up as associated with them in an OAR search that do not appear on the list they submitted.

**Comment by obrienad** [comment]
@mariel-oar Justin had completed the work ahead of your inquiry on reducing the point allocation.

**Comment by mariel-oar** [comment]
thanks @obrienad, i see that this ticket is still in the inprogress column on Zenhub, but you said it's completed. Will this be in the release that goes out today (5/12)?

**Comment by obrienad** [comment]
Thanks, Mariel! Per @jwalgran 's last reply on the thread, there wasn't a fix to offer.
