### ISSUE TITLE
Parent company dropdown in facility claims and facility search

### ISSUE THREAD

**Issue by vrwOAR** [open-apparel-registry/open-apparel-registry#1746]
## Overview

When submitting the form to claim a facility, the parent company field is populated with the listing of all contributors.
Also, when managing the claimed facility as an approved claimant, the parent company field operates the same way.

### Expected Behavior

The parent company field on both the claim form and the search form should be populated with parent company entries from EP submissions or previous facility claims (previous facility claims create EP field values, so we only have to worry about pulling values from the ExtendedFields table).

### Actual Behavior

Drop down fields for parent company is populated with all contributor data

### Steps to Reproduce

* [Facility claim](https://staging.openapparel.org/facilities/BR2020057K5F3HZ/claim)
* [Facility owner/claimed facility management page](https://staging.openapparel.org/claimed/71/)

* both fields for parent company list all OAR contributors and not designated parent company names

### Demo

![Screen Shot 2022-03-20 at 22 01 31](https://user-images.githubusercontent.com/97313337/159199961-4ac60d40-cd52-4ab3-8488-1d7fd4761e8b.png)

![Screen Shot 2022-03-20 at 21 59 14](https://user-images.githubusercontent.com/97313337/159199984-41673b51-720f-454e-9915-b20523b27f12.png)

### Technical Implementation

- Add an API endpoint for valid parent company values similar to `GET /api/sector`
  - Ensure that the values match what is saved in the FacilityIndex
- On the search page, load the choices when "More filters" is clicked
- On the facility claim form use the choices loaded from the new API instead of the list of registered contributors.

**Comment by mariel-oar** [comment]
Linked to #1751

**Comment by mariel-oar** [comment]
@TaiWilkin, looking at this on openapparel.org, it doesn't look like it's yet working this way and on OS Hub it's still populating with all contributors values.

**Comment by obrienad** [comment]
Replying in thread:

1. The feature only appears in OS Hub staging given the decision to not spend more time building features for OAR (a separate development environment).
2. It turns out there was not a bug, but there are that many raw parent companies that have been submitted as part of extended field data, so the feature is performing as expected in that regard on OS Hub.
