### ISSUE TITLE
Number formatting on EM Custom Fields (Decimal Points) 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1748]
## Overview

HL: I'm no longer seeing decimal points in number of workers, but I uploaded another numeric field as a custom field for an embedded map and it has a decimal point. There were not decimal points in the data I uploaded. This is happening in multiple numeric fields. This is a showstopper because when I try to search by that data point as part of the custom functionality, it won't come up unless I add a decimal point. 

### Expected Behavior

When a custom field is entered as a number format, convert to text to remove number-specific formatting (e.g. ".0") 

### Steps to Reproduce

* enter number data as custom field in EM (without a decimal point) 
* search by number data without adding the decimal point 
* search will not return a match unless decimal point is added 

### Demo

Columbia has paid for this functionality and it needs to work: 
<img width="1080" alt="Screen Shot 2022-03-21 at 9 28 56 AM" src="https://user-images.githubusercontent.com/97469356/159273479-2806b512-b657-4df5-a701-52b864724a22.png">

cc: @hlennett @katieashaw

**Comment by hlennett** [comment]
You can see the Embedded Map in this account: https://staging.openapparel.org/dashboard/lists/?contributor=872
