### ISSUE TITLE
Updating the format for downloaded files (CSV, Excel) 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1752]
## Overview

On download of EP data, we do not see the processed values (e.g. for number of workers or facility type). 

Also confusing is that we see the raw processing and facility type data broken out, even though they are submitted as one - it feels repetitive and confusing. 

### Expected Behavior

Raw uploaded values and processed values are downloadable via excel. 

### Steps to Reproduce

* filter by contributor with EP list [(https://staging.openapparel.org/facilities?contributors=861&lists=803)](https://staging.openapparel.org/facilities?contributors=861&lists=802) 
* download data
* open file to see that processed values are not displayed 

### Demo

For example, you can see that in this download, only the raw values for number of workers is downloading: 
[facilities (3).xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8315817/facilities.3.xlsx)

### Technical Implementation
 
Reference this mockup
[Example_DataDownload.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8543524/Example_DataDownload.xlsx)

- Rename facility_type_raw to processing_type_facility_type_raw and drop the duplicate column processing_type_raw
- Order the columns so that column with raw values comes first with processed values to its right; for processing/facility type use: processing_type_facility_type_raw, processing_type, facility_type
-  De-dup facility types when multiple values map to the same facility type within one contributor (this change is illustrated in the attached file where there are 3 processing types uploaded by the same contributor that map to "Final Product Assembly" - we don't need to display "Final Product Assembly" 3x. We do want to display this value again if a different contributor uploaded this.
 - Change CSV/Excel to have multiple rows per facility
	 - One row per contributor
	 - First row shows the same the "top values" from the facility details sidebar
	 - For each contributor, iterate over `extended_fields` to get column values for the corresponding row

**Comment by obrienad** [comment]
Labeled blocked pending further OAR discussion

**Comment by mariel-oar** [comment]
1. We don't need the processed number of workers value to be downloadable. 
2. Re: the processed and raw values for processing and facility type ---> Rename facility_type_raw to processing_type_facility_type_raw and drop the duplicate column processing_type_raw
3. Order the columns so that column with raw values comes first with processed values to its right; for processing/facility type use: processing_type_facility_type_raw, processing_type, facility_type 
4. Can we update it so that the contributor of additional data points only displays after the list of all the data points they uploaded instead of each individual one? (e.g. see the difference between cells L2 and M6 on the 'Update' tab of the attached workbook) 

Nice to have (should this be a future ticket?): 
- De-dup facility types when multiple values map to the same facility type within one contributor (this change is illustrated in the attached file where there are 3 processing types uploaded by the same contributor that map to "Final Product Assembly" - we don't need to display "Final Product Assembly" 3x. We do want to display this value again if a different contributor uploaded this. 
- Could we nest additional contributors as rows below the initial contribution? See attached workbook, Update tab for example.

[Example_DataDownload.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8542343/Example_DataDownload.xlsx)

**Comment by mariel-oar** [comment]
@TaiWilkin, @jwalgran, my understanding was that the address contributions would still be included in the csv download, like in the Example_datadownload.xlsx. 

I'm getting a download file with only extended field values included (see attached) 
[facilities (2).xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/9283506/facilities.2.xlsx)

**Comment by TaiWilkin** [comment]
Hi @mariel-oar - our understanding was that core fields (name, address, country, latitude, longitude) would only be listed once for each facility, leaving those columns blank for additional facility list items (see Example_datadownload.xlsx, 'Update' tab). Can you confirm whether you're looking to add the address to additional facilities, or if you're seeing addresses missing for the base row?
