### ISSUE TITLE
Claimant data not prioritized

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1754]
## Overview

Not working as expected: Claimant address is not the primary. Address was submitted via claim form. 

### Expected Behavior

Data points from claimant should be prioritized. 

### Steps to Reproduce

* Submit claim on facility with EP data 
* See that their data is not primary on facility profile (e.g. in example below address submitted by XYZ brand is not listed first). 

### Demo

[Example of this behavior on staging](https://staging.openapparel.org/facilities/US2020212H79QR1)
[Another example](https://staging.openapparel.org/facilities/US2022080TK04GQ)

### Technical Implementation

- Add nullable `location` Point field to the FacilityClaim model and the `FacilityClaim` API
- When saving the claim form, geocode the address (if not blank) by getting from the exiting /api/geocode endpoint
	- Show a failure message if the address is not found.
- Alter the sorting off address/point location results in the facility details API to that approved claim addressa nd point location sorts to the top.
- When saving the FacilityClaim, if there is a geocoded location on the claim,  update location of the Facility record to match

**Comment by jwalgran** [comment]
The reason behind this may be the know issue that we do not geocode the address on the claim form and we did not want to promote an address to the top of he list without being able to promote a corresponding lat/lng. The proposed implementation for this and estimate is to add geocoding to the claim form and a data migration to retroactively geocode existing claim addresses.

**Comment by mariel-oar** [comment]
This seems like something we should include in the single facility upload anyways, which is close to facility claim forms - would that make sense to tackle this with single form, @jwalgran @obrienad? 

cc: @hlennett
