### ISSUE TITLE
Name and addresses appear to be showing today's date as the contribution date

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1781]
## Overview

Name and addresses appear to be showing today's date as the contribution date

An example from production:

https://openapparel.org/facilities/IN2019083MPMF72

<img width="363" alt="Screen Shot 2022-03-30 at 8 19 54 AM" src="https://user-images.githubusercontent.com/17363/160870859-5d8d95d5-e3f9-4693-acd4-104f7037c34a.png">

**Comment by jwalgran** [comment]
The `formatAttribution` function uses `moment(createdAt)` to build a date object. 

https://github.com/open-apparel-registry/open-apparel-registry/blob/1aebc3c0343b4708622164f7041bc11b0697d852/src/app/src/components/FacilityDetailSidebarExtended.jsx#L91-L96

if `createdAt` is null, this is going to create a date object for the current date. `name` and `address` items under `extended_fields` do no have a data property, which would explain the null value.

<img width="509" alt="Screen Shot 2022-04-25 at 11 43 28 AM" src="https://user-images.githubusercontent.com/17363/165153811-82f285d9-d66a-4ca9-ba5b-9152660f45ea.png">

**Comment by mariel-oar** [comment]
Testing feedback: 

- It looks like today’s date is still showing up but only for the parent company attribute
- Issue resolved on these facilities (none of them have a parent company listed): VN2020070RKZ193, CN20201914QR6D6, TR2021204WQQQ6R 
- These are all showing today's date by only for parent company: IN2019083Z8TD51, GT2019083TBFK70, BD2019087GMGA43, PK20212306XKW2S, CN2019085HVM8M6

**Comment by jwalgran** [comment]
Re showing today's date for parent_company, L looked up the facilities listed and the updated date is today. This is expected if lists reuploaded and the existing extended field records are updated.

```sql
select id, facility_id, created_at, updated_at
  from api_extendedfield
 where field_name = 'parent_company'
   and facility_id in ('IN2019083Z8TD51', 'GT2019083TBFK70', 'BD2019087GMGA43', 'PK20212306XKW2S', 'CN2019085HVM8M6');
```

Note that these datetimes are UTC

```
  id   |   facility_id   |          created_at           |          updated_at
-------+-----------------+-------------------------------+-------------------------------
 33377 | BD2019087GMGA43 | 2022-03-15 13:45:29.413155+00 | 2022-04-26 20:59:08.331462+00
 34331 | BD2019087GMGA43 | 2022-03-16 05:44:42.415085+00 | 2022-04-26 20:59:23.004125+00
 62740 | BD2019087GMGA43 | 2022-03-21 19:14:43.030001+00 | 2022-04-26 20:59:50.920294+00
 44160 | CN2019085HVM8M6 | 2022-03-17 01:26:12.71388+00  | 2022-04-26 20:59:25.963928+00
 44660 | GT2019083TBFK70 | 2022-03-17 01:26:21.249667+00 | 2022-04-26 20:59:26.330867+00
 84911 | IN2019083Z8TD51 | 2022-04-25 21:23:22.214108+00 | 2022-04-26 21:00:06.388476+00
 34562 | IN2019083Z8TD51 | 2022-03-16 05:44:48.467321+00 | 2022-04-26 20:59:23.158907+00
 34707 | PK20212306XKW2S | 2022-03-16 05:44:52.312055+00 | 2022-04-26 20:59:23.481754+00
 64521 | PK20212306XKW2S | 2022-03-21 19:15:42.509938+00 | 2022-04-26 20:59:48.625883+00
 85755 | PK20212306XKW2S | 2022-04-25 21:23:26.863268+00 | 2022-04-26 21:00:09.115062+00
(10 rows)
```

**Comment by jwalgran** [comment]
In our checkin call we determined that the `updated_at` was set to the date on which we ran the migration on staging to reprocess all the `parent_company` values. @mariel-oar said that this ok. 

At this time no additional code updates appear to be required for this issue.
