### ISSUE TITLE
Facility with no contributor

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1796]
A couple of examples of facilities that have no Contributor section: 
https://openapparel.org/facilities/CN202031463D4MB
https://openapparel.org/facilities/DE20220774ZVHM0

The first is the first facility that shows up when you just look at our full database in alphabetical order, so it might be good to address. 

It looks like post-EP launch, anonymized contributors are no longer showing up in the contributor section, so if there are only anonymized contributors on a profile, there's no contributor section. Is this the behavior we want to have? One of these facilities came up in a demo and the stakeholders were a bit confused when they saw it, since our model is showing who is connected to facilities. 

## Technical Implementation

- Use the previous anonymous contributor handling from the old sidebar to the new sidebar.
  - Continue to not not show other contributors in embed mode

**Comment by mariel-oar** [comment]
Thanks @hlennett (model = wireframes? or data model?)

**Comment by hlennett** [comment]
Oh like our mission as an organization.

**Comment by mariel-oar** [comment]
haha yes, got it (thought you might have been saying that there was something public that did show the contributor associations although the profile page wasn't displaying)

**Comment by mariel-oar** [comment]
More examples: 
https://openapparel.org/facilities/IN20190855SBCEK
https://openapparel.org/facilities/CN20211821GPP86

**Comment by hlennett** [comment]
@mariel-oar Was this meant to be closed?

**Comment by mariel-oar** [comment]
no it was not! thank you @hlennett

**Comment by mariel-oar** [comment]
@hlennett , we can see who contributed here: https://openapparel.org/api/docs/#!/facilities/facilities_get_facility_history

looks like both were anonymous and via API. do we want to change this pattern or wait for page changes with OGR?

**Comment by hlennett** [comment]
@mariel-oar I'd love to discuss whether we think it's disconcerting for users or not. As an open data platform, if there's no contributor, is that too jarring? At the very least, we can make an FAQ about it, should we decide not to change.

**Comment by mariel-oar** [comment]
Estimate it for after beta launch, but might need to wait for larger OS Hub pattern updates if it's too big of an estimate (seems like it should be small).
