### ISSUE TITLE
Add babel polyfill for IE11

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#180]
## Overview

The client code is currently missing polyfills for IE11, which means it won't work there:

![screen shot 2019-02-06 at 1 29 12 pm](https://user-images.githubusercontent.com/4165523/52364481-51679980-2a13-11e9-9b25-31a77f11534e.png)

Add the required polyfill so the site works in IE11+

### Expected Behavior

Site should load in IE11

### Actual Behavior

Site fails to load because of some ES6/7 syntax IE11 can't parse.

### Additional context

We typically add the polyfill in our webpack configuration file, but since this is set up in CRA we will have to figure out an alternate way to handle it.

**Comment by caseycesari** [comment]
Is this a good opportunity to use https://babeljs.io/docs/en/babel-preset-env?

**Comment by kellyi** [comment]
Oh, cool -- that's already available in the package.json file but not yet configured, so I'll see about adjusting package.json to use it.

**Comment by kellyi** [comment]
I looked into this a bit more and it seems like the immediate problem is a missing polyfill for `String.prototype.startsWith`, which is required by redux-act.
