### ISSUE TITLE
Pattern in which kinds of files/docs generate errors for blank rows

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1829]
Sometimes, when users upload a list, the blank rows in their sheet generate errors (Error_Parsing) and sometimes they do not. 

You can see with Ralph Lauren's most recent update, they have 555 errors from blank rows, but the previous version of that list (they said it was the exact same file/formatting), did not generate those errors: https://openapparel.org/dashboard/lists/?contributor=1337

Other examples of lists with lots of errors that appear to be from blank rows:
OVS: https://openapparel.org/dashboard/lists/?contributor=981
Next Plc: https://openapparel.org/dashboard/lists/?contributor=194 - their September 2021 list
Hylo Athletics: https://openapparel.org/dashboard/lists/?contributor=1879 - their December 2021 list

Curious if there's a pattern in why sometimes blank rows are read as errors and sometimes not? It's not a deal-breaker but it's jarring for users to see hundreds of errors in their data.

**Comment by mariel-oar** [comment]
I think this is resolved by #1835 and can be closed

**Comment by hlennett** [comment]
Oooh exciting!
