### ISSUE TITLE
Add sector to FacilityListItem and populate it from list and API submissions

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1830]
**NOTE** This and all sector features should only be merged to the `ogr/develop` branch

- Add an additional `sector` column to the csv and xlsx upload templates. (Pipe delimited like other multi-value fields)
  - The templates are hosted on the info site, not committed with the code https://info.openapparel.org/stories-resources/how-to-contribute-data-to-the-oar
  -  The `sector` column is required so insert it near the beginning of the column list  after country, name, and address
  - Attach the updated templates to this issue and send them to the OAR team
- Add a `sector` char array field to `FacilityListItem`
  - Add a migration with 3 operations
    - `AddField` to create the nullable array field
    - `RunPython` to set the value for all existing items to  `['Apparel']`
    - `AlterField` to make it non-nullable
- Update list parsing and API submission handling to store sector values
   -  When converting the raw column value to `sector` `api.processing.parse_facility_list_item` should split values on the pipe character, trim leading and trailing whitespace and title case the value.
   - `api.views.FacilityViewSet.create` should apply the same `sector` value processing and should handle values submitted as either pipe-delimited single strings or arrays of strings (`api.extended_fields.get_product_type_extendedfield_value` has this functionality)

**Comment by maurizi** [comment]
> Add a migration with 3 operations
>      AddField to create the nullable array field
>      RunPython to set the value for all existing items to ['Apparel']
>      AlterField to make it non-nullable

Are we on an old version of Postgres? I've done this in the past to avoid locking a table, but as of PSQL 11 you don't need to do that - https://dba.stackexchange.com/a/216153

**Comment by jwalgran** [comment]
We are running PostgresSQL 12.8 so we should be able to use a default without running into locking issues. Thanks for checkong.
