### ISSUE TITLE
Update facility indexing to include sector 

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1831]
Depends on #1830 

A new `FacilityIndex.sector` array field should be populated with a deduplicated list of sector values submitted by contributors. The method by which multi-value extended fields like `product_type` are indexed should be the inspiration for the implementation.

- Create a new migration to add `sector` to `FacilityIndex`
  - Use `processing_type` as a model for a char array field 
- Add a function to update the `sector` column and add a new data migration to run it
  - The reverse action should be a noop
  - `api.models.index_custom_text` is a similar operation that can be used for inspiration
- Update `index_facilities` to also index sector.

**Comment by jwalgran** [comment]
I added but then removed the blocked label because the ZenHub dependency makes the additional label redundant
