### ISSUE TITLE
Users unable to upload Excel files

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1835]
We've had three users now in recent days who have reached out because they were unable to upload files to the OAR. They are receiving the: "An error prevented uploading that file" message on the Contribute screen. @vrwOAR and I have confirmed that behavior for those three lists on staging. When we change the file to a CSV, we are able to upload it. Attaching the three files here. 

[OAR_Contributor_Template_Additional_Data_Points_Excel (5).xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8629766/OAR_Contributor_Template_Additional_Data_Points_Excel.5.xlsx)

[2.OAR_Contributor_NAKD_April_2022.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8629767/2.OAR_Contributor_NAKD_April_2022.xlsx)

[OAR_ELK_2022_SUPPLIER_LIST_FINAL.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8629757/OAR_ELK_2022_SUPPLIER_LIST_FINAL.xlsx)

@vrwOAR also tested with a couple of Excel files that she was able to previously upload to prod and now do not work when trying to upload on staging:

[OSKLEN_Tier3_Raw_Material_Suppliers_jun2020.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8629800/OSKLEN_Tier3_Raw_Material_Suppliers_jun2020.xlsx)

[Pernambucanas_Domestic_Suppliers_feb2022.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8629801/Pernambucanas_Domestic_Suppliers_feb2022.xlsx)

---

An exception logged in Rollbar when submitting [OSKLEN_Tier3_Raw_Material_Suppliers_jun2020.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8629800/OSKLEN_Tier3_Raw_Material_Suppliers_jun2020.xlsx)

https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/1541/

<img width="1093" alt="Screen Shot 2022-05-05 at 6 31 09 AM" src="https://user-images.githubusercontent.com/17363/166933920-d343f0e5-c11a-4af8-8bf5-5788c2be352e.png">

**Comment by mariel-oar** [comment]
@jwalgran, can you investigate how often this is happening? if it's widespread we think it is a priority to have address.

**Comment by jwalgran** [comment]
@mariel-oar Reviewing reports of the error in production on Rollbar at least 3 users have run into the problem in the last 4 days. I am reviewing a fix now.

**Comment by vrwOAR** [comment]
Adding additional files from two new contributors reporting the same error
[OAR_Contributor_Template_Additional_Data_Points_Excel (5).xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8643208/OAR_Contributor_Template_Additional_Data_Points_Excel.5.xlsx)
[OAR_Contributor_Template_Antigua.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/8643210/OAR_Contributor_Template_Antigua.xlsx)
