### ISSUE TITLE
Show sectors on the facility detail sidebar

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1840]
## Overview

Show sectors on the facility detail sidebar

Depends on #1839

### Describe the solution you'd like

- Follow the existing pattern where the top-most list of sectors is displayed, others are hidden.
- Show the section section after the Name near the top of the sidebar
- Ensure that the sidebar in embed mode only shows the sector from the embed mode contributor

**Comment by maurizi** [comment]
I noticed we only display unique values for some of the other fields - should we do the same for sector and display the latest values from all contributors when we display all sectors, or should we only show _unique_ values?

e.g. this, with "Apparel, Health" shown twice:
![localhost_6543_facilities_CN2022160Z3RP4J_q=Regina%20Miracle%20Intimate](https://user-images.githubusercontent.com/4432106/172911278-61acb192-11c8-4046-b4e7-637a56f39e55.png)

or like this, with it shown only once:
![localhost_6543_facilities_CN2022160Z3RP4J_q=Regina%20Miracle%20Intimate (1)](https://user-images.githubusercontent.com/4432106/172911365-2168b86b-505c-40fb-a33e-fdc458c2cfc8.png)

**Comment by jwalgran** [comment]
These first screenshot looks correct. The values appear twice, but they are from distinct contributors.

**Comment by jwalgran** [comment]
I added this previously missing requirement to the issue description

- Ensure that the sidebar in embed mode only shows the sector from the embed mode contributor

I left a suggested implementation for this in my PR review comments here https://github.com/open-apparel-registry/open-apparel-registry/pull/1898#pullrequestreview-1003112470
