### ISSUE TITLE
Rename Organization model to Contributor

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#185]
Edited after discussion

## Overview

We currently have an `Organization` model but the UI refers to this entity as a "Contributor." Contributors to the OAR are not always organizations. Rename the `Organization` model to `Contributor`.

~Currently the React client uses `contributor` to refer what we've adapted into the `organization` model, but the API uses `organization`. We should normalize on organization.~

### Describe the solution you'd like

- Rename the `Organization` model to `Contributor`.
- Rename related attributes.
- Rebuild related fixtures
- Update client to use `contributor` rather than `organization` where it isn't already

~Update client-side form field labels, variable names, et cetera to use `organization` rather than `contributor` when necessary. Adjust the API to match.~

**Comment by jwalgran** [comment]
@katieashaw I would like to get your opinion on this. Internally, we have started using "Organization" to refer to a brand, retailer, MSI, etc. The application interface currently uses "Contributor" when referring to these entities. Do you anticipate any our stakeholders having a problem with using the word "Organization?"

**Comment by katieashaw** [comment]
My only slight hesitation is that individuals, in certain circumstances, might upload to the site - e.g. a researcher, student or journalist. @nataliegrillon Do you have a view on this?

**Comment by nataliegrillon** [comment]
agreed @katieashaw - data contributors will be potentially more than just organizations....

**Comment by jwalgran** [comment]
Thanks for the feedback. It sounds like we should reverse this issue and change our code to refer to Contributor internally so we are consistently using the same name.
