### ISSUE TITLE
Create a version of the API documentation Google Doc that includes sector 

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1872]
## Overview

Create a version of the API documentation Google Doc that includes sector

**Comment by obrienad** [comment]
Please also add answers to these questions (and to the extent that makes sense the reasoning behind it).

1. Can you explain to me the use and/or difference between aor_id and new_oar_id I get in the response json?
2. I tried calling the endpoint /api/facility-matches/{id}/ to test out, but was not able to get any results back. I'm not sure what id I should provide to get a response.

**Comment by jwalgran** [comment]
I created [Open Supply Hub API Documentation](https://docs.google.com/document/d/1Ar5hUsgf2D3aIiv5P7DYZALS9JTBts08LIRk_-9xaUE/edit#heading=h.1y2kcnrplc8x) by copying [OAR API Documentation](https://docs.google.com/document/d/1qJBTJCRv-kvmkGtRKpMT_iENa9oBrdaplmwrskLb3ds/edit#heading=h.ihn6qxtdgpkx) and adding sector related details
