### ISSUE TITLE
Update logo and base color

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1879]
Summary: update logo, top banner color, map styling and "search" button on side panel (search button update is a nice to have, not necessary if it changes the point value of ticket) 

Logo: [OS-Hub_Logo_Vector.zip](https://github.com/open-apparel-registry/open-apparel-registry/files/8818325/OS-Hub_Logo_Vector.zip)

<img width="207" alt="Screen Shot 2022-06-01 at 7 56 17 AM" src="https://user-images.githubusercontent.com/97469356/171421950-ac92d1bf-94d6-4025-a71b-2910ec1b2b8a.png">

Color: 
![Screen Shot 2022-06-01 at 11 45 21 AM](https://user-images.githubusercontent.com/97469356/171469277-177fcab6-d3c0-4a46-8f9e-129a342279f0.png)

1. Update logo: on top of background color (logo background is transparent). 
2. Update colors on top banner to: green background
3. Update text on top banner to black.
4. Make map greyscale by using the "silver" map style option already supported by the VectorTileFacilityMap component.
Pending time: Update search bar color to green background and black text.

Logo is on 

Green hex: 62CC74 
Black hex: 0D1128

**Comment by obrienad** [comment]
![image](https://user-images.githubusercontent.com/95237721/171508068-b2bd8b71-dde1-4f00-8728-b73ac62fd6b9.png)

**Comment by obrienad** [comment]
![image](https://user-images.githubusercontent.com/95237721/171508162-d51e30b1-804e-4d5d-890f-da5b86c8e924.png)

**Comment by obrienad** [comment]
@mariel-oar as a head's up: making the color changes _might_ require changes to other colors in the application to change for it to look right. We won’t know until we see it.

**Comment by jwalgran** [comment]
I updated the issue description to be more explicit about the map styling

>4. Make map greyscale by using the "silver" map style option already supported by the VectorTileFacilityMap component.
