### ISSUE TITLE
Dependabot updates black box

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1887]
Sequence the updates based on
- Severity
- Production code vs build piipeline

**Comment by maurizi** [comment]
All of the remaining updates fall into one of two categories:
 - They're a transitive dependency of `react-scripts` that will be fixed when we update to the latest version of that in #1914
 - There are 3 alerts for the package `node-fetch`, which is a transitive dependency of 2 Material-UI libraries and React Infinite
   - The Material-UI libraries in question need a major-version upgrade
   - Unfortunately React Infinite seems to be abandoned, so we can't simply upgrade it
