### ISSUE TITLE
July pull of numbers for two DO NOT OPEN affiliation reports for first half of year

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#1888]
For our first half of year reporting to Laudes, we will need the monthly figures for January - June 2022 for the two reports:

- [Do Not Open Average Affiliations]
- [Do Not Open Percent Facilities With Multiple Matches]

We cannot currently pull those ourselves as they take down the site, but Azavea can manually pull for us. 

It would be great if this could be done between July 1 and July 15. 

@mariel-oar just tagging in case it needs to get worked into current sprint convos - hopefully a very small point issue!

**Comment by mariel-oar** [comment]
Adding to estimation session 6/14

**Comment by jwalgran** [comment]
To run the SQL reports, I ran `psql`

-   Set the separator to `,`

```
\f ','
```

-   Set the output format to unaligned

```
\a
```

-   Set the output to a file

```
\o /tmp/average_affiliations_2022-07-13.csv
```

-   Run the content of `average_affiliations.sql`
-   Set the output to a file

```
\o /tmp/percent_facilities_with_multiple_matches_2022-07-13.csv
```

-   Run the content of `percent_facilities_with_multiple_matche.sql`
-   Reset the alignment and output

```
\a
\o
```

-   `scp` the files and remove the last line (row count) from each

**Comment by mariel-oar** [comment]
@jwalgran, will you be attaching the output of these reports here?
