### ISSUE TITLE
Migrate OAR production database to to OS Hub production

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1894]
Based on rehearsal timings we expect the total process to take less than 1 hour.

### Prep
- [x] Verify the production app CLI resource allocation is 1024 CPU and 8192 RAM https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/taskDefinitions/OpenSupplyHubProductionAppCLI

### pg_dump OAR production database
- [x] Connect to OAR prod bastion
- [x] pg_dump the OAR production database, replacing `{HH}` and `{MM}` with dump time (expected runtime: 1m15s)
```
$ time pg_dump -Fc -h database.service.oar.internal -U openapparelregistry -d openapparelregistry > openapparelregistry-prd-2022-10-14-{HH}-{MM}.dump
```
  - [x] Copy the dump to the s3 data bucket (expected runtime: 5s)
  ```
time aws s3 cp openapparelregistry-prd-2022-10-11--21-24.dump s3://openapparelregistry-development-data-eu-west-1

real	0m4.950s
user	0m3.941s
sys	0m2.514s
```

### pg_resource into the OS Hub production database
  - [x] Update the production cluster to run 0 tasks. https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/ecsOpenSupplyHubProductionCluster/services/OpenSupplyHubProductionApp/details 
  - [x] Connect to OS Hub production bastion
  - [x] Create an empty database
```
$ psql -h opensupplyhub-enc-prd.ctdp4povekhv.eu-west-1.rds.amazonaws.com  -U opensupplyhub -d opensupplyhub
opensupplyhub=> \c postgres
postgres=> drop database opensupplyhub;
DROP DATABASE
postgres=> create database opensupplyhub with owner opensupplyhub;
CREATE DATABASE
```
  - [x] Copy dump file from the s3 data bucket (expected runtime: 5s)
```
$ time aws s3 cp s3://openapparelregistry-development-data-eu-west-1/openapparelregistry-prd-2022-10-11--21-24.dump .
download: s3://openapparelregistry-development-data-eu-west-1/openapparelregistry-prd-2022-10-11--21-24.dump to ./openapparelregistry-prd-2022-10-11--21-24.dump
```
  - [x] `pg_restore` the OAR production dump (expected runtime: 3m50s)
```
time pg_restore --no-owner -h opensupplyhub-enc-prd.ctdp4povekhv.eu-west-1.rds.amazonaws.com  -U opensupplyhub -d opensupplyhub openapparelregistry-prd-2022-10-11-{HH}-{MM}.dump
```

### Update the database for OS Hub
- [x] Run migrations (expected runtime: 1m10s)
```
$ git checkout ogr/develop
$ git pull origin ogr/develop
$ ./scripts/manage ecsmanage -e production migrate

 Created at
2022-10-11 15:06:07 -0700
Started at
2022-10-11 15:06:35 -0700
Stopped at
2022-10-11 15:07:15 -0700
```
- [x] Index all facilities (expected runtime: 15m20s)
```
$ ./scripts/manage ecsmanage -e production index_facilities
```
- [x] Update the production cluster to run 32 tasks. [eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/ecsOpenSupplyHubProductionCluster/services/OpenSupplyHubProductionApp/details](https://eu-west-1.console.aws.amazon.com/ecs/home?region=eu-west-1#/clusters/ecsOpenSupplyHubProductionCluster/services/OpenSupplyHubProductionApp/details)
- [x] Verify that the restored database is not read-only

**Comment by mariel-oar** [comment]
@jwalgran , @obrienad , is this the ticket that captures the UI elements for freezing OAR or is #2160 where that belongs? 

Two things I want to close the loop on with this: 
1) We had discussed putting a banner at the top of the screen that messages the freeze (e.g. "Uploading new data to the OAR is disabled as of October 14 while we prepare to transition this database into Open Supply Hub. Check back on November 2 when OS Hub goes live.”) 

2) Primary CTA: Contribute button should be greyed out 

Nice to have: 
3) Facility pages: CTAs for claim, report as duplicate, report as close, and suggest an edit should be removed/greyed out 
This one is a nice to have because we can manage these through the info inbox as well.

**Comment by TaiWilkin** [comment]
@mariel-oar #2160 is the card for the UI changes. I'll copy your comment over there.
