### ISSUE TITLE
Allow matches to be approved on the facility list detail page / show match results

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#192]
## Overview

When a `FacilityListItem` has the status of `POSSIBLE_MATCH`, show the related `FacilityMatch` rows and allow the user to select one or reject them all. If they are all rejected, create a new `Facility`.

### Describe the solution you'd like

  - On the list detail page, show rows with `POSSIBLE_MATCH` status in an "expanded" state. List the possible match(s) underneath with "Accept" and "Reject" buttons.
     - If "Accept" is clicked, POST to an endpoint. Update state to show other matches as rejected.
     - If "Reject" is clicked on all options, POST to an endpoint and create a new `Facility`.
  - Allow any row that is not in process to be "expanded."
    - If the item is matched, show the `Facility` row to which it is matched.
    - If the item is in the error state, show the error. 

### Additional Context

The previous matching UI

<img width="1132" alt="screen shot 2019-02-07 at 1 54 15 pm" src="https://user-images.githubusercontent.com/17363/52442247-e637c900-2adf-11e9-83de-20c62d56e81e.png">

https://docs.google.com/presentation/d/1vfEb1QnVD-9bvfQyMtYUpXQT3ogJvkQvURI7QoK4z7s/edit#slide=id.g4c5179bf71_0_5

**Comment by kellyi** [comment]
Blocked by #190

**Comment by kellyi** [comment]
API side is mostly done for #206, aside from figuring out how to generate some non-automatic matches using the existing naive matching algorithm.

Frontend's partly done, although I'll need to make some adjustments to the UI:

![screen shot 2019-02-19 at 5 37 02 pm](https://user-images.githubusercontent.com/4165523/53052595-2185b080-346d-11e9-89e9-458b1b8bfbdf.png)

Some remaining stuff on #206:

- [ ] create row components for displaying errors
- [ ] create row components for displaying automatic matches
- [ ] clean up confirm/match UI
- [ ] interleave confirm/reject API response data back into Redux facilityDetails data
