### ISSUE TITLE
DRAFT: Enable API users to subscribe to groups of notifications sent to different URLs

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1940]
# Draft

This is a draft issue, and it will need to clarify specs and formalize what
counts as "done" before work begins on it.

Check with the issue's creator before starting work on this issue.

## Overview

A clear description of the feature request.

### Additional Context

Optional. Add any other context, screenshots, gifs, etc about the feature request here.

**Comment by jwalgran** [comment]
Closing because this feature is Included in #1991
