### ISSUE TITLE
Update colors on OS Hub page

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1942]
**Headline bar and search**
Top bar/headline and search button updated to yellow (Hex code # F C C F 3 F) 

**Map dots** 
Old image
![Screen Shot 2022-06-29 at 10 07 12 AM](https://user-images.githubusercontent.com/97469356/176483769-8e59b38d-576a-4f43-b560-0f0cbcd67daf.png)

Update blue dot colors to the following: 
- Darkest dot: Hex code # 8 4 2 8 FA
- Next darkest dot: Hex code # a868fb
- Next lightest dot: Hex code # cda9fd
- Lightest dot: Hex code # f2e9fe

For reference

<img width="929" alt="Hues " src="https://user-images.githubusercontent.com/95237721/176952142-9e338e3f-5991-428f-a0d5-4d96c95c7a4b.png">

**Comment by hlennett** [comment]
@mariel-oar One thought I just had - to differentiate the OS Hub Beta, do we also want to update the font to Darker Grotesque to match our new brand? 

cc @katieashaw

**Comment by mariel-oar** [comment]
I would rather keep this ticket small since we will be doing an overhaul of the UX later on. I'm not sure if it would be throw away work to change the font now, but that would be my main concern. @jwalgran @obrienad, thoughts on that?

**Comment by mariel-oar** [comment]
ok, UX changes will definitely take font into account so let's hold on that.

**Comment by obrienad** [comment]
Got it.
