### ISSUE TITLE
Integrate OS Hub account signups with HubSpot

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#1944]
## Overview

Replace the existing Mailchimp integration with HubSpot.

##  Notes

OS Hub to provide HubSpot integration details (API Token and the list ID to which people should be subscribed)

## Technical Implementation

- Replace `MAILCHIMP_API_KEY` and `MAILCHIMP_LIST_ID` with `HUBSPOT_API_KEY` and `HUBSPOT_LIST_ID` throughout the app code and Terraform
- Add the appropriate values to `tfvars` for OS Hub staging.
- POST to the subscribe endpoint when users register and opt in  (developers.hubspot.com/docs/api/marketing-api/subscriptions-preferences)

**Comment by mariel-oar** [comment]
Details on subscribe contact endpoint at: 
https://developers.hubspot.com/docs/api/marketing-api/subscriptions-preferences

**Comment by mariel-oar** [comment]
cc: @hlennett for hubspot linking

**Comment by mariel-oar** [comment]
Azavea needs to know the name / code of the list that they need to subscribe people to
as well as the API token that they need to use

**Comment by hlennett** [comment]
The list is titled Open Supply Hub Subscribers: https://app.hubspot.com/contacts/19901037/lists/8

For the API key, it looks like HubSpot is changing their method. I don't know enough to know how to set up a Private App. Is this something we could do together/on a call with someone from Azavea? 

<img width="1143" alt="Screen Shot 2022-09-14 at 4 09 58 PM" src="https://user-images.githubusercontent.com/80268596/190252435-9ce9638c-6129-4a97-bee1-003fdf140ae4.png">

**Comment by hlennett** [comment]
<img width="362" alt="Screen Shot 2022-09-14 at 4 10 59 PM" src="https://user-images.githubusercontent.com/80268596/190252616-a0e0651f-0315-4fe6-b0f3-40dd4ec631b8.png">

**Comment by hlennett** [comment]
Contacts who opt in will need to be set as marketing contacts and be added to the "Open Supply Hub News and Updates" subscription type.
