### ISSUE TITLE
Update the AMI used when launching EC2 instaces to run Batch jobs 

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1947]
## Overview

**NOTE** This change should be applied to both `develop` and `ogr/develop`

AWS is deprecating the AMI we for launching Batch job instances on July 30 2022. We need to update to a newer AMI.

Detail from @nanotubing 

The AMI we use for the compute environments in AWS batch for OAR is being deprecated on July 30th. It sounds like there probably won’t be any immediate impact (unless we happen to be doing a DescribeImages call somewhere, but it’s good to know that this AMI is on it’s way out.

Terraform variable assigning that AMI:
https://github.com/open-apparel-registry/open-apparel-registry/blob/b98abc5bf2672fb5a73a7c67e935a3dd282f98da/deployment/terraform/variables.tf#L239

Quote:
>While you will continue to be able to launch instances using the
AMI IDs, the AMIs will not be visible on the public AMI catalog [3] or
in DescribeImages calls by default once deprecated. To list deprecated
AMIs in the DescribeImages API calls, you must specify the
--include-deprecated parameter [4].

### Describe the solution you'd like

- Find the ID of the latest version of the Amazon ECS-optimized AMI on eu-west-1,, referecing https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html
- Update variables.tf and, push a `test/` branch to deploy to staging, and submit lists to verify that the parse batch jobs runs without error

### Additional Context

Full notice from AWS:

Hello,

On March 31, 2022, EC2 announced that all public AMIs will have the
deprecation time set to two years after their creation date [1]. Once
an AMI is deprecated, it will no longer appear in DescribeImages [2]
API calls for users that are not the owner of the AMI. Deprecating an
AMI only reduces the visibility of the AMI in untargeted searches, but
continues to be usable and available to you. Users of a deprecated AMI
can continue to launch instances and describe the deprecated AMI using
its ID. Deprecation time for all public AMIs will now be set
automatically to two years after their creation. Public AMIs already
older than two years will be deprecated on July 30, 2022 instead of
the originally stated date of June 30 to give you time to assess and
mitigate potential impact to your workflows which may perform
DescribeImages requests that do not specify image IDs.

We have identified that you have launched one or more instances in the
last month using a public AMI which will be deprecated on July 30,
2022. While you will continue to be able to launch instances using the
AMI IDs, the AMIs will not be visible on the public AMI catalog [3] or
in DescribeImages calls by default once deprecated. To list deprecated
AMIs in the DescribeImages API calls, you must specify the
--include-deprecated parameter [4]. If you would like to view details
about the deprecated AMI, you can describe it using its ID as well.
This message is to notify you of the upcoming change, and does not
require any action from you.

The following is a list of old public AMIs you have used for instance
launches in the last month in the EU-WEST-1 Region :
ami-00921cd1ce43d567a

To learn more about viewing and managing the deprecation time for your
AMIs, please refer to the "Deprecate an AMI" documentation [5].

If you have any further questions or comments regarding this matter,
please contact AWS Support [6].

[1] https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-machine-images-public-visibility-two-years/
[2] https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html
[3] https://aws.amazon.com/blogs/aws/new-ami-catalog-and-new-ami-launch-button-are-now-available/
[4] https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html
[5] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ami-deprecate.html
[6] https://aws.amazon.com/support

Sincerely,
Amazon Web Services

**Comment by jwalgran** [comment]
I ran the command to get details of the latest amazon-linux-2 AMI

bash-5.1# aws ssm get-parameters --names /aws/service/ecs/optimized-ami/amazon-linux-2/recommended
PARAMETERS	arn:aws:ssm:eu-west-1::parameter/aws/service/ecs/optimized-ami/amazon-linux-2/recommended	text	1661984300.21	/aws/service/ecs/optimized-ami/amazon-linux-2/recommended	String	{"ecs_agent_version":"1.62.2","ecs_runtime_version":"Docker version 20.10.13","image_id":"ami-0e592a261c043bc6a","image_name":"amzn2-ami-ecs-hvm-2.0.20220831-x86_64-ebs","image_version":"2.0.20220831","os":"Amazon Linux 2","schema_version":1,"source_image_name":"amzn2-ami-minimal-hvm-2.0.20220805.0-x86_64-ebs"}	93

**Comment by maurizi** [comment]
I updated the `terraform.tfvars` file for each of the 4 environments (OS Hub staging/production & OAR staging/production)
