### ISSUE TITLE
Discrepancy with total # facilities on the OS Hub staging site 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1949]
On OS Hub staging there are ~85,000 in total, but when you filter to only apparel sector value it drops to 75752.

Justin response / context: Searching comes from an index of the sector information. This may need to investigate the root cause to update the indexing of that particular item 

cc: @obrienad @jwalgran 

---

The 1-point estimate is to research if reindexing will resolve the issue. If there is a larger underlying problem create a followup issue with a separate estimate.

**Comment by jwalgran** [comment]
#1966 has been deployed and I ran the new `index_sectors` management command. These numbers are much closer now

No filter: 89149
Selecting all available sectors: 89092

I expect the additional change as part of #1964 to address the remainder

**Comment by jwalgran** [comment]
The discrepancy in the number does match the count of facilities that do not have any sector in the index.

```

opensupplyhub=> select count(*) from   api_facilityindex  where sector = '{}' and id in (select id from api_facility);
 count
-------
    57
(1 row)
```
