### ISSUE TITLE
Facility search resulting in "whoops" error page 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1959]
This is a claimed facility that is in the OAR. Uploaded in March 2022. 

When I try searching this facility: /facilities/VN202108625A1KW?q=VN202108625A1KW. I get a Whoops something went wrong error. I was trying to see if claimed facility data was displaying and this is a claimed facility in the OAR. It happens when I try to search it by name, too: /facilities/VN202108625A1KW?q=protrade

Based on the contribution date, it looks liek this facility should have been migrated from OAR. Is there a reason it is erroring in OS Hub? It works in OAR. 

### Proposed Fix

- In `serializers.py` exclude sectors with a null value

**Comment by jwalgran** [comment]
In an example from staging (US2022117EBHAQ2) there is a null value from sectors added to a claim

<img width="544" alt="Screen Shot 2022-07-07 at 1 40 05 PM" src="https://user-images.githubusercontent.com/17363/177867501-45b9a6bf-2044-41af-9fb5-6f06e1c29bfa.png">

A null `values` causes an exception here

<img width="628" alt="Screen Shot 2022-07-07 at 1 43 48 PM" src="https://user-images.githubusercontent.com/17363/177867986-b1fdd9dd-94af-4fb8-bf67-cd00b6737a1e.png">

**Comment by jwalgran** [comment]
A fix for this is deployed to OS Hub staging
