### ISSUE TITLE
Attempting to delete a facility from the OS Hub staging dashboard fails

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1961]
https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/1662/

ProtectedError: ("Cannot delete some instances of model 'Facility' because they are referenced through a protected foreign key: 'FacilityMatch.facility'", <QuerySet [<FacilityMatch: FacilityListItem 742838 - MATCHED - Some Other Place (US20221887KCCAV) -

Connected to #1992

**Comment by obrienad** [comment]
Blocked as we need OS Hub's approval to work on a bug.

**Comment by jwalgran** [comment]
Closing as a duplicate of #1992
