### ISSUE TITLE
Issue with Yeti List polluting sector data 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1964]
[This list](https://5e7e9bbe1de56315bc37e39f.openapparel.org/lists/1690) was uploaded and had a bunch of line errors (there were line breaks in the address fields). Most of the list failed to upload; however it appears that pieces of the address field got pulled into the sector field. 

You can see some of these values below:
<img width="352" alt="Screen Shot 2022-07-07 at 10 59 03 PM" src="https://user-images.githubusercontent.com/97469356/177914258-c43dd7c1-dfda-4378-86cc-8525bf5c7114.png">

The list was replaced with a corrected version of the list, [here](https://5e7e9bbe1de56315bc37e39f.openapparel.org/lists/1695). 

How can we remove the bad values from the sector field? (these were somehow pulled in from another column it appears) ? 

- The originally uploaded list is here: https://drive.google.com/file/d/1UmJf360ipbSTw-bNGul5gCKvX8QTuQXp/view?usp=sharing
- The corrected list is here: https://docs.google.com/spreadsheets/d/1cqjiVu3VYA-O85xQcZ7CXzCA-s4APuyZqCr14XJsVo4/edit?usp=sharing

### Proposed Fix

Filter the values returned from /api/sectors to only include list items in the `MATCHED` or `CONFIRMED_MATCH` status

List items in the that have not finished processing, are in an error state, or are in the deleted state should be excluded when generating the list of possible sector filter values.

**Comment by maurizi** [comment]
@jwalgran should we include `AUTOMATIC` status as well, like we do in `index_facilities`?

**Comment by jwalgran** [comment]
I do not see a PR connected to this issue so I moved it back to In Progress

**Comment by jwalgran** [comment]
As I was working on #1966 the other issues it occurred to me that the purpose of /api/sectors is to return values that are searchable and, after fixing up the the sector indexing process in #1966 we could potentially simplify the query behind this endpoint to

```sql
SELECT DISTINCT unnest(sector) AS sector
FROM api_facilityindex
ORDER BY sector;
```
