### ISSUE TITLE
Load test and record facility search and tiling performance after loading test data to staging at 5x current data volume

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1976]
## Overview

NOTE this testing needs to be coordinated with OS Hub since it will create strange data temporarily and likely performance degradation and downtime.

- [x] `pg_dump` existing staging (reference tools/copy_production_database_to_stagingl)
- [x]  Use the SQL generated from tool built in #2108 to load 5x test data into staging
- [ ]  Run the `index_facilities` management command
- [ ]  Run search and tile load tests at 5x (reference load-tests/README)
- [ ]  Document failures for follow up issues
- [x]  pg_dump the 5x data set and store in the development data S3 bucket
- [ ]  `pg_restore` the original staging dump.

**Comment by jwalgran** [comment]
Not seeing the inflated total when I run an unfiltered search 

<img width="217" alt="Screen Shot 2022-10-10 at 8 02 13 AM" src="https://user-images.githubusercontent.com/17363/194896814-0a78a700-ebb2-4179-bdf2-63bfb1f4ec52.png">

Using `shell_plus` in development we can get the query used

```
>>> from django.http import QueryDict
>>> Facility.objects.filter_by_query_params(QueryDict())
>>> str(Facility.objects.filter_by_query_params(QueryDict()).query)
```

```
SELECT "api_facility"."ppe_product_types",
       "api_facility"."ppe_contact_email",
       "api_facility"."ppe_contact_phone",
       "api_facility"."ppe_website",
       "api_facility"."id",
       "api_facility"."name",
       "api_facility"."address",
       "api_facility"."country_code",
       "api_facility"."location" :: bytea,
       "api_facility"."created_from_id",
       "api_facility"."is_closed",
       "api_facility"."new_os_id",
       "api_facility"."has_inexact_coordinates",
       "api_facility"."created_at",
       "api_facility"."updated_at"
FROM   "api_facility"
WHERE  "api_facility"."id" IN (SELECT U0."id"
                               FROM   "api_facilityindex" U0) 
```

The where clause appears to be the key. It "joins" `api_facilityindex` with an `IN` query. 

Running the `index_facilities` management command fix things.

**NOTEI** expect this command to take quire a while at this volume.  We may need to increase the RAM available to AppCLI tasks.

**Comment by nanotubing** [comment]
Results from this testing are documented in this google document

https://docs.google.com/document/d/1i8s6WCURE1Dq9cTZz8T5PfVqIrN19aWUZ0iZSVow0QU/edit?usp=sharing
