### ISSUE TITLE
Not all sector values populating in drop down 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#1990]
This list has a sector value of "Food and Beverage" but that value is not populating in the sector filter. 

/facilities/US202220627V2HD

![Screen Shot 2022-07-25 at 4 00 05 PM](https://user-images.githubusercontent.com/97469356/180853824-017ec34c-5929-482d-a33f-5658779240e9.png)

The only values cut off in this screen shot are Accessories and Apparel: 
![Screen Shot 2022-07-25 at 4 01 12 PM](https://user-images.githubusercontent.com/97469356/180853995-88b9ca97-c97e-45e6-a65f-88713cb02766.png)

**Comment by jwalgran** [comment]
Consistent with the bug report the sector does not appear in the index.

```
opensupplyhub=> select distinct sector from api_facilityindex;
                  sector
-------------------------------------------
 {Apparel,"Outdoor Equipment"}
 {Apparel,"Consumer Products"}
 {Apparel}
 {Technology,Apparel}
 {}
 {"Outdoor Equipment",Apparel}
 {"Outdoor Equipment"}
 {Electronics/Technology}
 {Electronics,Apparel,Automotive}
 {Technology,Electronics}
 {Apparel,Accessories}
 {"Consumer Products"}
 {"Consumer Products",Apparel}
 {Apparel,"Outdoor Equipment",Accessories}
 {Apparel,"Sporting Goods"}
 {Electronics}
(16 rows)
```

That facility is currently does not have any sector in the index

```
opensupplyhub=> select sector from api_facilityindex where id = 'US202220627V2HD';
 sector
--------
 {}
(1 row)
```

But the sector is set correctly in the list item

```
opensupplyhub=> select sector from api_facilitylistitem where name = 'America''s Beverage';
         sector
------------------------
 {"Food And Beverages"}
```

**Comment by obrienad** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/1990?planning-poker) with ZenHub @jwalgran @TaiWilkin @maurizi @nanotubing
