### ISSUE TITLE
Allow deletion of facilities with multiple created_from matches

### ISSUE THREAD

**Issue by TaiWilkin** [open-apparel-registry/open-apparel-registry#1992]
## Overview

When the facility.created_from list item has multiple matches associated with it, we’re only deleting the first match, and the other matches block the facility from being deleted. 

### Expected Behavior

Facilities can be deleted regardless of the number of matches. 

### Actual Behavior

The facility cannot be deleted. The following error is thrown: https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/1674/

### Steps to Reproduce

* For any facility in local development, create a second FacilityMatch linked to the FacilityListItem which the facility was created from (`Facility.created_from`). 
* Attempt to delete the facility. The facility will fail to delete and an error will be thrown. 

### Demo

After updating the test FacilityDeleteTest as below, the following error was thrown

Updated test:
```diff
diff --git a/src/django/api/tests.py b/src/django/api/tests.py
index fce6560..4e33bff 100644
--- a/src/django/api/tests.py
+++ b/src/django/api/tests.py
@@ -3157,6 +3157,14 @@ class FacilityDeleteTest(APITestCase):
                     confidence=0.85,
                     results='')
 
+        match_4 = FacilityMatch \
+            .objects \
+            .create(status=FacilityMatch.PENDING,
+                    facility=self.facility,
+                    facility_list_item=self.facility.created_from,
+                    confidence=0.85,
+                    results='')
+
         alias = FacilityAlias.objects.create(
             facility=self.facility,
             oar_id='US1234567ABCDEF')
```

Error:
```
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Facility' because they are referenced through a protected foreign key: 'FacilityMatch.facility'", <QuerySet [<FacilityMatch: FacilityListItem 9 - CONFIRMED_MATCH - Name (US2022207YPT3FQ) - PENDING>]>)
```

**Comment by jwalgran** [comment]
@mariel-oar approved us to work on this fix at our Aug 2 check in
