### ISSUE TITLE
Support Front-end Environment Variables

### ISSUE THREAD

**Issue by rajadain** [open-apparel-registry/open-apparel-registry#203]
## Overview

In different environments, such as development, test, staging, and production, the app may need to behave differently or connect to different third party services (e.g. Rollbar, Mapbox, etc.). Currently there is no way to achieve this, since the environment variables are baked in to a Docker image at compile-time, not run-time. This organization requires compiling different images for different environments, since the environment variables can only be injected at compile-time. This limits are confidence in the parity of staging and production (and other environments), leading to potential bugs not being caught until a later environment is launched.

### Describe the solution you'd like

A code organization that would read variables from the environment and use them to populate values in the front-end. This should behave the same way in _all_ environments: development, test, staging, and production.

At least one of the environment variables should be the name of the environment, so it can be used by the app to potentially flag certain behaviors.

The way environment variables are specified should ensure that there is a value for that variable in every environment. We shouldn't discover after a deploy that a particular environment doesn't have a variable set.

**Comment by kellyi** [comment]
Not sure whether "code organization" implies changing the dir structure and project setup of the app container, but it appears that this is one way Create React App recommends for injecting server side variables: https://facebook.github.io/create-react-app/docs/title-and-meta-tags#injecting-data-from-the-server-into-the-page in a way that might minimize the number of changes to the client setup.

**Comment by rajadain** [comment]
That looks really promising! I'd like to do this with a small footprint. Trying that out now.

**Comment by rajadain** [comment]
Okay, I don't think the link above is enough, because we still need server infrastructure in place to replace the `__SERVER_DATA__` placeholder. That would require adding middleware / views to Django.

However, once we've done that, we'd need to switch to using the Django rendered endpoint in development (rather than hitting webpack-dev-server directly), so we have access to those environment variables.

This is accomplished by using [`django-webpack-loader`](https://github.com/owais/django-webpack-loader) and [`webpack-bundle-tracker`](https://github.com/owais/webpack-bundle-tracker), as done in https://github.com/project-icp/bee-pollinator-app/pull/289/commits/ee6791b21f7803c01159cef65126dc86704d7233 and https://github.com/project-icp/bee-pollinator-app/pull/289/commits/d89c46b30b6042d074130ca79758e332a8f511cc.

Unfortunately, this requires changing the Webpack config, which may require ejecting it. There [is an alternative](https://blog.rousek.name/2018/10/13/using-create-react-app-with-django/) which uses (the now outdated) [`react-app-rewired`](https://github.com/timarney/react-app-rewired) which [effectively breaks CRA guarantees](https://twitter.com/dan_abramov/status/1045809734069170176). There are [some modern alternatives](https://github.com/timarney/react-app-rewired#alternatives) we could look in to, but they would have a similar consequence as far as CRA confidence is concerned.

Which would be more preferable at this stage in the project: ejecting Webpack, or using one of the Custom CRA projects?

/cc @jwalgran

**Comment by kellyi** [comment]
> we'd need to switch to using the Django rendered endpoint in development (rather than hitting webpack-dev-server directly), so we have access to those environment variables.

Could we keep the existing set up for development, including its way of setting environment variables and just do this for staging/production? 

This would obviously not make development identical to staging/production but aside from bees we don't typically make client development identical to staging anyway, since we use webpack dev server there.
