### ISSUE TITLE
Enable downloading facility list items CSV file from `lists/:id` page

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#204]
## Overview

Users were previously able to download a CSV of facility list items from the `lists` page for each list. We should restore a version of that feature. (Note that this was not the same as re-downloading the already uploaded list).

### Describe the solution you'd like

Use the existing `DownloadCSV` utility method to enable users to download a CSV of the facility list items for a parsed list on `/lists/:id`

Create utility functions as necessary to do the actual parsing of the facility list items into rows for the CSV, and create tests for each utility function.

### Additional Context

This was the previous implementation in `Lists.jsx`:

```
    factoriesCSV = (data) => {
        const cleanedData = [];
        data.forEach((temp) => {
            const { country, name, address } = temp.data;
            if (
                temp.matched &&
                temp.matched.length &&
                temp.matched.length > 0
            ) {
                temp.matched.forEach((m) => {
                    const matchedName = m.name;
                    const matchedAddress = m.address;
                    const factoryObj = {
                        _id: temp._id,
                        country,
                        name,
                        address,
                        matchedName,
                        matchedAddress,
                        confirm: m.confirm,
                        matchedId: m.nameId._id,
                    };
                    cleanedData.push(factoryObj);
                });
            } else {
                const factoryObj = {
                    _id: temp._id,
                    country,
                    name,
                    address,
                    matchedName: 'No Match',
                    matchedAddress: 'No Match',
                    confirm: 'No Match',
                    matchedId: 'No Match',
                };
                cleanedData.push(factoryObj);
            }
        });
        return parse(cleanedData, {
            fields: [
                '_id',
                'country',
                'name',
                'address',
                'matchedName',
                'matchedAddress',
                'confirm',
                'matchedId',
            ],
        });
    };
```

We've replaced, removed, or adjusted some of these fields in the transition to using Django, so use a reasonable set of fields from the current facility list items data returned from the API.

**Comment by kellyi** [comment]
See https://github.com/open-apparel-registry/open-apparel-registry/issues/133 which has a request for a specific format for the CSV file.

**Comment by kellyi** [comment]
See also #123

**Comment by kellyi** [comment]
Hi @katieashaw and @nataliegrillon! I'm about to start work on enabling users to download CSVs of their parsed lists and I have some questions to help clarify how the functionality should work:

![screen shot 2019-02-22 at 2 14 06 pm](https://user-images.githubusercontent.com/4165523/53265414-2dab8100-36ac-11e9-94b5-ffa7d189ef14.png)

First question: when downloading a list of facility list items like those in the table depicted above, should the CSV include 1 row per list item parsed from the original upload data OR 1 row per facility match?

(The legacy code appears to create 1 row per facility match, but I wanted to check that that is the correct and intended functionality).

Second question: should the downloaded CSV list of facility list items

**Comment by katieashaw** [comment]
I'll let @nataliegrillon confirm my responses on this, but my inclination on your two questions is:

1) 1 row per facility match

2) A combination of confirmed matches AND new entries - but NOT rejected matches

The logic I'm working under to get to those answers is around the use case for downloading the data: users want to understand which facilities have been returned as matches in the OAR to their lists, and also to strengthen the quality of their address data - which is why rejected matches isn't so useful for them. They need the new entries in order to access the OAR ID number.

Do you agree with that @nataliegrillon ?

**Comment by katieashaw** [comment]
Hi again,

I wanted to confirm that @nataliegrillon & I have spoken and that she's in agreement with my answers on this.

One additional point on the rejected data: perhaps there could be the option further down the line that people could download rejected matches - i.e. that could be an additional feature for further filters that users could search by (potentially a paid for service?).

**Comment by kellyi** [comment]
Hi @katieashaw,

Great! Thanks for clarifying and confirming how the CSV downloads should work! I'll relay the point about the rejected data to @dboyer so we could account for it in future planning.

Thanks again!

**Comment by kellyi** [comment]
I made https://github.com/open-apparel-registry/open-apparel-registry/issues/234 to keep track of downloading rejected matches.

**Comment by jwalgran** [comment]
The current CSV does not include `lat` and `lng` columns.  #123 calls these out as desired fields. I think we should include them.
