### ISSUE TITLE
Add DUPLICATE status count to the list list page and as a filter option on the list detail page

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2041]
**NOTE** The duplicate count was added to the serializer in #2044. If that PR has not yet been merged, start your work from the associated branch.

Duplicate filtering was added in #2032

The PR for this feature should be connected to #2021 as it is continued work

<img width="1020" alt="Screen Shot 2022-08-12 at 10 17 46 AM" src="https://user-images.githubusercontent.com/17363/184412712-3376909a-cb72-4115-8038-1746f73c5497.png">

<img width="1220" alt="Screen Shot 2022-08-12 at 10 19 29 AM" src="https://user-images.githubusercontent.com/17363/184412725-489b4aea-aebc-475c-a2ae-be9dbebd8a89.png">
 on the same feature

**Comment by mariel-oar** [comment]
@jwalgran, @obrienad, the list status page is still not displaying this duplicate column - is this expected at this point? 
![Screen Shot 2022-09-22 at 11.30.11 AM.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/fdbcf47e-b9f4-4a46-9973-a2c4aa5a8f28
)

**Comment by mariel-oar** [comment]
OK, thanks, they weren't showing up on Friday (when the above screen shot is from) but I see the updated columns now.
