### ISSUE TITLE
Contributor Workflow UX Updates

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2050]
## Overview

This ticket captures requirements for UX changes to the data contribution experience.

### Included Changes

Must-have: 
1. ~Updated copy, font, logo, color and stylistic changes~ (via #2059 )
2. My Lists pages - columns updated to: Uploaded, Duplicates, Errors and Status; Status values: processing, pending approval, action required (if contributor is doing confirm reject) OR pending moderation (if OS Hub team is doing it), approved, rejected.

### Visual Design 
Screen design - WIP

**Comment by moradology** [comment]
Here's the current list: ![image.png](https://images.zenhubusercontent.com/5ceec31a30146b3110ab4f8e/37bd24ad-a604-406b-89ef-41fa5506c0ca)

If I'm understanding this task correctly, we should end up with these columns: name, description, file name, uploaded, duplicates, errors, and status

**Comment by moradology** [comment]
The UI is basically done, but I'm struggling on how the statuses ought to be changed for list items and wondering if this issue is meant to include a migration to get this list of statuses to correspond to the new ones listed above. Here's the current, relevant (I think) bit on the backend: https://github.com/open-apparel-registry/open-apparel-registry/blob/ogr/develop/src/django/api/models.py#L618-L635

**Comment by jwalgran** [comment]
I ton't think wee need a migration or a change to the backend. My impressions what that we just needed to sum the more granular statuses together.

**Comment by jwalgran** [comment]
Sum them together on the frontend, that is

**Comment by moradology** [comment]
The sums make sense but there do appear to be new statuses (which seems like a categorical field?) to advertise: "Status values: processing, pending approval, action required (if contributor is doing confirm reject) OR pending moderation (if OS Hub team is doing it), approved, rejected." Not 100% sure how to decide which of these new statuses to choose given the information currently available on the list object

**Comment by jwalgran** [comment]
You are right. I got contused thinking about the count columns, not the status column.

I think we have the information we need

- Pending approval: the list status == PENDING
- Rejected: the list status == REJECTED
- Processing: If the list status is APPROVED and any of the UPLOADED, PARSED, or GEOCODED counts are  > 0 
- Action Required: If not processing and match_resposibility == contributor
- Pending Moderation: If not processing and match_resposibility == moderator
- Approved: if list status is APPROVED and there are no items in UPLOADED, PARSED, GEOCODED, or POTENTIAL_MATCH
