### ISSUE TITLE
OS Hub: Parsing Issue for countries that should be recognized 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2053]
## Overview
List items uploaded in the lists below resulted in a parsing error and the error code given referenced the country code being the issue; however, all of the countries mentioned as an issue seem to be valid country values. 

### Expected Behavior
United Kingdom, Dominican Republic, Russian Federation and Hong Kong SAR should all have a country code match. 

### Actual Behavior
The lists below each returned a parsing error related to the country value. In the the case of Hong Kong SAR and United Kingdom, there were other instances of these country values uploaded in the same list that did not cause errors; in the case of the DR, that is the only DR facility on the list. 

Lists with parsing error due to country: 
United Kingdom - https://076e8b512ec74bb6832725db.openapparel.org/lists/1727
Hong Kong SAR - https://076e8b512ec74bb6832725db.openapparel.org/lists/1725
Dominican Republic - https://076e8b512ec74bb6832725db.openapparel.org/lists/1723
Russian Federation - https://076e8b512ec74bb6832725db.openapparel.org/lists/1724

All of these terms return a match in the ISO online country lookup: https://www.iso.org/obp/ui/#search

**Comment by mariel-oar** [comment]
@obrienad @jwalgran , we are worried that this could turn into a bigger issue at launch. Can you spend a point investigating this one next sprint? 

cc: @vrwOAR @KlausGPaul

**Comment by KlausGPaul** [comment]
While this may not fully address the issue described, the attached `country.py` would be a code change for a much broader and more forgiving country name mapping. It's sources include
* [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Officially_assigned_code_elements)
* [again Wikipedia](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes#Current_ISO_3166_country_codes)
* [IBAN](https://www.iban.com/country-codes)
* [Data from Naturalearth map files](https://www.naturalearthdata.com/)
* [UN World Population Data](https://population.un.org/wpp/Download/Standard/MostUsed/)
* [Names used in Johns Hopkins COVID-19 data](https://github.com/CSSEGISandData/COVID-19)
* [Names used in Oxford University COVID-19 policy tracker](https://github.com/OxCGRT/covid-policy-tracker)
* [Data from `pycountry`](https://pypi.org/project/pycountry/)

[countries.py.md](https://github.com/open-apparel-registry/open-apparel-registry/files/9645554/countries.py.md)

**Comment by TaiWilkin** [comment]
Except for "Hong Kong SAR", each of these items had a newline character in the middle of the country.
[Example](https://9f692df0338dcbc9848646c6.openapparel.org/admin/api/facilitylistitem/761317/change/) 
> "Could not find a country code for \"United\nKingdom\"."

Hong Kong SAR is the one case where it's not in our list. 

Recommended actions: 
- handle newline characters in country field
- update country codes list

**Comment by mariel-oar** [comment]
thanks for the info @TaiWilkin, cc: @KlausGPaul

**Comment by mstone121** [comment]
@KlausGPaul FYI: I added 'hong kong sar' to countries.py along with your amended list in https://github.com/open-apparel-registry/open-apparel-registry/pull/2195.
