### ISSUE TITLE
Updated Header for OS Hub 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2068]
# Overview 

This ticket captures requirements for the navigation menu in the header and footer of the OS Hub site. 

### Header Changes 
Must-have: 
1. A top level navigation bar with buttons that either link to a submenu pop-out or directly to a page; examples of buttons with submenus include 'About us' and 'How it works'; the only button without a submenu is 'Resources' and 'International,' which is represented by a globe icon. 
2. The buttons with submenus contain a number of links below a menu title (e.g. Title: "Who's it for?", submenu items: Brands, Civil Society, etc.) 
3. The styling (font, color, logo) of the header shall be consistent with the Figma designs from Nonlocal

### Additional Context 

Header Menu Designs: 
https://codepen.io/niceandserious/full/MWGbvro/800eca8ba2f56cfe4c4e30d0c42be941

Note that when you want to review how it will look on mobile, just narrow your browser till it stacks to the mobile design.The desktop and mobile nav have separate html and you can toggle between them with the css.

Note that the globe icon in the top menu is not a language selector - this links to a page on the info site with content from the in-country community managers. 

<img width="760" alt="Screen Shot 2022-09-15 at 5 15 53 PM" src="https://user-images.githubusercontent.com/97469356/190510188-8e9970a0-ee7e-42ed-a482-cc3530aeadb6.png">

Sub-menu: 
The screen shot below is of the How it Works sub-menu; note that the carrot is pointed upwards when the submenu is displayed. You can see the submenus for About Us and the International page (globe) [here](https://codepen.io/niceandserious/full/MWGbvro/800eca8ba2f56cfe4c4e30d0c42be941). Also note that Resources and Explore do not have sub-menus. Explore links to the map site. 

<img width="1394" alt="Screen Shot 2022-09-15 at 5 17 39 PM" src="https://user-images.githubusercontent.com/97469356/190510456-a4799772-8f92-4803-8faa-fe8168fb9df9.png">

A mockup from @mariel-oar of how to style the user menu based on the styling of the other menus

![Screen Shot 2022-09-20 at 11 07 16 AM](https://user-images.githubusercontent.com/97469356/191321146-db659264-1c50-44d5-8be4-7124bc9c00a4.png)

**Comment by mariel-oar** [comment]
The expanded footer needs to be split into it's own ticket - this changes the design of the app in a fairly significant way because it's currently design to persist the skinny footer on all pages, regardless of content. This would change with Nonlocal's design to only have the footer appear when all of the content has been scrolled through.

**Comment by obrienad** [comment]
CAN tagged because pending nice and serious

**Comment by obrienad** [comment]
estimate added for work load estimates with OAR; not verified by engineers

**Comment by mariel-oar** [comment]
Updated header designs are here: 
https://codepen.io/niceandserious/full/MWGbvro/800eca8ba2f56cfe4c4e30d0c42be941

Note that when you want to review how it will look on mobile, just narrow your browser till it stacks to the mobile design.
The desktop and mobile nav have separate html and you can toggle between them with the css.

**Comment by mariel-oar** [comment]
I think CAN can be removed from this one, @obrienad ?

**Comment by jwalgran** [comment]
My only remaining question is whether we need to make changes to the "User" menu, which is not included in the Codepen example

Here is how it currently appears

<img width="1276" alt="Screen Shot 2022-09-20 at 9 48 56 AM" src="https://user-images.githubusercontent.com/17363/191317525-a1fac735-6007-42a5-b6d8-58779bbd5f55.png">

**Comment by mariel-oar** [comment]
The items on that menu doesn't need to change, but does it fit within the current point estimate to update the look to match the other drop downs? Like this:

![Screen Shot 2022-09-20 at 11 07 16 AM](https://user-images.githubusercontent.com/97469356/191321146-db659264-1c50-44d5-8be4-7124bc9c00a4.png)

**Comment by jwalgran** [comment]
Yes, we can implement the styling you have mocked up because we had incorporated into the estimate the assumption that we would be restyling the user options

**Comment by obrienad** [comment]
@mariel-oar - the N&S designs do not include Google Translate. How would you like to proceed? Some quick ideas below:

- stick it into the new header somewhere as-is
- remove it for now
- add it into a new row above the header with a black background and white font (so a first step towards the Figma design, but it would still just be the language abbreviation with a dropdown arrow)

<img width="1422" alt="Screen Shot 2022-09-26 at 1 42 41 PM" src="https://user-images.githubusercontent.com/95237721/192349469-5aafa8ff-99af-4369-a3a7-78edc6f27542.png">

<img width="723" alt="Screen Shot 2022-09-26 at 1 35 21 PM" src="https://user-images.githubusercontent.com/95237721/192349487-3e4a5ce6-3408-49aa-ad55-15a300cd9df6.png">

**Comment by mariel-oar** [comment]
The google translate feature is mocked up in the requirements section above (the EN with down arrow); it's consistent with what you describe as option 3 above). Are their questions about that approach?

**Comment by obrienad** [comment]
I see that in the screen shots you added, but they are missing from the linked designs. Flagged the screenshots.

**Comment by mariel-oar** [comment]
OK, thank you.

**Comment by mariel-oar** [comment]
@mstone121 @jwalgran , seeing one issue with the header - the submenu for My Account has the words surrounded by a slightly different shade of purple than the rest of the background. This must have come from a mockup that i did to be quick...the intention was that all the background be the same shade of purple. Possible to fix this? want a new ticket? cc: @obrienad

**Comment by mstone121** [comment]
@mariel-oar Is this what you mean?

<img width="1447" alt="Screen Shot 2022-09-29 at 5 42 17 PM" src="https://user-images.githubusercontent.com/8356789/193147705-36d78b3f-6e92-42a1-b912-5cdc7c01cb13.png">

"My Facilities" is showing the hover style.

**Comment by mariel-oar** [comment]
Yes @mstone121 , exactly.
