### ISSUE TITLE
Expanded Footer 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2079]
# Overview
This ticket captures requirements for the updated OS Hub footer, which appears at the end of the page scroll and has additional links and branding elements compared to the OAR footer.

## Included Changes
Must-have:

1. Footer appears at the end of the page when a user scrolls past all of the page content 
2. Footer contains links and branding elements represented in Figma design boards 

### CodePen 
Footer Menu Designs:
https://codepen.io/niceandserious/pen/dyeOdmY/1a08d126f3479db9d98d55fda4539a74

### Links
Links used on the footer can be found when hovering over the footer design or when viewing the HTML code panel on Codepen. 

NOTE: The **_ONLY link that needs to be changed to something other than what is in codepen_** is the link for the donate page, which should be: http://opensupplyhub.org/donate

### Visual Design 
<img width="1436" alt="Screen Shot 2022-09-27 at 9 51 20 PM" src="https://user-images.githubusercontent.com/97469356/192669314-9c31f14a-e1a8-4bbe-8404-dc044d7f147c.png">

### CodePen walk-thru: 

https://user-images.githubusercontent.com/97469356/192860325-0fb8c040-3c7e-4c47-b242-830911e26426.mov

**Comment by obrienad** [comment]
@mariel-oar - what do you mean by context aware footer?

**Comment by mariel-oar** [comment]
"Context aware" is probably an over complicated way to phrase it - what i mean is a footer than appears at the end of the page scroll, under all of the page content (which is in different places depending on the page layout and length of page content)

**Comment by obrienad** [comment]
Blocked pending Nice and Serious work.

**Comment by obrienad** [comment]
Mariel confirmed she made the URL update, so removing CAN.

**Comment by obrienad** [comment]
@mariel-oar - can you provide an OS Hub "powered by" logo for EMs?

**Comment by mariel-oar** [comment]
@obrienad , replied re: EM powered by logo on #2186 (that graphic will be ready Oct 14) 

Also wanted to flag for you, @TaiWilkin , and @mstone121 , that there is one line (for the donate page) that is different that the links referenced in the codepen HTML code. Updated above.

**Comment by obrienad** [comment]
@mariel-oar - we're updating the root URL once info site is live so links aren't broken in the interim.
