### ISSUE TITLE
Updated Sector Taxonomy & Logic 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2080]
## Overview

This ticket includes requirements for updated processing logic for the sector field. This 

### Included Requirements 

1. Sector should be a combined column with product_type in the upload template (e.g. column name = sector_product_type) 
2. This will be a required field. i.e. the list must be uploaded with sector, product type or both. 
3. This column will be processed in a manner similar to how the processing_type_facility_type column is processed in the OAR 
4. There will be a set list of identified sector values that should be pulled from this new sector_product_type column; the values identified as sectors are then displayed under the sector field on facility profiles; values NOT identified as sectors are displayed as product types. 
5. All OAR data (when migrated) should have "Apparel" added to the sector field. 
6. Sector drop down filter should display only the sector values that are on the identified list of supported sectors AND have been submitted as list data (i.e. do not automatically show the entire list of supported sectors - they may not all be submitted data on the site) 

### Technical Implementation

- Add a `Sector` model with a single unique name field with a max of 200 characters.
  - Update `admin.py` so that `Sector` is editable via the Django admin
-  Create a fixture to load the initial list [sectors.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/9576363/sectors.csv)
  - Make sure the default value of `Unspecified` is also included
- Add `sector_product_type` as a field read from Excel/CSV or API requests. 
  - (OS Hub Team Task) Remove `sector` and `product_type` from the templates
  - Avoid breaking existing API integrations by allowing `product_type` to continue to be used as a field name alias for `sector_product_type`
  - Update API documentation 
- For each value submitted to `sector_product_type` try a case-insensitive match to the list of allowed sectors. If there is a match, add the value to the sector array and exclude it from values that will go into the `product_type` extended field. 
- As discussed with the OS Hub team it is OK to keep the sector as a required field. If none of the values in the `sector_product_type` match the list of allowable sectors, set a default value of `Unspecified`

**Comment by jwalgran** [comment]
Labeled client action needed because we are awaiting a list of Sectors from the OS Hub team

**Comment by obrienad** [comment]
Blocked as Klaus is working on defining the sectors. Timing re:

**Comment by mariel-oar** [comment]
Azavea needs to know the name / code of the list that they need to subscribe people to 
as well as the API token that they need to use 
cc: @vrwOAR @hlennett

**Comment by KlausGPaul** [comment]
Provisional initial list transmitted 2022-09-15.
As some sector descriptions may have longer text, we would want to reserve up to 200 characters for that field for now.

**Comment by jwalgran** [comment]
Thank you, @KlausGPaul  We have all we need for the implementation so I removed the client action needed tag

**Comment by KlausGPaul** [comment]
Is the sector list somewhere on the repo? This way we could change and amend its contents. If we had the table name, we could provision SQL DROP and INSERT scripts.

**Comment by KlausGPaul** [comment]
@jwalgran Updated sectors list as discussed today

[sectors.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/9610458/sectors.csv)
