### ISSUE TITLE
Very long download times 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2081]
# Bug Description 
Download of all US facilities (using country filter) took 8 min. It's about 9k facilities. 
Download started at :29 and finished at :37. File is attached. 

# Expectation 
It should take no more than ~2 minute to download the entire database. 

We should disable this feature until it is possible to download ~20k records within 30s, full db in 2 min. We risk users trying to do multiple downloads, thinking that the initial download didn't work / froze. Is people try to do multiple downloads, it more cost for us. 

As an interim solution, we are enabling download for up to 10,000 facilities; beyond that the download button is disabled.
 
This info should be displayed via tool tip or popup when a search results in >10k facilities: 
"Downloads are supported only for searches resulting in 10,000 facilities or less." 

# Technical Implementation

- Add a waffle switch called `allow_large_downloads` to conditionally control visibility of the download button on the search results
  - Reworked search results in PR #2110 
- If the the switch is disabled, only show the download button if the total number of matching facilities is < 10,000

**Comment by mariel-oar** [comment]
[facilities2_8min.csv](https://github.com/open-apparel-registry/open-apparel-registry/files/9396572/facilities2_8min.csv)

**Comment by KlausGPaul** [comment]
Download of complete facilities list, no filter, on a Sunday, took roughly from 07:28 to 15:26 for 91382 records. 
Using the API, downloading all data incl. extended fields, took from 19:12:57 to 23:42:21, thats 16163 seconds for 91379 records. All times CEDT. API calls were made with a 2...3 second pause between calls, no timeouts were encountered.

**Comment by obrienad** [comment]
tagged as CAN because OAR needs to give green light for bugs.

**Comment by mariel-oar** [comment]
is there a point estimate for this @obrienad ?

**Comment by mariel-oar** [comment]
@jwalgran , is this 1 pt for investigation?

**Comment by jwalgran** [comment]
@mariel-oar The 1-point is to add a feature flag switch so that we can hide the download button until we are able to more quickly generate the download.

**Comment by mariel-oar** [comment]
ok, thanks @jwalgran.

Is it possible to only disable download for searches that return more than 10k facilities?

**Comment by jwalgran** [comment]
Yes. I will adjust the feature description to only disable the download button at >10k

**Comment by mariel-oar** [comment]
thank you @jwalgran! last question on this one: 
is it possible to add helper text (i) next to the download button that says "Downloads are only supported for searches of 10,000 facilities or less."

**Comment by jwalgran** [comment]
We can add some help text. Could Nonlocal provide visual guidance on how to manage this interaction?
- Should we hide or disable the download button if there are more than 10k results
- Where should we place the ℹ️ and should we show it all the time, or only when there is a search greater than 10,000 items

**Comment by mariel-oar** [comment]
thanks @jwalgran, I reached out to Adam for input there.

**Comment by mariel-oar** [comment]
@jwalgran, 
Nonlocal suggested to do one of the following (ordered by preferred UX): 

1. Show a popup window in the center of the screen that says downloading is not supported for searches of over 10k facilities 
2. Show a (i) tool tip to the left of the download button
3. Disable the CSV / Excel selection in the drop down and show the message instead when someone clicks the button

I couldn't find anywhere on the platform where we currently use a center screen popup to display a message, but maybe it exists somewhere @jwalgran? If not, let's go with the helper text. Option 3 seems too counterintuitive / frustrating.
