### ISSUE TITLE
Add text search results to search sidebar

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#209]
## Overview

The prior UI had a way to list search results in text in the search sidebar:

![screen shot 2019-02-18 at 4 09 27 pm](https://user-images.githubusercontent.com/4165523/52976484-ae5e3a80-3397-11e9-8da1-330f6cd7baa8.png)

We should recreate a similar functionality.

### Describe the solution you'd like

List search results in text form in the search sidebar somehow. This could involve adding a new tab to that sidebar or adding the list beneath the existing search bar.

Each facility name should use a react router `Link` tag to link to `/facilities/:id` where `:id` is the facility's `oar_id`.

**Comment by jwalgran** [comment]
Labeled as a question because I am not sure we want to carry this behavior forward.

As of now we have implemented text searching as just another filter that combines with the dropdown list selections to narrow the search results.

@katieashaw and @nataliegrillon, is having the text filter behave differently a desired feature?

**Comment by katieashaw** [comment]
Coming back on a few points in this thread, to be certain I've understood correctly:

- Having a list of the facilities returned by a search displayed in a column as per the screenshot, which you can then click onto take you to the facility details - and have the map zoom to that facility - is a desired feature that we would like to keep.

- When it comes to text searching on the site, ideally we would like there to be an elastic, free text search box so users could search using terms such as "socks", "organic" etc, and have results returned with have been tagged with those keywords. Is that possible?

@nataliegrillon Jump into add any nuance / Qs you may have!

**Comment by kellyi** [comment]
I created https://github.com/open-apparel-registry/open-apparel-registry/issues/244 for restoring the map zoom interactions. Seems like we should also make the map zoom to the marker when the user visits `/facilities/:oarID` directly and the facility data returns from the API.
