### ISSUE TITLE
Match processing attempts to process the CSV header row

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#211]
## Overview

While working on #206 I noticed that the first row for any CSV I uploaded would end up in an error state if I ran the match processing all the way through on the list:

<img width="338" alt="screen shot 2019-02-19 at 4 57 45 pm" src="https://user-images.githubusercontent.com/4165523/53050782-1da35f80-3468-11e9-9f5b-b2b19509d75b.png">

### Expected Behavior

CSV parsing should discard the header for the match processing.

### Actual Behavior

CSV parsing doesn't always discard the header for match processing

### Steps to Reproduce

Upload a list through the app, then run the processing script through the parse, geocode, and match steps and verify that the first row in the UI is in the error state depicted above.

**Comment by rajadain** [comment]
I notice that here, we add all lines in the CSV file as FacilityListItems:

https://github.com/open-apparel-registry/open-apparel-registry/blob/76a1ea9b20b199ddb9ebc658d624964adc41818a/src/django/api/views.py#L338-L344

This causes the header row to be added to `api_facilitylistitem` table:

```sql
SELECT id, row_index, raw_data, status, facility_list_id
FROM api_facilitylistitem
WHERE row_index = 0;

 id | row_index |       raw_data       |  status  | facility_list_id
----+-----------+----------------------+----------+------------------
  1 |         0 | country,name,address | ERROR    |                1
 83 |         0 | country,name,address | UPLOADED |                2
(2 rows)
```

I can skip that one line like this:

```python
for idx, line in enumerate(csv_file):
    if idx > 0:
        new_item = FacilityListItem(
            row_index=idx,
            facility_list=new_list,
            raw_data=line.decode().rstrip()
        )
        new_item.save()
```

One effect of this will be that the `row_index` field will start at `1`. This can be adjusted to start at `0`, but then it won't directly match the line number of the input CSV, which will continue to include a header row. Which is preferable?

**Comment by jwalgran** [comment]
I think we should adjust the value so that `row_index` continues to start from zero. AWS Batch array jobs feed us a zero based index.

**Comment by kellyi** [comment]
> I think we should adjust the value so that `row_index` continues to start from zero. AWS Batch array jobs feed us a zero based index

I made a comment about this on #241 but I wonder if we should decouple the row_index as used by AWS batch from the row index displayed to the user? Users who have uploaded CSVs will probably imagine that their first entry is in the second row after the header, not the 0-indexed row. It seems like it might be best for batch to keep the 0 indexing for items it processes, so I wonder if we should just add a new serializer method field which is like `row_index + 2` and then propagate that through the UI as the "Row Index".
