### ISSUE TITLE
Sector drop down is listing non-sector values

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2112]
Sector on OS Hub appears to be displaying a drop down list wtih product type values: 

<img width="346" alt="Screen Shot 2022-08-31 at 9 07 37 AM" src="https://user-images.githubusercontent.com/97469356/187686735-917b2a8c-5e0d-41e3-930e-c3338860345c.png">

## Expected Behavior 
Sector drop down lists only submitted sector values (this behavior will change with #2080 because only sector values that are on the list AND have been submitted should be displayed in the drop down) 

There was a similar bug to this related to #2004

**Comment by obrienad** [comment]
Closed because this was due to a user error.
