### ISSUE TITLE
OS Hub claim wizard header should use the a new brand color instead of the legacy blue

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2131]
## Overview

@mariel-oar I labeled this `client action needed` because I could not find a design in the Figma document with new color guidance for the claim wizard

<img width="1261" alt="Screen Shot 2022-09-12 at 7 38 45 AM" src="https://user-images.githubusercontent.com/17363/189686625-b8d3b134-32ff-4f04-ab61-5f92a7de392d.png">

I presume the color should be the purple brand color seen here in a contribute design

<img width="485" alt="Screen Shot 2022-09-12 at 7 57 09 AM" src="https://user-images.githubusercontent.com/17363/189687433-0375e70c-1195-459d-8d0b-c9c017f0f7a9.png">

**Comment by jwalgran** [comment]
Estimate of zero because it shares a point with #2132

**Comment by mariel-oar** [comment]
Why is the CAN label on this?

**Comment by jwalgran** [comment]
I labeled this `client action needed` just to get confirmation that we should change the color of the header on the claim page to "brand purple" (see second screenshot in the description) instead of the legacy blue. I did not see a design in Figma  for the facility claim wizard.

**Comment by obrienad** [comment]
@mariel-oar - can you advise?

**Comment by mariel-oar** [comment]
@jwalgran @obrienad, confirming that brand purple is fine here.

**Comment by obrienad** [comment]
Mariel confirmed she made the URL update, so removing CAN.
