### ISSUE TITLE
Use the new marker on the OS Hub facility details satellite map

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2132]
Currently the legacy marker is being used

<img width="703" alt="Screen Shot 2022-09-12 at 7 53 17 AM" src="https://user-images.githubusercontent.com/17363/189687627-2b7c09ad-50b3-40dc-9c92-fb7dad4f5f72.png">

A screenshot of the new marker in the designs

<img width="684" alt="Screen Shot 2022-09-12 at 8 00 34 AM" src="https://user-images.githubusercontent.com/17363/189687903-3237d6b5-8468-4b2f-881c-4c09df505c81.png">

The SVG for the marker was already added to project, but the Google satellite map may require a PNG version. The marker is in the Map Components section of the Figma https://www.figma.com/file/FGVrJYElirWCQyR7nBehF0/OAR

**Comment by TaiWilkin** [comment]
Noting that the icon doesn't work in development, because Google requests the marker separately, and then can't access our local-host. This ticket isn't expected to fix that issue, just update the icon.
