### ISSUE TITLE
Embedded Map: Only active list data in download

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#2135]
## Overview

In Embedded Maps, only data from active lists should appear in the download, to match the data that is in the Embedded Map itself. Currently, if the contributor has inactive lists, the additional data points from those lists are showing up in the download, too. 

See Columbia Sportswear's map: https://www.columbiasportswearcompany.com/corporate-responsibility-group/responsible-practices/supply-chain/

And then this download of their data from their map: https://docs.google.com/spreadsheets/d/1agcSxksBdFHjTwj-0iJ96j0Jvvl0-GGq1XjvEMZpIGI/edit?usp=sharing

If you look at: TW2022064MY5TN1

On the map, you can see only Footwear listed as the Product Type. In the download, you see a long, repetitive list of all of the Product Types they have submitted to this facility, since they have submitted some lists multiple times to resolve errors. 

Users would ideally want their download from their Embedded Map to match the data in the map itself.

**Comment by mariel-oar** [comment]
@jwalgran @obrienad , can you let us know when this is ready to test on staging? There's a particular case we want to test.

cc: @hlennett

**Comment by jwalgran** [comment]
@mariel-oar @hlennett The updated embed CSV format is now deployed to staging.opensupplyhub.org
