### ISSUE TITLE
Access for India Fallon

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#2137]
We'd love to get our new employee, India, added to our GitHub instances, as well as given Admin privileges in OAR Staging and Prod, + the Beta. 

Her GitHub username is india-oshub. 

She used india@openapparel.org to register for her accounts on OAR Staging, Prod and Beta.

**Comment by jwalgran** [comment]
I invited India to the Github org and made them an admin on OAR staging and production. I could not find their account on OS Hub staging so I sent an email requesting that they reply after registering.
