### ISSUE TITLE
Show country name instead of code on the list detail page

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#214]
## Overview

We standardize on using the 2-character code internally, but the uploaded lists almost always use the full country name. Show the full country name on the list detail page.

### Describe the solution you'd like

* Replace the "Country Code" column with "Country"

**Comment by kellyi** [comment]
Since the API already has a map of country codes to country names, I'm just going to update the list item serializer to return this as an additional key/value pair for display in the list items table.
