### ISSUE TITLE
Update Terminology on map site 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2143]
## Overview

We've found through user interviews that some of the terms that we use on our website can be confusing to our users. Specifically: the call to action button being "Contribute," referring to users as "contributors," and "Public Lists." The latter (public list) is something that the OS Hub team can address on our own, but we need help in having the other references on the map site changed. 

Specific places where these terms are used is called out below. 

#### Filters on the [home page](https://9f692df0338dcbc9848646c6.openapparel.org/): 

- Contributor --> Data Contributor
- Contributor Type --> Stays same for now

#### Field Names on [Register page](https://openapparel.org/auth/register) and [Settings page](https://9f692df0338dcbc9848646c6.openapparel.org/settings): 
- Contributor Name --> Organization Name 
- Contributor Description --> Organization Description 
- Contributor Type --> Organization Type 

#### [Facility profile](https://9f692df0338dcbc9848646c6.openapparel.org/facilities/TR2020078EGZA00) pages -

- 14 more contributions --> 14 more entries
- 19 organizations have contributed data for this facility --> 19 organizations have uploaded data for this facility

#### Notifications tab on [Settings Page](https://9f692df0338dcbc9848646c6.openapparel.org/settings)
- Notifications --> API Notifications (this is in reference to the name of the tab)
- Add copy above fields that says: "This feature is in development. Notification logic can be created but events will not be sent at this time." 

#### Processing Complete Email copy
This is the email that gets sent to a user after their list has been approved and the data has completed geocoding. Update existing email to the copy provided [here](https://docs.google.com/document/d/1l-cECNgAR5EfUzkpKLLiQBRiH6GdgsPpVoxZzoCXQ_c/edit?usp=sharing).

**Comment by mariel-oar** [comment]
@hlennett , can you confirm the copy changes above.

**Comment by hlennett** [comment]
@mariel-oar Here would be my suggestions:

Home Page:
Contributor Name --> Data Contributor
Contributor Type --> Stays same for now

Field Names on [Register page](https://openapparel.org/auth/register) and [Settings page](https://9f692df0338dcbc9848646c6.openapparel.org/settings):

Contributor Name --> Organization Name
Contributor Description --> Organization Description
Contributor Type --> Organization Type
(These can be organization because they may or may not be contributing data). 

[Facility profile](https://9f692df0338dcbc9848646c6.openapparel.org/facilities/TR2020078EGZA00) pages -

14 more contributions --> 14 more entries
19 organizations have contributed data for this facility --> 19 organizations have uploaded data for this facility

**Comment by mariel-oar** [comment]
Thanks @hlennett , I've updated the requirements. I left it as "contributor" on the home page because that is the exact copy that Azavea will change (i.e. it doesn't say "Contributor Name"). Let me know if it does say Contributor Name somewhere that I'm missing.

**Comment by hlennett** [comment]
@mariel-oar The convo we'd had in our taxonomy discussion was that it would change from Contributor ---> Data Contributor. I think I just mistyped Name there. Could you update to Data Contributor?

**Comment by mariel-oar** [comment]
yes, it's updated to Data Contributor.

**Comment by obrienad** [comment]
tagged CAN pending decision re: #2156 2156 (and whether it should be included here)

**Comment by obrienad** [comment]
OAR approved working on this ticket, CAN remains as @mariel-oar is updating a URL.

**Comment by obrienad** [comment]
Mariel confirmed she made the URL update, so removing CAN.

**Comment by TaiWilkin** [comment]
Made #2183 for link updates, but it's covered here, so I'm going to close that.

**Comment by mariel-oar** [comment]
@TaiWilkin @obrienad @jacobscarfmerrell, i just realized that since you all are picking up the footer ticket #2079 that you don't need to make the footer link changes referenced above

**Comment by obrienad** [comment]
Updated to remove info site references. Covered in #2183.
