### ISSUE TITLE
Create 404 page for React app

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#216]
## Overview

Currently non-matching routes for the React client will just render the navbar plus a blank page beneath. We should create a component to use as a 404 page.

### Describe the solution you'd like

- add a new memoized function component reporting that the requested route could not be found as the default case in whatever is the appropriate `Switch` JSX.

**Comment by kellyi** [comment]
When this component exists, it can be set up to display when no existing route matches by placing it in a route declaration in this `Switch` block: https://github.com/open-apparel-registry/open-apparel-registry/blob/develop/src/app/src/App.jsx#L102

```
<Route
    component={New404Component}
/>
```

...without a `path` prop will work as if it's the `default` case at the end of a regular `switch` bock.

**Comment by designmatty** [comment]
Is there a base component/route setup for this already that I can design on top of?

**Comment by kellyi** [comment]
@designmatty not yet but I will create one now and put up a PR with the new component.

**Comment by kellyi** [comment]
@designmatty there is now a component called `RouteNotFound` ready to go.
