### ISSUE TITLE
Links from the OS Hub contributor details page to the search page sometimes loose their query string argumes

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2173]
## Overview

Links from the OS Hub contributor details page to the search page sometimes loose their query string argumes.

### Expected Behavior

The "View map of facilities" link and the links to the individual lists on the contributor details page navigate to the search page and run the appropriate search

### Actual Behavior

The links have the correct query parameters but the query parameters disappear when the search results load.

NOTE: Browsing a contributor search link directly in a new browser window (like `/facilities?contributors=1710`) does work correctly, but browsing a list search link directly in a new browser window (like `/facilities?contributors=1710&lists=1355`) results in the list query string argument disappearing. 

### Steps to Reproduce

* Browse a facility details page
* Open the contributors drawer
* Click a contributor link
* From the contributor details page click the "View map of facilities" button

### Contributor search

![2022-09-27 09 11 43](https://user-images.githubusercontent.com/17363/192579956-a5a24154-780a-4071-bf75-ae981e9b22bc.gif)

### List search

![2022-09-27 09 25 44](https://user-images.githubusercontent.com/17363/192582160-4b41851d-c593-4169-8cb3-ad3691a18b54.gif)

**Comment by mariel-oar** [comment]
this happens 100% of the time?
