### ISSUE TITLE
Update info.openapparel.org links for OSHub

### ISSUE THREAD

**Issue by TaiWilkin** [open-apparel-registry/open-apparel-registry#2183]
#### Info site URLs
All URLs that link to info sites at info.openapparel.org need to be updated to: info.opensupplyhub.org: 

1. On the [Contribute Page](https://9f692df0338dcbc9848646c6.openapparel.org/contribute), the URL that links to step by step instructions needs to be updated: 

- FROM https://info.openapparel.org/stories-resources/how-to-contribute-data-to-the-oar 
- TO https://info.opensupplyhub.org/stories-resources/how-to-contribute-data 

*Note that the URL above ends at "contribute-data" and that the "to-the-oar" part is dropped

2. On the Footer: links for Contact Us, Work With Us, FAQs, Privacy Policy, and Terms of Service change from a root url of https://info.openapparel.org/[page] TO https://info.opensupplyhub.org/[page]
- Contact Us: https://info.opensupplyhub.org/contact-us
- Work With Us: https://info.opensupplyhub.org/work-with-us
- FAQs: https://info.opensupplyhub.org/faqs
- Privacy Policy: https://info.opensupplyhub.org/privacy-policy
- Terms of Service: https://info.opensupplyhub.org/terms-of-service
- Donate: http://info.opensupplyhub.org/donate

3. On the Header: 
- Donate: http://info.opensupplyhub.org/donate

**Comment by TaiWilkin** [comment]
#2143 covers this

**Comment by jwalgran** [comment]
@TaiWilkin Based on your comment it looks like #2143 covers. Please check that there isn't anything noting in this issue that has not already been implemented.

**Comment by TaiWilkin** [comment]
@jwalgran We re-opened this because we'll need to do a final switch-over to the new root URL for the info site, and a check of all info site links, to confirm everything is working once the info site is live.
