### ISSUE TITLE
Rename production URL and change name servers in Google Domains

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#2185]
- Domain name registration
- Info site CNAME (provided by Nice & Serious)

**Comment by obrienad** [comment]
@mariel-oar - can you confirm when you expect to get the CNAME for the site?

**Comment by nanotubing** [comment]
@mariel-oar: to set up info.opensupplyhub.org, we will need an address to direct traffic for that domain to. This would be provided by the web host for that site. I can show you how the existing site is configured if it helps track down the right information

**Comment by obrienad** [comment]
Removed CAN as N&S provided necessary information (email).

**Comment by nanotubing** [comment]
The following records should be manually added to opensupplyhub's route53 once terraform has created the new zone. This is taken from the bind format zone file exported from the google domains interface, which is where dns is currently hosted:

### Hubspot domainkey records
```
hs1-19901037._domainkey.opensupplyhub.org. 60 IN CNAME opensupplyhub-org.hs02a.dkim.hubspotemail.net.
hs2-19901037._domainkey.opensupplyhub.org. 60 IN CNAME opensupplyhub-org.hs02b.dkim.hubspotemail.net.
```

### Info Site CNAME
```
info.opensupplyhub.org. 60 IN CNAME open-supply-production.cl-uk-london-1.servd.dev.
```

### GSuite Records
```
opensupplyhub.org. 3600 IN MX 1 aspmx.l.google.com.
opensupplyhub.org. 3600 IN MX 1 aspmx.l.google.com.
opensupplyhub.org. 3600 IN MX 5 alt1.aspmx.l.google.com.
opensupplyhub.org. 3600 IN MX 5 alt2.aspmx.l.google.com.
opensupplyhub.org. 3600 IN MX 10 alt3.aspmx.l.google.com.
opensupplyhub.org. 3600 IN MX 10 alt4.aspmx.l.google.com.

opensupplyhub.org. 3600 IN SPF "v=spf1 include:_spf.google.com ~all"
opensupplyhub.org. 3600 IN TXT "v=spf1 include:_spf.google.com ~all"

google._domainkey.opensupplyhub.org. 3600 IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn4WckSa6Cn/69caGB39oi18qd6Ney36L8E2zUjPE86d0Es6rmhA1UUua432gfXZPDvZzEFPAdvAt9dMgp79XYOkNC4X9zQ4csM4fFuEqRacUMXq6dMnnPFJ+NnmFonwWo7cdYg3b4G09TZ0hC2uRf6wWLCowfoCGi6Rcxh23aRceVmQBiy2Dgf4TcbI5cPBZK" "Ap8AVsUuIkLT5p4WLN7YpPdnP93jaFUT5E7Zjg7y1FYGbihzElqJ2kT2w6FyrZnMN8RAzKYGsUdQJs9pycKUrtOMayQcGDJnX9ID5G4OICmQlo9phEDe7sXUbAl3rPq4BWvPsZ/DIX08N5kQuj9ZQIDAQAB"
```

**Comment by mariel-oar** [comment]
1) In addition to the above, we will need to add the 4 new DNS servers to google domains? 

<img width="992" alt="Screen Shot 2022-11-01 at 12 10 41 PM" src="https://user-images.githubusercontent.com/97469356/199307024-edb31585-d2b3-42c8-8ea8-e5ecb909a668.png">

2) In addition, the info site developers asked about this - would this also be done in Route 53? 
- Set up new subdomain for archiving the current OAR site: [archive.openapparel.org](http://archive.openapparel.org/)
- Point it at Servd, using the same details as the current site:
- CNAME record: [tidy-shrike-production.cl-us-east-2.servd.dev](http://tidy-shrike-production.cl-us-east-2.servd.dev/)

**Comment by nanotubing** [comment]
> 1. In addition to the above, we will need to add the 4 new DNS servers to google domains?

Correct. Amazon gives you those once you add a domain to route53, so we don't get them in advance. Once we get them, we'll add them into the google domains interface.

>  2. In addition, the info site developers asked about this - would this also be done in Route 53?

yeah, the subdomain for `archive.openapparel.org` gets added to the route53 interface
