### ISSUE TITLE
Change or remove the "powered by" image for OS Hub embedded map

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2186]
Embedded maps have a "powered by" image in the footer. For OS Hub embedded maps we will need to change or remove this

On the individual facility pages for EM, replace the link text that says "View on the Open Supply Hub" with "View on Open Supply Hub" 

![Screen Shot 2022-10-07 at 9.36.19 AM.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/75395d1f-91cb-41c2-98b9-4a57779fa18a)

<img width="811" alt="Screen Shot 2022-09-28 at 9 45 24 AM" src="https://user-images.githubusercontent.com/17363/192841184-2559dcf0-c3c3-4e7c-9519-d2c72815b969.png">

Design files for logo: 
![OSH_PoweredBy_white.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/f507408a-a476-469d-bcf2-97c170018ce5)

**Comment by jwalgran** [comment]
@mariel-oar Labeled client action needed because we need to

1) Decide if we want to replace or remove the embedded map footer image
2) If we are going to replace it with an image, we need one of our design partners to create it. Alternatively we could replate it with a text link.

**Comment by mariel-oar** [comment]
@jwalgran, we have a new graphic for this coming Oct 14, so suggest holding on it until then and going with option 2

**Comment by obrienad** [comment]
@mstone121 - this issue is unblocked!
