### ISSUE TITLE
Logic for display of Sector field on EM 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2187]
## Overview

The logic for all Extended Data Points on Embedded Maps has been to hide those data points which the EM contributor has not submitted. This ticket specifies the logic that should be used to decide when the Sector field is displayed on the OS Hub EMs. 

### Solution 

1. Add a check box to the EM settings page that allows a user to toggle the display of the sector field on and off.

**Comment by mariel-oar** [comment]
@obrienad, please let us know the pt estimate and which implementation solution the team wants to move forward with on this one.

**Comment by obrienad** [comment]
@mariel-oar - 2 points for approach 1 and 3.

**Comment by mariel-oar** [comment]
Thanks @obrienad , sorry one more clarification - would it be possible for 3. to work on OS Hub as well or the 2pts would only cover EM?

**Comment by obrienad** [comment]
@jwalgran - tagging you for response.
