### ISSUE TITLE
Update Google Analytics Key for OS Hub

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#2188]
Update Analytics Key for OS Hub.

Consider updating to [Google Analytics 4](https://support.google.com/analytics/answer/10089681?hl=en) since Google Google Analytics Universal Analytics tag is going to be deprecated next year.

**Comment by hlennett** [comment]
We do have one set up for OS Hub. Property ID: 320730191. Is there any specific code or info you need?

**Comment by nanotubing** [comment]
@hlennett the value we need might be called Tracking ID in google analytics? it starts with `UA-`, followed by a string of numbers. Thanks!

**Comment by hlennett** [comment]
How this: G-PFQY2JR2KH. I think with GA-4 the format may have changed.

**Comment by nanotubing** [comment]
Thanks, I'll give it a try!

**Comment by mariel-oar** [comment]
@TaiWilkin here are the measurement IDs for each site: 

OS Hub info: G-3N9248MR8P
OS Hub prod: G-GSLW5DLZQY
OS Hub staging: G-GS2XMYGRN9
