### ISSUE TITLE
Issue with background color of text on hover

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2218]
Related to header tickets: #2202

### Context 
When hovering over the text menus that display under the "My Account" page of the header, we are seeing a black background. 

![Screen Shot 2022-10-05 at 8.55.09 AM.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/7e9f0e1b-efac-4a39-abfd-1aa1bd994bf0)

### Solution 
The hover state should look just like it does on the other header menus (the mouse turns into the click icon, e.g. a pointer finger on my computer - doesn't display during a screen shot)

**Comment by jwalgran** [comment]
I opened #2217 yesterday with a few small styling issues I found during testing, including this one. I am going to close this issue since it is included in #2217.
