### ISSUE TITLE
Superuser unable to remove list items from pending lists 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2220]
### Overview 
There is a button to remove a facility in the list detail view. This button does not currently work. 

### Desired Behavior 
Required: 
1) PENDING LIST - Clicking remove on a facility when a list is in pending status, results in the facility being removed from the list and not geocoded (in the event that list is approved) 

Nice to have: 

2) MESSAGE - Similar to when a list is rejected, there should be a popup when a facility is removed from a pending list. This is free form text box for OS Hub team to message what the issue is. This then triggers an email with OS Hub team's feedback to go to the contributor. 

### Additional Context: 
![Screen Shot 2022-10-05 at 11.34.20 AM.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/f17482f1-e27b-40a6-bd66-15fdbb26002b)!

### Technical Implementation

The API is returning 404

<img width="1214" alt="Screen Shot 2022-10-07 at 9 05 35 AM" src="https://user-images.githubusercontent.com/17363/194598445-50e83052-3b0e-4b3d-acfe-fbfab6c4cda7.png">

This is most likely because the `remove_item` view function includes

```python
            facility_list = FacilityList \
                .objects \
                .filter(source__contributor=request.user.contributor) \
                .get(pk=pk)
```

and this associated except block

```python
        except FacilityList.DoesNotExist:
            raise NotFound()
```

Before we updated the workflow to allow the moderation team to handle approve/reject on lists we enforced that only the owner of the list could take action on it

- Update `remove_item` to allow superusers to remove items from a list

**Comment by jwalgran** [comment]
- In which  environment did you run into this error, OAR production, OAR staging, or OS Hub staging? 
- From which list did you create that screenshot?

I was able to remove an item from a test list in OS Hub staging, so that points to there being a problem with a specific data situation, not the entire feature.

<img width="1219" alt="Screen Shot 2022-10-05 at 11 09 18 AM" src="https://user-images.githubusercontent.com/17363/194132001-10c84474-502c-4097-bbfa-c40a211a5f15.png">

**Comment by mariel-oar** [comment]
OS Hub staging

**Comment by mariel-oar** [comment]
@obrienad , do you know if the nice to have on this is being implemented?: 

Nice to have:

MESSAGE - Similar to when a list is rejected, there should be a popup when a facility is removed from a pending list. This is free form text box for OS Hub team to message what the issue is. This then triggers an email with OS Hub team's feedback to go to the contributor.

**Comment by jwalgran** [comment]
No. The nice to have popup/email notification when items are removed has not been implemented.

**Comment by mariel-oar** [comment]
ok, thanks for confirming
