### ISSUE TITLE
Facility_type_Processing_type for OS Hub

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2224]
### Overview (state of the OAR world): 
In OAR, since all facilities are within the apparel sector, there is an established taxonomy for mapping processign type values to a facility type. Regardless of whether facility type is contributed, if there is a processing value that matches our taxonomy, the associated value for facility type will be displayed on the profile under the facility type field. Any values contributed as part of processing_type_faciltiy_type that do not match our taxonomy are displayed under the processing type only. 

At the start of OS Hub Beta, this logic still applied, but since facilities were outside of apparel all values contributed only displayed under processing type. 

### Solution 

On OS Hub: 

- For facilities contributed as apparel sector, the OAR logic for processing_type_faciltiy_type is applied. 
- For facilities contributed as any other sector, values contributed in the processing_type_facility_type field should be accepted and displayed under processing type.

**Comment by jwalgran** [comment]
@mariel-oar Contributors can specify more than one sector. As an example, if a contributor specifies `Apparel` and `Electronics` (or any number of non-Apparel sectors), should we use the OAR logic for the parsing the `facility_type_processing_type` values?

Tagging client action needed since wee need an answer to this question to build the feature

**Comment by mariel-oar** [comment]
yes, if apparel is a sector value that's being contributed, then parse all processing_type_facility_type values as they are for the apparel sector; else leave them tagged as processing type.

**Comment by TaiWilkin** [comment]
@mariel-oar Two questions to confirm my current understanding:
1. Should all items submitted with processing_type_facility_type (on non-apparel items) be labeled as processing_type?
2. Should items submitted with processing_type_facility_type be matched to the processing_type taxonomy, or should they be saved as raw data without formatting? (The downsides of just using the raw data are that it won't necessarily be formatted well when it displays on facility details, and that these values won't be available in the Processing Types filter.)

**Comment by TaiWilkin** [comment]
@mariel-oar I think that actually answers the question - if the processing types in the taxonomy definitely don't apply for the non-apparel items, attempting to match to them doesn't make sense, so we should just use the raw data. 
E.G., if someone submits 'seam tape' for a 'Home Furnishings' sector item, we will assign the `processing_type` as 'seam tape' without trying to match it to the Apparel taxonomy's 'Seam Taping'.
