### ISSUE TITLE
Mapbox API Key Not Set

### ISSUE THREAD

**Issue by rajadain** [open-apparel-registry/open-apparel-registry#223]
## Overview

Mapbox API key is not being set on the map, because it is using the new style environment injection introduced in https://github.com/open-apparel-registry/open-apparel-registry/commit/e9b95288a34566410ddfa53e9b122d9e89c31d16. Compile time variable replacement only works when the entire string is specified using dot notation, e.g. `process.env.REACT_APP_MAPBOX_TOKEN`, not via the indirection being used now.

For unclear reasons, this has not caused a crash on staging.

### Expected Behavior

Mapbox API key is set.

### Actual Behavior

Mapbox API key is not set.

### Steps to Reproduce

* Open the developer tools and look under Debugger / Sources, and isolate the missing variable

### Additional context

See here for more on build-time environment variables for Create React App: https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables.

We may have to adopt fundamentally different strategies for compile time and run time variables.

**Comment by kellyi** [comment]
This seems to have been a false alarm, so I'm closing this for now.
