### ISSUE TITLE
Move TrainedModel file storage to a django file field backed by Django storages

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2230]
**NOTE** The implementation for this should be targeted at the `ogr/feature/dedupe-upgrade-and-refactor` branch

- This refactored dedupe is not released so we don't have to worry about a data-preserving migration
- There is a `trainedmodel.json` fixture that we have used to bootstrap both development and deployed test releases. We will need to convert this to a management command that creates and saves rows using a model file checked into the repo and is included as part of `resetdb`.
- Files saved in development should go into a directory that is in `.gitignore`
- Model files could either go into a new bucket or a folder within the existing "files" bucket.
- Naming the files to include the ID of the trained model would be helpful when browsing the bucket in the console.

**Comment by jwalgran** [comment]
I used the code below to write out the trained model we currently have in a fixture.

[dedupe_model.pickle.zip](https://github.com/open-apparel-registry/open-apparel-registry/files/9767046/dedupe_model.pickle.zip)

<img width="649" alt="Screen Shot 2022-10-12 at 9 43 56 AM" src="https://user-images.githubusercontent.com/17363/195400968-b79354b0-6484-47a1-8ff5-db3e77f688af.png">

**Comment by KlausGPaul** [comment]
Should we consider moving this to S3 to facilitate concurrent access?

**Comment by jwalgran** [comment]
Already done, actually. In  #2241 we used the same storage abstraction we introduces to save uploaded lists to S3 for our training model files.
