### ISSUE TITLE
On initial load of the OS Hub homepage the compact map and sidebar are small before resizing

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2231]
**NOTE** The fix for this should be time boxed to 1 hour 

This results in 
- A redraw with a lot of page motion once the content is ready
- Potential map rendering issues

This was most easily repeatable in an incognito window. I was able to repeat it in both Firefox and Chrome

![2022-10-11 11 29 31](https://user-images.githubusercontent.com/17363/195172174-55124bdf-31bd-4c01-a736-b183c9f1434f.gif)

### Technical implementation

- Set height based on window minus header
- Center spinner

**Comment by mariel-oar** [comment]
@obrienad @jwalgran, can you provide more details about what part of this is repeatable? or what conditions are required for repeatability? I am not able to see this behavior in chrome. 

also a point estimate would be helpful in deciding how much of a priority this is

**Comment by jwalgran** [comment]
We will be having a planning meeting shortly so we can provide more detail and an estimate within the hour.

**Comment by obrienad** [comment]
It is a 1 (point, but also hour). Ability to reproduce it might be affected by data being loaded or the map is changing - those things might make it easier to see the problem.
