### ISSUE TITLE
(Final) Terminology Updates

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2235]
### Description 
- This ticket includes all final copy changes / tweaks for OS Hub. 

### Requirements: 

1. Footer update - REPLACE: "Open Apparel Registry, Inc., doing business as Open Supply Hub, is established as a 501(c)(3)..." WITH: "Open Supply Hub is established as a 501(c)(3)" 
![Screen Shot 2022-10-11 at 9.10.06 PM.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/1a469751-23cb-4182-b145-affc5d8b12d8)
2. Update copy for reject notification email: https://docs.google.com/document/d/16bXhAUnvYkjeTibNGJSUafTb7rtsL6XyT2ajIpPYR8I/edit?usp=sharing
3. Donate link on Footer update to: https://givebutter.com/opensupplyhub2022
4. Reporting link link on the Footer should be: https://opensupplyhub.allvoices.co/
4. The additional fields helper text popup that displays when you hover: remove "the" before Open Supply Hub 
![Screen Shot 2022-10-12 at 2.03.39 PM.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/60326f45-7251-4ca3-86ed-26dece645db1)

**Comment by hlennett** [comment]
In the Embed tab in settings, "Contribute your supplier data" links to an OAR link and the email address is the OAR email address. Can we please also use the following copy (small tweaks made throughout):

To begin, [upload your supplier data](https://openapparel.org/contribute) (via upload or API) to OS Hub with all of the data fields you wish to have displayed on your map using the template supplied to you by the OS Hub Team. This list must include any additional data points you would like to display on your customized map, such as facility type, number of workers etc. The Embedded Map will display all facilities included in your lists.

Adjust the below settings to your liking, such as the map color and size. Once complete, copy the Embed Code to add to your website.

Have questions? Check out the FAQs on our [Embedded Map info page](https://info.opensupplyhub.org/embedded-map) or email [info@openapparel.org](mailto:info@openapparel.org).

**Comment by hlennett** [comment]
The Embed page also refers to the OS Hub ID. Should it be OS ID?

**Comment by hlennett** [comment]
On the upload data page:

can we update this sample text:
"example: 'This is the Alpha Brand list of suppliers for their apparel products valid from June 2021 to Sept 2021'

to:
"example: 'This is the Alpha Company list of suppliers for their retail products valid from Jan 2023 to June 2023'

**Comment by hlennett** [comment]
![Screen Shot 2022-10-12 at 7 08 39 PM](https://user-images.githubusercontent.com/80268596/195405521-646488d4-9589-4443-a4d8-598658e5cf43.png)

When reporting a facility as closed, still goes to OAR email address.

**Comment by hlennett** [comment]
In top of facility claim form, please remove "the" from before OS Hub. 

![Screen Shot 2022-10-12 at 7 10 20 PM](https://user-images.githubusercontent.com/80268596/195405775-332ed838-c9dd-4593-a8aa-c3e94291ae71.png)

**Comment by hlennett** [comment]
On the last page of facility claim form, it links to an OAR email address:

![Screen Shot 2022-10-12 at 7 11 21 PM](https://user-images.githubusercontent.com/80268596/195405984-9ba4036b-d02c-4cc8-b2cf-53796af1cf15.png)

**Comment by hlennett** [comment]
On registration page, please remove "the" before OS Hub

![Screen Shot 2022-10-12 at 7 13 20 PM](https://user-images.githubusercontent.com/80268596/195406323-4ebad6e4-9cd1-47eb-8a75-8900e5480dd9.png)

**Comment by jwalgran** [comment]
Moved back to "in progress" awaiting any additional copy changes from the OS Hub team.

**Comment by jwalgran** [comment]
On login screen, please remove "the" before OS Hub

![Screen Shot 2022-10-12 at 7 14 37 PM](https://user-images.githubusercontent.com/80268596/195406519-65bcba97-b8a5-4e0b-8b1f-ee58b94d0506.png)
