### ISSUE TITLE
Setup production stack

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#224]
TODO: add a checklist of items that must be completed in order to provision a production stack and deploy a release.

**Comment by hectcastro** [comment]
I created https://github.com/azavea/operations/issues/298 to track this because we are having trouble connecting the OAR org to Codetree. It was definitely working before, but it is not now. Working with Codetree support to get it resolved.

**Comment by hectcastro** [comment]
Instantiate all of the resources currently supporting the staging environment in AWS, but for production.

- Updated production variables in remote `.tfvars` file
- DNS
- Certificates
- Email
- Rollbar
- Mapbox
- Google Geocoding
- Database w/ migrations

**Comment by dboyer** [comment]
Note that #263 requires production be in an EU-based data center.

**Comment by rbreslow** [comment]
- [ ] Make sure `develop`, `test/`, `release/`, and `hotfix/` all go to staging
- [ ] Add `Jenkinsfile.release` which takes the SHA of an existing container image and runs the `infra` process against the production settings bucket
- [ ] Add `Open Apparel Registry Release Pipeline` scripted pipeline job to Jenkins
- [ ] Create a GitHub issue template for releases, similar to what was done in https://github.com/raster-foundry/raster-foundry-python-client/pull/75, which walks through git flow steps, as well as running the pipeline
