### ISSUE TITLE
Adjust Facility Match searches return an error - "An error prevented fetching that facility"

### ISSUE THREAD

**Issue by vrwOAR** [open-apparel-registry/open-apparel-registry#2252]
## Overview

When searching for a facility in the dashboard from the Adjust Facility Matches page, some of the search is returning an error stating, "An error prevented fetching that facility". It is an intermittent occurrence, not all searches are returning this error.

### Expected Behavior

From the Adjust Facility Matches page of the dashboard you can enter an OS ID and then click SEARCH to load the facility in question. The match history will populate the page and the split, transfer, & promote actions are available for facilities that are eligible for any of those actions. Any matches that are ineligible for those actions (split, transfer, and/or promote) will remain visible, however they're greyed out and cannot be accessed.

### Actual Behavior

From the Adjust Facility Matches page of the dashboard you can enter an OS ID and click SEARCH, however, the search returns this error "An error prevented fetching that facility".

### Steps to Reproduce

- [Dashboard](https://prd.fb84e0f7529f2737.openapparel.org/dashboard)
- [Adjust Facility Matches](https://prd.fb84e0f7529f2737.openapparel.org/dashboard/adjustfacilitymatches)
- Enter OS ID IN2019083V232EY
- Click SEARCH
- Error returned 
- 
![image](https://user-images.githubusercontent.com/97313337/196602868-e4258573-08b7-42f5-a039-3327bf2b9019.png)

- OperaGX browser
- M1 MacBook Pro 

### Demo

Optional. Screenshots, gifs, `curl` examples, console errors, log files, etc.

### Additional context

Additional OS IDs that returned the same error:

- PK20212306XKW2S
- VN2019083YQJWWT

**Comment by vrwOAR** [comment]
Additional facilities returning the fetching error:

- BD202134107DFMA
- BD2021336VXGX73

**Comment by jwalgran** [comment]
We traced this issue to our renaming of `oar_id` to `os_id` throughout our application code and I built a recently approved tool in #2251 to fix references to the old name in the database. We will be able to run this tool on OS Hub production after our next release.

**Comment by mariel-oar** [comment]
Merged, Closed
