### ISSUE TITLE
Bug where map is zoomed out if you open a profile from C/R view 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2267]
When I click on a profile from the list of confirm / reject facilities, the profile sometimes goes to a zoomed-out version of the map (globe view) instead of individual facility view. 

This is P2, given that it seems isolated to opening facilties from C/R window. 

https://images.zenhubusercontent.com/159699912/8286d00f-ec5f-4518-a0cc-4c8f752c4d13/screen_recording_2022_10_25_at_7_16_00_pm.mov

**Comment by jwalgran** [comment]
This was addressed in pull request #2267 which we are scheduled to deploy to OS Hub production on Wed October 26
