### ISSUE TITLE
Contributors on staging site are not currently listed in alphabetical order [SHOULD SHARE A POINT]

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#227]
## Overview

In the Contributors dropdown on the staging site, the names do not appear in alphabetical order. 

### Expected Behavior

Names should appear in alphabetical order. 

### Actual Behavior

Names appear in random order (possibly the order in which they were added to the site?).

### Steps to Reproduce

* Visit staging site
* Select dropdown menu of the Contributor tab

### Demo

Optional. Screenshots, gifs, `curl` examples, console errors, log files, etc.

### Additional context

Optional. Add any other context about the problem here.

**Comment by kellyi** [comment]
Contributors currently return from an `all_contributors` method in the Django views: https://github.com/open-apparel-registry/open-apparel-registry/blob/develop/src/django/api/views.py#L175

We can probably just have the queryset which creates the tuples order by `name`.

**Comment by kellyi** [comment]
Shares points with #209
