### ISSUE TITLE
Change banner color of staging site so that it is obvious when on staging vs prd 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2270]
Change the white banner on staging to be the purple brand color (see below for color details) to indicate that you are on staging vs production. 

The banner is the part of the screen where the logo, menu options, and upload data button are located. 

Use the `environment` already available in `environment.js` to toggle the color.

Purple: 
"# 8 4 2 8 FA"
C M Y K 6 7 7 8 0 0
R G B 1 3 2 4 0 2 5 0
pa n t o n e 2 6 6 C

![Screen Shot 2022-10-26 at 10.52.16 AM.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/a2fb3bf0-f700-451d-9975-3c07e6b89e8d)

**Comment by jwalgran** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2270?planning-poker) with Zenhub @TaiWilkin @nanotubing
