### ISSUE TITLE
Create static S3 bucket site for OS Hub "maintenance mode"

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2274]
- Create an index.html
  - Based on the index.html from the app, without dynamic content 
      -  I started a file: [inded.html.txt](https://github.com/open-apparel-registry/open-apparel-registry/files/9882062/inded.html.txt)

  - Header log
  - Some "down" language from the OS Hub team
- Create an S3 "website" bucket to server the index.html
- Test on OS Hub staging 
  - Manually adding a CloudFront origin pointing to the bucket site
    - The second origin should be added to the existing distribution
  - Manually changing the default behavior of the distribution to point to the bucket

**Comment by jwalgran** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2274?planning-poker) with Zenhub @TaiWilkin @nanotubing

**Comment by obrienad** [comment]
Removed CAN because OAR approved shared [copy](https://docs.google.com/document/d/1J04xJzyQ-r6E1Yjizo3IAzNSYbzASklUZOXE07eEyXk/edit)

**Comment by jwalgran** [comment]
I added "The second origin should be added to the existing distribution" to the issue description to clarify.
