### ISSUE TITLE
Link & copy updates

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2291]
## 1) Copy change in header 
Under the globe icon drop down, change copy from Türk to Türkiye

## 2) Link change in footer 
The footer on the [map site](https://prd.fb84e0f7529f2737.openapparel.org/) has a Github icon that currently isn't linking to anything. The icon should link to: 
https://github.com/opensupplyhub/pyoshub 

## 3) Changes on [Contribute page](https://prd.fb84e0f7529f2737.openapparel.org/contribute)
On this page: https://prd.fb84e0f7529f2737.openapparel.org/contribute
Update "Step by step instructions" to link to: https://info.opensupplyhub.org/resources/preparing-data 

## 4) My [Lists page](https://prd.fb84e0f7529f2737.openapparel.org/lists)
On the My Lists page, change "processed and matched" to link to https://info.opensupplyhub.org/resources/a-free-universal-id-matching-algorithm 

## 5) On the [Settings page](https://prd.fb84e0f7529f2737.openapparel.org/settings) 
On the Settings page, update copy from “Terms of Use” to “Terms of Service” 

## 6) [Processing complete email](https://docs.google.com/document/d/1CAcO9Zdgrl3ZTk8xb7HhHC2-pAXxL9gfXjAdMju7pdY/edit?usp=sharing) 
In this email, update "Check out this guide" to https://info.opensupplyhub.org/resources/uploading-to-open-supply-hub

**Comment by obrienad** [comment]
CAN until Mariel confirms it's exhaustive.
