### ISSUE TITLE
Reduce OAR staging and production ECS task count

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2307]
OAR production is only serving read-only traffic to legacy embedded maps
OAR staging  is only serving read-only traffic

Recommend reducing the desired task count in both tfvars files to `8`, manually editing the services through the console to run 8 tasks  and monitoring production latency to see if `8` is sufficient.

**Comment by jwalgran** [comment]
Labeled client action needed to get approval for this task.

**Comment by obrienad** [comment]
CAN pending 2/1 sprintly meeting with OSH

**Comment by mariel-oar** [comment]
@jwalgran @obrienad , given that this could significantly help our AWS cost, I'd like to up the priority. @jwalgran , can you take a screen cast of how you do this instead of scheduling paired time?

**Comment by obrienad** [comment]
Mariel confirmed OS Hub sorted this.
