### ISSUE TITLE
Password reset links use http rather than https on staging

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#231]
## Overview

Password reset links use `http://` rather than `https://` on staging. There is a redirect in place, so these links are not broken, but we want to avoid sending authentication related requests in the clear.

### Expected Behavior

URLs in password reset email use the `https://` protocol.

### Actual Behavior

URLs in password reset email use the `http://` protocol.

### Steps to Reproduce

* Ensure you have a registered account with an email account you can check.
* Log out.
* Request a password reset email.

### Demo

<img width="922" alt="screen shot 2019-02-25 at 4 43 57 pm" src="https://user-images.githubusercontent.com/17363/53376757-b597c200-391c-11e9-9350-98c012958648.png">

**Comment by kellyi** [comment]
Shares points with #97
