### ISSUE TITLE
Copy / UX Updates - November 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2310]
**NOTE** This small text change should be included in a PR for another issue in the same epic

## 1) Preview text references "global apparel facilities" - see screen shot below: 
The ask is that copy be updated to remove the apparel reference. 

![Screen Shot 2022-11-17 at 11.26.29 AM.png](https://images.zenhubusercontent.com/61f9cafd1f9027ce23332739/a4be0246-935f-42a7-914c-bd729daf9f5b)

UPDATED COPY: 
Open Supply Hub (OS Hub) is an accessible, collaborative, supply chain mapping platform, used and populated by stakeholders across sectors and supply chains.

## 2) ~TBD - Remove Twitter icon~ In a comment below we decided that this is being kept

**Comment by jwalgran** [comment]
@mariel-oar I labeled this client action needed for 2 reasons

- For the "Add banner" task
  -  On what domain do we want to add the banner and under what conditions
  - There are placeholders in the description for copy and style guidance but they are currently empty
- For te Twitter tasks we will wait for the TBD to be resolved

**Comment by mariel-oar** [comment]
@katieashaw, please update the requirements above (the TBDs) with banner copy, color, and font details, as well as a decision on Twitter.

**Comment by obrienad** [comment]
@jwalgran - Katie asked: can this text be added to the existing black banner on Production, that is currently used for the Google Translate dropdown functionality?

**Comment by vrwOAR** [comment]
@obrienad & @jwalgran - twitter button will remain up on the site. Thanks, V.

**Comment by jwalgran** [comment]
@katieashaw in response to your question I did a quick mock up of what showing the banner message in the google translate menu area could look like at a mobile width
<img width="451" alt="Screen Shot 2022-11-22 at 9 43 11 AM" src="https://user-images.githubusercontent.com/17363/203372205-462a9311-b858-4317-8f18-2a31e0261054.png">

**Comment by katieashaw** [comment]
Thank you @jwalgran ! Great to know that this is possible. I also think it will look even cleaner than this, as the copy is pretty short.

I'd love your thoughts on this though @hlennett

**Comment by obrienad** [comment]
@katieashaw - moved the discussion re: donation banner to its separate ticket so it's included in Release 76. @hlennett - please respond on #2317
