### ISSUE TITLE
Banner and copy update - donation campaign

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#2317]
## 2) Add a banner (like the one on [staging.openapparel.org](https://staging.openapparel.org/)) 
This banner will display persistently (as on OAR staging); it will message a donation campaign that is loosely slated to run from Nov 25 - ~Dec 31~ Jan 31 2023 (specific dates will not be referenced in the copy; but please keep in mind that we will ask that it be turned of in early January) 

Copy (with hyperlink): We’re fundraising! Help us maintain OS Hub as a free platform, accessible to all, by [donating to our campaign](https://givebutter.com/opensupplyhub2022).
Background color: Black
Text color: White 
Font and weight: Darker Grotesque font, medium weight

![Screenshot 2022-11-21 at 18.03.42.png](https://images.zenhubusercontent.com/6228ec40c8dbf82201006213/a497b16a-946b-40b8-b4ab-b81444cea7e7)

**Comment by obrienad** [comment]
<img width="451" alt="Screen Shot 2022-11-22 at 9 43 11 AM" src="https://user-images.githubusercontent.com/17363/203372205-462a9311-b858-4317-8f18-2a31e0261054.png">

**Comment by obrienad** [comment]
@katieashaw - we created a new ticket per Vanessa's guidance. tagging @hlennett for her feedback.

**Comment by vrwOAR** [comment]
Updated Copy & styling (with hyperlink): We’re fundraising! Help us maintain OS Hub as a free platform, accessible to all, by [donating to our campaign](https://givebutter.com/opensupplyhub2022).
Background color: Black
Font: Darker Grotesque font, medium weight
Color: #FCCF3F
Alignment: Centered
Location: Persistent banner with the Google translate dropdown.

**Comment by jwalgran** [comment]
@vrwOAR I have just opened pull request #2318 that includes screenshots of the new banner with content and styling matching the commend above (https://github.com/open-apparel-registry/open-apparel-registry/issues/2317#issuecomment-1324079431)

**Comment by jwalgran** [comment]
From @vrwOAR 
> The banner can have an end date of Jan 31, 2023.
