### ISSUE TITLE
List approval workflow status updates are needed. Rejected lists to become "inactive". Replaced lists to become "rejected".

### ISSUE THREAD

**Issue by vrwOAR** [open-apparel-registry/open-apparel-registry#2326]
## Overview

In the new upload workflow, contributor lists are reviewed by OS Hub team. When [rejected](https://opensupplyhub.org/lists/2035), the list will stop progressing through the workflow and a rejection message is delivered to the contributor. Though rejected, the lists are maintaining their active status in the [list source dashboard](https://opensupplyhub.org/admin/api/source/406807/change/?_changelist_filters=contributor__id__exact%3D194) and thus remain on the [front end as an available list](https://opensupplyhub.org/profile/195?q=Akh%20Eco%20Apparels%20Ltd) for said contributor. The list details (list name and description) are available, however, the [facilities and all corresponding facility data points](https://opensupplyhub.org/facilities/?contributors=194&lists=2035) are not available; as the list was rejected prior to geocoding and matching.

Also, as a part of the upload process, a user has historically had the option to replace a previously uploaded list. Lists uploaded to OS Hub that are replaced with a new upload are being made inactive. However, their status within the Django facility list details remains as “Pending”. Therefore the list remains visible within both the OS Hub Dashboard & the user’s dashboard as a pending list awaiting inputs from the OS Hub admin. 

### Expected Behavior

- When a list is rejected during the list approval process the list should also be made inactive in the list source dashboard.
- When a list uploaded to OS Hub is replaced by the user, the status should be updated to “inactive” and “rejected”. It is not necessary to send the rejected notification to the user for this use case, as they have already replaced the list with another upload for processing. 

### Actual Behavior

- Though rejected, the lists are maintaining their "active" status in the [list source dashboard](https://opensupplyhub.org/admin/api/source/406807/change/?_changelist_filters=contributor__id__exact%3D194) and thus remain on the [front end as an available list](https://opensupplyhub.org/profile/195?q=Akh%20Eco%20Apparels%20Ltd) for said contributor.
- Replaced lists are retaining the "pending" status in the change facility list dashboard. Example, [Mammut Sports Group - Mammut Sports Group AG Supplier List 2022](https://opensupplyhub.org/admin/api/facilitylist/2215/change/)

### Steps to Reproduce

Rejected List items:
- Log-in to [OS hub admin dashboard](https://opensupplyhub.org/dashboard)
- navigate to desired list from [rejected list](https://opensupplyhub.org/dashboard/lists/?status=REJECTED)
- select [list](https://opensupplyhub.org/lists/2035) & verify rejected status
- visit [Django admin](https://opensupplyhub.org/admin/) 
- [Sources](https://opensupplyhub.org/admin/api/source/) 
- search contributor ([Next PLC](https://opensupplyhub.org/admin/api/source/?contributor__id__exact=194))
- select desired list ([Next Plc (NEXT Tier 1 and Tier 2 Factory List September 2022) (406807)](https://opensupplyhub.org/admin/api/source/406807/change/?_changelist_filters=contributor__id__exact%3D194)) & verify active list status

Inactive Pending List items:
- Log-in to [OS hub admin dashboard](https://opensupplyhub.org/dashboard)
- navigate to desired list from [pending list](https://opensupplyhub.org/dashboard/lists/?rowsPerPage=100)
- select [list](https://opensupplyhub.org/lists/2215) & verify inactive status
- visit [Django admin](https://opensupplyhub.org/admin/) 
- [Sources](https://opensupplyhub.org/admin/api/source/) 
- search contributor - [Mammut](https://opensupplyhub.org/admin/api/source/?contributor__id__exact=337)
- select desired list - [Mammut Sports Group (Mammut Sports Group AG Supplier List 2022) (468155)](https://opensupplyhub.org/admin/api/source/468155/change/?_changelist_filters=contributor__id__exact%3D337) & verify inactive list status
- Verify pending status in [Django admin](https://opensupplyhub.org/admin/api/facilitylist/)
- select desired list - [Mammut Sports Group (Mammut Sports Group AG Supplier List 2022) (468155)](https://opensupplyhub.org/admin/api/facilitylist/2215/change/)
- Review list status: PENDING
- Mac M1, Opera GX browser

### Demo

From staging, here is the view as a user with an upload & replacement:
- [Stitch Fix test](https://staging.opensupplyhub.org/lists/1857) was replaced by [replace test](https://staging.opensupplyhub.org/lists/1870)

### Additional context

**Rejection error**: Is occurring with all rejected lists, however, most have been manually updated to reflect accurate records on the platform's front-end. These are the rejected lists currently displaying the error:
- [Next Plc (NEXT Tier 1 and Tier 2 Factory List September 2022) (406807)](https://opensupplyhub.org/lists/2035) 
- [Baoding Tianxing Garment Co.ltd](https://opensupplyhub.org/lists/2294)
- [Dafiti Facility List Jan 2023](https://opensupplyhub.org/lists/2299)
- [Brixon ( Jiangmen) Manufactoring Co Ltd Facility List January 2023](https://opensupplyhub.org/lists/2304)
- [WU LUEN KNITTING CO.,LTD](https://opensupplyhub.org/lists/2306)
- [Dafiti Facility List Jan 2023](https://opensupplyhub.org/lists/2310)
- [UNIQUE WASHING & DYEING LTD](https://opensupplyhub.org/lists/2319)
- [CTT TEKSTIL TURIZM INS. SAN. TIC. LTD. STI.](https://opensupplyhub.org/lists/2320)

**Replaced Lists**: Replaced lists that should be updated to a status of “rejected”:
- [OS_Hub_Data_Template_adidas_Primary Suppliers_Oct 2022](https://opensupplyhub.org/lists/2019)
- [adidas_Licensee Suppliers_Oct 2022](https://opensupplyhub.org/lists/2020)
- [adidas_Wet Process Suppliers_Oct 2022](https://opensupplyhub.org/lists/2021)
- [ASOS Factory List June 2022](https://opensupplyhub.org/lists/2052)
- [Fair Trade Certified Factory List](https://opensupplyhub.org/lists/2055)
- [Nordstrom July 2022 Supplier List](https://opensupplyhub.org/lists/2076)
- [OAR_Contributor_EmbeddedList_Tier1_final](https://opensupplyhub.org/lists/2131)
- [Columbia Sportswear Company Facility list November 2022](https://opensupplyhub.org/lists/2135)
- [Columbia Sportswear Facility List November 2022](https://opensupplyhub.org/lists/2136)
- [Mountain Hardwear Facility List November 2022](https://opensupplyhub.org/lists/2137)
- [SOREL Facility List November 2022](https://opensupplyhub.org/lists/2138)
- [prAna Facility list November 2022](https://opensupplyhub.org/lists/2139)
- [Tier 1 suppliers November 2022](https://opensupplyhub.org/lists/2160)
- [Wertchemie_2022](https://opensupplyhub.org/lists/2162)
- [Cipo Tekstil Sanayi ve Ticaret A.S.](https://opensupplyhub.org/lists/2163)
- [WE Fashion Supplier list 2022-2023](https://opensupplyhub.org/lists/2171)
- [New Look Tier 1 Factory List November 2022](https://opensupplyhub.org/lists/2172)
- [New Look Beyond Tier 1 Factory List November 2022](https://opensupplyhub.org/lists/2173)
- [Bank & Vogue Ltd ( BVH )](https://opensupplyhub.org/lists/2175)
- [Fruit of the Loom Factory List November 2022](https://opensupplyhub.org/lists/2178)
- [Levi Strauss & Co. Factory List Q4 2022](https://opensupplyhub.org/lists/2179)
- [ZALORA Private Label Tier 1 Factory List October 2022](https://opensupplyhub.org/lists/2181)
- [VF Corporation Factory List (FY'23Q2)](https://opensupplyhub.org/lists/2187)
- [Fair Wear Dec 2022](https://opensupplyhub.org/lists/2188)
- [Levi Strauss & Co. Factory List Q4 2022](https://opensupplyhub.org/lists/2189)
- [Fairtrade Facility List Nov & Dec 2022](https://opensupplyhub.org/lists/2192)
- [Tesco Clothing and Home Textile Facility List August 2022](https://opensupplyhub.org/lists/2204)
- [Mammut Sports Group AG Supplier List 2022](https://opensupplyhub.org/lists/2206)
- [Mammut Sports Group AG Supplier List 2022](https://opensupplyhub.org/lists/2215)
- [Mark Designers Ltd.](https://opensupplyhub.org/lists/2218)
- [Mark Wear Limited](https://opensupplyhub.org/lists/2219)
- [Mark 2000 Ltd.](https://opensupplyhub.org/lists/2220)
- [Stage 2 Desigual Facility List November 2022](https://opensupplyhub.org/lists/2226)
- [Zalando Private Labels Supplier List Nov 2022](https://opensupplyhub.org/lists/2227)
- [april sourcing pvt ltd](https://opensupplyhub.org/lists/2229)
- [DİSSA TEKSTİL YIKAMA İNŞ.SAN.TİC.LTD.ŞTİ](https://opensupplyhub.org/lists/2230)
- [Outerstuff LLC 12-27-22 Version](https://opensupplyhub.org/lists/2263)
- [ALDI SOUTH Group Facility List October 2022](https://opensupplyhub.org/lists/2265)

**Comment by obrienad** [comment]
@mariel-oar removed CAN tag because you greenlit it.

**Comment by vrwOAR** [comment]
@obrienad we're going to add an element to this ticket. Replaced lists are deactivated when the user uploads the new list, however, they aren't being processed as a rejection and thus hang in the pending status as a list awaiting an OS Hub response. I'll flush out the elements this afternoon.

**Comment by vrwOAR** [comment]
@obrienad, here's the updates to the ticket:
  
**Overview:** As a part of the upload process, a user has historically had the option to replace a previously uploaded list. Lists uploaded to OS Hub that are replaced with a new upload are being made inactive. However, their status within the Django facility list details remains as “Pending”. Therefore the list remains visible within both the OS Hub Dashboard & the user’s dashboard as a pending list awaiting inputs from the OS Hub admin. 

**Expected Behavior:** When a list previously uploaded to OS Hub is replaced by the user, the status should be updated to “inactive” and “rejected”. It is not necessary to send the rejected notification to the user for this use case, as they have already replaced the list with another upload that is being processed. 

**Additional Context:** Current list of replaced lists that should be updated to a status of “rejected”:

- [OS_Hub_Data_Template_adidas_Primary Suppliers_Oct 2022](https://opensupplyhub.org/lists/2019)
- [adidas_Licensee Suppliers_Oct 2022](https://opensupplyhub.org/lists/2020)
- [adidas_Wet Process Suppliers_Oct 2022](https://opensupplyhub.org/lists/2021)
- [ASOS Factory List June 2022](https://opensupplyhub.org/lists/2052)
- [Fair Trade Certified Factory List](https://opensupplyhub.org/lists/2055)
- [Nordstrom July 2022 Supplier List](https://opensupplyhub.org/lists/2076)
- [OAR_Contributor_EmbeddedList_Tier1_final](https://opensupplyhub.org/lists/2131)
- [Columbia Sportswear Company Facility list November 2022](https://opensupplyhub.org/lists/2135)
- [Columbia Sportswear Facility List November 2022](https://opensupplyhub.org/lists/2136)
- [Mountain Hardwear Facility List November 2022](https://opensupplyhub.org/lists/2137)
- [SOREL Facility List November 2022](https://opensupplyhub.org/lists/2138)
- [prAna Facility list November 2022](https://opensupplyhub.org/lists/2139)
- [Tier 1 suppliers November 2022](https://opensupplyhub.org/lists/2160)
- [Wertchemie_2022](https://opensupplyhub.org/lists/2162)
- [Cipo Tekstil Sanayi ve Ticaret A.S.](https://opensupplyhub.org/lists/2163)
- [WE Fashion Supplier list 2022-2023](https://opensupplyhub.org/lists/2171)
- [New Look Tier 1 Factory List November 2022](https://opensupplyhub.org/lists/2172)
- [New Look Beyond Tier 1 Factory List November 2022](https://opensupplyhub.org/lists/2173)
- [Bank & Vogue Ltd ( BVH )](https://opensupplyhub.org/lists/2175)
- [Fruit of the Loom Factory List November 2022](https://opensupplyhub.org/lists/2178)
- [Levi Strauss & Co. Factory List Q4 2022](https://opensupplyhub.org/lists/2179)
- [ZALORA Private Label Tier 1 Factory List October 2022](https://opensupplyhub.org/lists/2181)
- [VF Corporation Factory List (FY'23Q2)](https://opensupplyhub.org/lists/2187)
- [Fair Wear Dec 2022](https://opensupplyhub.org/lists/2188)
- [Levi Strauss & Co. Factory List Q4 2022](https://opensupplyhub.org/lists/2189)
- [Fairtrade Facility List Nov & Dec 2022](https://opensupplyhub.org/lists/2192)
- [Tesco Clothing and Home Textile Facility List August 2022](https://opensupplyhub.org/lists/2204)
- [Mammut Sports Group AG Supplier List 2022](https://opensupplyhub.org/lists/2206)
- [Mammut Sports Group AG Supplier List 2022](https://opensupplyhub.org/lists/2215)
- [Mark Designers Ltd.](https://opensupplyhub.org/lists/2218)
- [Mark Wear Limited](https://opensupplyhub.org/lists/2219)
- [Mark 2000 Ltd.](https://opensupplyhub.org/lists/2220)
- [Stage 2 Desigual Facility List November 2022](https://opensupplyhub.org/lists/2226)
- [Zalando Private Labels Supplier List Nov 2022](https://opensupplyhub.org/lists/2227)
- [april sourcing pvt ltd](https://opensupplyhub.org/lists/2229)
- [DİSSA TEKSTİL YIKAMA İNŞ.SAN.TİC.LTD.ŞTİ](https://opensupplyhub.org/lists/2230)
- [Outerstuff LLC 12-27-22 Version](https://opensupplyhub.org/lists/2263)
- [ALDI SOUTH Group Facility List October 2022](https://opensupplyhub.org/lists/2265)

From staging, here is the view as a user with an upload & replacement:
- [Stitch Fix test](https://staging.opensupplyhub.org/lists/1857) was replaced by [replace test](https://staging.opensupplyhub.org/lists/1870)

**Comment by obrienad** [comment]
thanks, @vrwOAR - is the update meant to replace the body of the original issue? Or be in addition to it? If so, I'll delete the original to avoid confusion / conflicting info.

**Comment by mariel-oar** [comment]
@obrienad , Vanessa is calling out that there is a second, slightly nuanced case where this list-not-being-rejected behavior happens : (1) when a pending list is rejected, it needs to rejected on the list's source page as well so that it does not show up on the front end and (2) when a pending list gets replaced by a user (before it is approved or rejected by OS Hub), the list needs to go into inactive _and rejected_ status - right now it is only going into inactive. In the second case, the reject email does not need to be sent because the user is essentially rejecting their own list. 

(1) is captured in original ticket stop; (2) was not captured in the original ticket, but is very closely related to it. 

We will update the original ticket to include both. @vrwOAR, do you mind doing that? It would be good to keep the lists of lists separate for the two use cases at the bottom in the extra context section.

**Comment by vrwOAR** [comment]
@obrienad & @mariel-oar, I've updated the ticket.

**Comment by jwalgran** [comment]
Thanks for the update. I would like to discuss at an upcoming check in meeting our options for updating workflow status. I would like to find a way to fix the moderation workflow while reserving the "rejected" status for lists that were never processed and use another method or designation for old lists that have been replaced.

**Comment by jwalgran** [comment]
In our check-in we agreed to use a distinct status rather than setting previous lists to rejected (either a "real" REPLACED status or a meta status based on the existing replacement tracking)

We need to make sure that in both the moderation UI and the public UI show the active, non-replaced lists.
