### ISSUE TITLE
Embedded Map CSV/Excel Downloads

### ISSUE THREAD

**Issue by hlennett** [open-apparel-registry/open-apparel-registry#2329]
There are two behaviors that we'd like to fix in Embedded Map downloads:

1. The order of the fields in the CSV/Excel download should match the order of the fields configured in Embedded Map settings. 
2. There should only be one line per facility in the download, showing the active data from the contributor for that facility. There should not be additional rows with inactive data points from that contributor. The idea is that a user can come and download the list of facilities from an embedded map and only see each facility entered once with all the datapoints the contributor submitted in that row. 

cc @mariel-oar @vrwOAR

**Comment by hlennett** [comment]
Dropping in some feedback from another user on why the second point in this ticket is important to resolve:

_As I said below, I was able to use the facilities report run from the Embedded Map to import the OSH IDs back into Salesforce. However, I got stuck when trying to import the longitude and latitude data back in. Long story short, Salesforce won’t let you import these two columns into the one field in Salesforce via its internal Import Data Wizard, so you have to use something called Dataloader.io instead. While Salesforce will let you import data using a non-Salesforce source field (the OSH ID for example), Dataloader.io won’t let you. It requires you to use the Salesforce ID as the source field.

Now, this is where I got stuck, because the format of the facilities report run from the Embedded Map is a bit strange. Please see attached.

As you can see, for each facility there are up to 5 rows and the data for each field isn’t filled in on every row. Our Salesforce ID (factory: id) only appears in one of the rows. Luckily, the OSH ID (os_id) appears in every row (which is why I was able to import the OSH ID back into Salesforce). But the longitude and latitude data only appears on the first row and not on the same row as the Salesforce ID.

Do you know why the Excel is formatted like this? Is there something we can change in the OSH so we can run a report with only one row per facility? I don’t want to start moving data around within the Excel, that is way too risky and/or time consuming._

**Comment by jwalgran** [comment]
Thank you for including the additional feedback.

Item 2. in the issue description overlaps with #2135, which is in progress.

**Comment by mariel-oar** [comment]
great news, thank you for confirming @jwalgran

**Comment by mariel-oar** [comment]
Merged, closed
