### ISSUE TITLE
cipublish step of the Jenkins CI build failing with UnrecognizedClientException on GetAuthorizationToken

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2341]
An excerpt from a failing CI build log. Two consecutive builds of `ogr/develop` failed with this error.

```
[Pipeline] stage
[Pipeline] { (cipublish)
[Pipeline] withCredentials
Masking supported pattern matches of $OAR_AWS_ECR_ENDPOINT
[Pipeline] {
[Pipeline] wrap
[Pipeline] {
[Pipeline] sh
+ ./scripts/cipublish

An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.
Must provide --username with --password-stdin
[Pipeline] }
```

**Comment by BryanQuigley** [comment]
We disabled a bunch of the AWS cert used for CI until they could be cleared.

**Comment by jwalgran** [comment]
@BryanQuigley Checking in on this to confirm that the certs were reenabled and we can close this issue.

**Comment by BryanQuigley** [comment]
They have not been.  It's likely a better idea to just generate a new access key.  Thoughts?

**Comment by jwalgran** [comment]
Yes to generating new keys to get the builds back up and running

**Comment by jwalgran** [comment]
I created a new set of keys and updated the CI configuration. I then reran a previously failing build/deploy job and it succeeded.
