### ISSUE TITLE
Close staging.openapparel.org & origin.openapparel.org

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2344]
With the goal of reducing hosting costs and minimizing complexity of our acounts, we would like to close the following sites: 

staging.openapparel.org
origin.openapparel.org (this is only accessible via incognito window, apparently, but shows up in Google search results)

**Comment by obrienad** [comment]
Tagged CAN pending 2/1 sprintly meeting with OSH

**Comment by mariel-oar** [comment]
@obrienad, this is closed?

**Comment by obrienad** [comment]
The epic lived in the backlog, but yes this issues have been closed.
