### ISSUE TITLE
Update email copy & send list status emails from data@opensupplyhub.org

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2345]
Requirements of this ticket: 
1. update the email that communications about a contributor's data arrive from 
2. update the copy of the reject email 
3. Update reference to info@ email address in facility closure workflow to be data@opensupplyhub.org email address 

### 1) Update email address: 
A new email account has been created to communicate with users about their data. That email address is: data@opensupplyhub.org. 

As such, we would like the following emails to come from data@opensupplyhub.org: 
- Processing complete (facility_list_complete_..)
- List rejected (facility_list_rejection_..)
- Facility claim emails (facility_claim_.. and claim_facility_..)

### 2) Update email copy: 
Additionally, the content for the automated part of the reject message has been updated (part of the content of the reject message comes from a text popup box that OS Hub team members can write in when a list if rejected). The updated copy for that message can be found here: 
https://docs.google.com/document/d/1geS6hCl-DJEVFZ3JJ3I9ZW_6TsdmRxgeYqWKHF9B7Yo/edit?usp=sharing

### 3) Update email reference in facility closure workflow 
When a user clicks on the "Report" button on a facility profile, then on "Report as Closed", a popup window opens that references the info@opensupplyhub.org email. This reference should be updated to be data@opensupplyhub.org

**Comment by mariel-oar** [comment]
note to self: we need to update the copy in the processing compelte email to use the data@osh email instead of info@osh

**Comment by jwalgran** [comment]
@mariel-oar Do we want all automated emails to come from data@ or just the two mentioned 

- Processing complete
- List rejected

**Comment by mariel-oar** [comment]
Do you have a list of auto generated emails handy? Those two specifically do need to come from data@ because they deal with the list approval workflow, but maybe there are others involved in that workflow we are missing... we don't want password resets, account authentication, etc emails to come from data@

**Comment by jwalgran** [comment]
That last sentence actually covers what we need to know.

>we don't want password resets, account authentication, etc emails to come from data@

We will create an separate from address configuration for these workflow emails.

As to a list of generated emails, all of our email templates are stored here so the contents of this folder is a good reference.

https://github.com/open-apparel-registry/open-apparel-registry/tree/ee0bd3a89a6ddb41c78c97c2356950142a72ffc8/src/django/api/templates/mail

**Comment by mariel-oar** [comment]
thanks @jwalgran , we want all of the facility claim emails to come from data@ as well...
updating the list above

**Comment by obrienad** [comment]
@jwalgran - Mariel updated the original scope to include updating copy in the reject message and swapping the email that comes up on the closure form.

**Comment by mariel-oar** [comment]
@jwalgran , when i go through the closure report, info@osh is still referenced.

This is in the email that gets sent to the contirbutor:
<img width="843" alt="Screenshot 2023-03-22 at 2 44 12 PM" src="https://user-images.githubusercontent.com/97469356/227006043-98644e95-d8b3-4a8e-9edb-f3435e5e5a92.png">

Can the email in this message be updated to [data@opensupplyhub.org](mailto:data@opensupplyhub.org)?

**Comment by vrwOAR** [comment]
@jwalgran - 3rd screen of the facility claim form, the text for additional documentation mentions @ info inbox, "If you do not have a website or LinkedIn page for your facility, or if those pages do not list the address of the facility you wish to claim, please email **info@opensupplyhub.org** with documentation confirming the address of your facility, to assist the OS Hub team in verifying your claim."

![image.png](https://images.zenhubusercontent.com/6228f221c8dbf8795600b510/4fcb9cf2-1ee1-4057-a878-85268e4938a5)

**Comment by jwalgran** [comment]
Thanks, @vrwOAR. I updated the email address on the claim form.

<img width="750" alt="Screenshot 2023-03-23 at 7 54 41 AM" src="https://user-images.githubusercontent.com/17363/227244599-82c29364-fd31-4dc1-a719-9acb8e6c7a53.png">

**Comment by vrwOAR** [comment]
Great. Thanks @jwalgran  My other tests were all clear. Good to proceed.
