### ISSUE TITLE
Remove origin.{domain} from Google index

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2350]
This was done for the staging domain in #2255. Repeat this for both origin.openapparelregistry and origin.opensupplyhub

**Comment by mariel-oar** [comment]
Justin, i'd like to include this in a demo when we talk about account management generally...i think i'm close to being label to remove this myself through our google search console, but it's saying that origin.openapparel.org is "URL not in property" - the property being openapparel.org 

<img width="535" alt="Screen Shot 2023-01-18 at 5 03 16 PM" src="https://user-images.githubusercontent.com/97469356/213305210-933f5e60-d356-4d7a-9dd7-6e73e1f2416e.png">
