### ISSUE TITLE
Remove donate banner 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2355]
There is a donate banner currently displayed at the top of all OS Hub pages. We would like to remove this banner. 

<img width="1357" alt="Screen Shot 2023-01-18 at 4 57 55 PM" src="https://user-images.githubusercontent.com/97469356/213304429-f2472747-03ec-4c06-877b-94d2ccca1353.png">

**Comment by jwalgran** [comment]
When initially created in the bander was set with an expiration date of Jan 31. Do we need to remove the banner before the end of the month?

https://github.com/open-apparel-registry/open-apparel-registry/blob/ee0bd3a89a6ddb41c78c97c2356950142a72ffc8/src/app/src/components/Navbar/NavbarQ42022Banner.jsx#L5

**Comment by obrienad** [comment]
@mariel-oar the banner will automatically go away on the expiration date and does not require any dev time.

**Comment by mariel-oar** [comment]
ah, great!

**Comment by mariel-oar** [comment]
@obrienad, do you know what the expiration date is? We actually want to keep it active for the year.

**Comment by obrienad** [comment]
@mariel-oar Justin noted the banner is currently set to automatically turn-off on 1/31. I'm confused by your request to keep it active this year, given that the ticket is about removing the banner.

**Comment by mariel-oar** [comment]
@obrienad, sorry - some conversations going on in real time about this one...Confirming that we are removing it, leaving the 1/31 expiration date is great. Closing ticket.
