### ISSUE TITLE
Google Maps Javascript API retired version warning

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2356]
> "Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version"

The above was seen in a the telemetry section of a Rollbar item

We specify the Google Maps API version here

https://github.com/open-apparel-registry/open-apparel-registry/blob/ee0bd3a89a6ddb41c78c97c2356950142a72ffc8/src/app/src/components/VectorTileFacilitiesMap.jsx#L135-L146

According to  https://developers.google.com/maps/documentation/javascript/versions at the time of writing this issue

<img width="781" alt="Screenshot 2023-01-19 at 11 20 25 AM" src="https://user-images.githubusercontent.com/17363/213527989-41ce1165-b3e0-4c97-b60b-8ab374802195.png">

**Comment by jwalgran** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2356?planning-poker) with Zenhub @TaiWilkin

**Comment by TaiWilkin** [comment]
Note that this is related to https://github.com/open-apparel-registry/open-apparel-registry/pull/1658. The base map was broken on version 3.48.1a, so we downgraded to 3.47, so we'll probably need to debug and update code as part of this.

**Comment by obrienad** [comment]
@mariel-oar - FYI that this is a time-sensitive issue that will need to be complete before Google releases the next version mid-February.

**Comment by mariel-oar** [comment]
Thanks @obrienad , can we discuss during check-in next week? This would be a good opportunity for us to learn how these upgrades are handled on the backend. @KlausGPaul

**Comment by KlausGPaul** [comment]
Trialled it locally using the dockerized environment. Changed 
```
<ReactLeafletGoogleLayer 
     googleMapsLoaderConf={{ 
         KEY: GOOGLE_CLIENT_SIDE_API_KEY, 
         REGION: countryCode, 
         VERSION: 3.47, 
 ```
 to
 ```
 <ReactLeafletGoogleLayer 
     googleMapsLoaderConf={{ 
         KEY: GOOGLE_CLIENT_SIDE_API_KEY, 
         REGION: countryCode, 
         VERSION: "3.50",
```
(note the double quotes to prevent the code formatter to change it back to 3.5) and it worked without any issues locally.

**Comment by mariel-oar** [comment]
Attaching screen recording in case the linter is the issue...

https://images.zenhubusercontent.com/159699912/139a6168-293a-422e-8d60-8f0c841c449a/screen_recording_2023_02_03_at_14_21_34.mov
