### ISSUE TITLE
Shut down OAR Embedded Maps 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2358]
## Overview 
Some Embedded Maps customers are still using the OAR style EM. To consolidate services, we are migrating everyone over to the OS Hub style EMs by the end of February. At that point, we will be ready to shut down the service supporting OAR EMs. 

### Expected Behavior 
- Support for the OAR EM endpoint is disabled 
- All traffic to OAR EMs is routed to OS Hub EMs

### Technical Implementation

- [x] Create a new CloudFront Function based on the existing function but redirecting all traffic
        - Switch the OAR production CloudFront distribution default behavior to use this new function
        - Delete the old, now unused CloudFront functions.
- [x] Stop all the OAR production ECS tasks
- [x] Stop the OAR production database and set a reminder to ensure that I repeatedly stop it each week until we destroy it and the other OAR AWS resources
- [x] Disable  the ClousWatch alarms for the shut down resources.

**Comment by mariel-oar** [comment]
CAN label on this because we will need to confirm that everyone is transitioned to the OS Hub style EM.

**Comment by obrienad** [comment]
To be updated 3/1

**Comment by obrienad** [comment]
@mariel-oar - moved this to backlog since it's not actionable ATM!

**Comment by mariel-oar** [comment]
Removing CAN. We were waiting until the end of February to convert everyone to the OS Hub style maps and that has been completed / users have been given sufficient notice. 

It would be great if we could get this scheduled in the next sprint.

**Comment by obrienad** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2358?planning-poker) with Zenhub @jwalgran @mstone121 @TaiWilkin
