### ISSUE TITLE
IndexError: list index out of range raised when downlaoding from embeded map and header does not match data fields

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2369]
## Overview

`IndexError: list index out of range` raised when downloading from embedded map and header does not match data fields

### Steps to Reproduce

**NOTE Make sure to close the tab after testing this to prevent looping requests ( #2368)**

* Browse https://opensupplyhub.org/facilities?contributors=25&embed=1
* Download

### Demo

In this screenshot note the discrepancy in length between `data_values` and `list_fields`. The code expects these to be the same length with fields in the same order.

<img width="601" alt="Screenshot 2023-02-20 at 12 47 46 PM" src="https://user-images.githubusercontent.com/17363/220188078-07f3b5bd-7c6f-4882-bb4e-83d7cf8a09a7.png">

### Additional context

https://rollbar.com/OpenApparelRegistry/OpenSupplyHub/items/218/

**Comment by jwalgran** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2369?planning-poker) with Zenhub @mstone121

**Comment by jwalgran** [comment]
@mariel-oar labeled client action needed to get your approval for fixing this bug. I would classify this as relatively high priority because it results in embedded map downloads that appear to never finish and is the root cause behind #2368

**Comment by mariel-oar** [comment]
Yes, please fix this @jwalgran...removing CAN
