### ISSUE TITLE
Take a final RDS snapshot and destroy OAR production resources

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2376]
This will require a different set of steps then the staging destroy (#2351) since we need to leave the DNS/CloudFront/certificate setup in place to handle the redirect until we can migrate those resources to the OSH deployment.
- [x] Remove all resources from .tf files other than those required for DNS/CloudFront/certificate
- [x] Run a production `./scripts/infra plan` and verify the output is expected and that the resources needed for the redirect remain in place
- [x] Create an RDS snapshot
- [x] Enable deletion protection on both OS Hub RDS instances via the console (for extra confidence)
- [x] Use `./scripts/infra apply` to destroy the resources

**Comment by jwalgran** [comment]
I updated the description since, unlike staging, there are a few non-compute resources we want to leave in place to handle the old domain name and redirection.
