### ISSUE TITLE
Move channel integrations to new Slack

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#2387]
We need these through the end of May, but now long term. Move them as efficiently as possible.

- [ ] Rollbar
- [ ] Jenkins
- [ ] Github
- [ ] SQS emails

**Comment by jwalgran** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2387?planning-poker) with Zenhub @nanotubing @TaiWilkin

**Comment by nanotubing** [comment]
adding this as a reminder for when it comes time to integrate the jenkins slack plugin
https://github.com/open-apparel-registry/open-apparel-registry/issues/2027#issuecomment-12109872252027

> We do not use this plugin, we use the one written by jenkins, but that plugin uses the API key created when enabling the slack version, so it needs to be turned on, even if it's not being used. I've re-enabled this integration, and directed it to a channel used by the operations team.

**Comment by jwalgran** [comment]
@obrienad Flagging this as an interesting timing challenge. I am not sure when we will be shutting down the old Slack, but it  may be sooner than 60 days from now. In the interest of time we may want to not migrate them and emphasize that the OS Hub team should set them up on their Slack and forward important notifications to us.

**Comment by obrienad** [comment]
Great point. Will add it to Wednesday's check-in.

**Comment by jwalgran** [comment]
It is likely that we will shut off the old Slack before the end of May. Since we need to keep our visibility into the current production system through then, we want to move this over to our new Slack for that short term period as efficiently as possible.

**Comment by nanotubing** [comment]
we should plan to share the OAR channel from the Azavea slack to Element84 slack. This will allow us to keep up with app notifications without requiring an active license on both slacks. This should buy us enough time to get the customer spun up on the various monitoring systems

**Comment by jwalgran** [comment]
I changed this estimate down to a one now that the scope is reduced

**Comment by nanotubing** [comment]
The version of `#oar` from azavea's slack has been shared into the Element84 slack as `#oar-internal`, so we are now able to monitor notifications for this project as long as necessary
