### ISSUE TITLE
Answer questions about download performance and make recommendations about restoring previous download format

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2388]
**Overview:**
We would like to consider moving back to the previous download format, which was more performant than the new download format, and also addresses user issues with the new formatting. 

**User Story:** 
As a user who frequently downloads data from OS Hub, I want a way to download data that organizes information about each facility on a single row so that I can easily interpret the information I’m downloading. 

**Additional Context:** 
Our civil society and brand users are really struggling with the formatting of our CSV/Excel downloads, since we separated them out with one line per contributor. For example: 

Worker Rights Consortium. These are extremely busy civil society advocates with huge case files. They’re trying to work as efficiently as possible to match brands with facilities and tie that information to their records/databases. They are really trying to make use of our data as much as they can, but the download format is tough for them. A direct quote from them: “Attached is an excel export of “Country: Pakistan” without any modification after download. Lots of “name” and “address” fields are blank. I do understand that I could refer to the os_id and then manually insert the name and address for every entry before doing anything with the sort function. But, when handling a very large data set, the blank name and address fields do add a lot of manual labor time. See, for example, PK2022228832XVJ in this data – there are nearly 50 identical rows with no more info than “An Auditor / Certification Scheme / Service Provider (API)“

In general, some of the themes we’re hearing from users who are asking about downloads: 
- The average user doesn’t know how to interpret what they see. They just see a lot of blank lines.
- Because we have a lot of anonymized contributions, a lot of those lines just say “A Brand/Retailer” or equivalent anonymized version, so it’s a lot of not terribly useful rows to sort through. 
- It makes it difficult for a brand, for instance, to download their list from OS Hub and just have a clean list of their facilities and OS IDs that they can put into their system. They have to clean/reorder the list first.

**Questions:** 
1. is it known why performance is impacted by the new download format 
2. would you recommend reverting to the old format to address these issues? 
3. is there any low hanging fruit that could be implemented to make the new download more performant? 

**Scope:** 

Note: This was split into 2 issues for estimation purposed. The estimate on this issue only covers 1)

1) Provide response to above questions; Assuming answers to above questions are not show stoppers, proceed to 2
2) #2392

**Comment by jwalgran** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2388?planning-poker) with Zenhub @TaiWilkin

**Comment by TaiWilkin** [comment]
@jwalgran Are we estimating for 1 (provide answers to questions) or 2 (revert to previous download)?

**Comment by jwalgran** [comment]
@TaiWilkin I clarified this by creating a #2392. The estimate on this issue should just be for item "1" in the scope section

**Comment by TaiWilkin** [comment]
We have written up answers to the above question in [this document](https://docs.google.com/document/d/1VePuQKWE2THwLzogL7prcocUDPPgSWVhERH_vt5jjxU/edit?usp=sharing), which is also available in the shared Google drive.

**Comment by obrienad** [comment]
Thanks, Tai. @mariel-oar - please let me know when you've reviewed, and when you'd like to proceed with #2392
