### ISSUE TITLE
Provide select users with access to production prior to launch [NO POINTS]

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#239]
## Overview

Select brands need to have access to production prior to launch in order to upload their facility lists

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

@nataliegrillon and @katieashaw will provide a list of brands/user names that need to have access to production prior to launch in order to upload facility lists.

**Comment by katieashaw** [comment]
We certainly will - thanks @dboyer ! 😄

**Comment by jwalgran** [comment]
I added the `operations` label. To accomplish this I think we need to create a DNS entry that resolves to the production deployment that we can distribute to our select users before the full launch on the 28th. This needs to be in place on March 25th.
