### ISSUE TITLE
Update Google Maps API keys in E84 prod endpoint 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2394]
## Overview
Update the Google Maps API keys with OS Hub generated keys. 

### Additional Context

The Google Maps functionality in the platform requires a server side and client side API key. OS Hub will generate these and E84 will update the production endpoint with them. At this point, E84 will not longer need to bill OS Hub for the Google Maps usage. 

### Technical Implementation

- [ ] Update the keys in the staging and production .tfvars files
- [ ] Trigger a deployment to both environments
- [ ] Notify @mariel-oar when the keys are in place so they can be removed from the secure share

**Comment by obrienad** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Civic-Apps-5c8fabc1177a1c1f6672f901/issues/open-apparel-registry/open-apparel-registry/2394?planning-poker) with Zenhub @TaiWilkin @jwalgran

**Comment by jwalgran** [comment]
The planning poker was set to a finial estimate when I saw the notification but I agree and it is definitely a 1.

**Comment by mariel-oar** [comment]
Client / FE side key needs to be restricted by domain 
Only a deployment is necessary to make this change / i.e. no code chage

**Comment by obrienad** [comment]
Tagged as CAN given OS Hub's need to create keys

**Comment by mariel-oar** [comment]
@jwalgran , we've created the key. let me know how you would like to share. 

it's restricted to the prod and staging URLs as well as to calling: geocoding API, maps static API, and maps javascript API

**Comment by jwalgran** [comment]
If your password manager has a secure send feature you could use that. Otherwise you could put them in a new text file and upload it to the `opensupplyhub-development-config-eu-west-1` bucket.

The application currently expects two different keys

`google_server_side_api_key` - For geocoding by the backend
`google_client_side_api_key` - For the frontend Google Maps API

These need to be separate because request from the backend do not have a referring domain, so they backend key cannot have a domain restriction.

**Comment by mariel-oar** [comment]
I see, thanks @jwalgran. I will use the secure send feature and: 
- create a new key for the geocoding API (it's ok to restrict this one to just the geocoding api?) 
- remove the geocoding API permission from the client side key (so it will be restricted to just maps static API and maps javascript API

**Comment by jwalgran** [comment]
I logged into the Google Console to verify the currently configured keys.

- There are 6 total keys, a client key and a server key for each of the three environments, development, staging, and production
- The server-side keys have all 3 services enabled, however when I browse the application source code the `GOOGLE_SERVER_SIDE_API_KEY` is only used by our server-side geocoding. It is likely that only "Geocoding API" is required

<img width="263" alt="Screenshot 2023-04-20 at 10 12 36 AM" src="https://user-images.githubusercontent.com/17363/233439629-9f270ee2-d598-48f9-bfb9-2e6941772365.png">

- The  client side keys only have "Maps Javascript API" and "Maps Static API" enabled

<img width="267" alt="Screenshot 2023-04-20 at 10 12 07 AM" src="https://user-images.githubusercontent.com/17363/233439837-6af13e81-ef38-469e-b1e4-ddf4e708bb3c.png">


- The development client-side key is restricted to only work with local development urls

<img width="496" alt="Screenshot 2023-04-20 at 10 15 27 AM" src="https://user-images.githubusercontent.com/17363/233440408-26b54767-7305-451c-a94d-aca66162857b.png">

**Comment by mariel-oar** [comment]
@jwalgran , one more question - why do staging and production need to have separate API keys? (we have already created the dev environment keys on our side, so I'm assuming we do not need to create / share thes.e

**Comment by jwalgran** [comment]
In our check-in meeting we discussed that having separate keys for staging and production makes it easier to report on usage in the console and track from which environment an increase in usage/cost originated.

**Comment by jwalgran** [comment]
Mariel shared new API keys so I'm removing the client action needed label.
