### ISSUE TITLE
CI Documentation / Demo 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2395]
## Overview
User Story: As a member of the OS Hub development team, I want to make sure I understand the CI/CD process that has been used in the development of the application up to this point so that I can best support future development. 

To ensure that OS Hub team understands the deployment process set up by E84/Azavea team, the OS Hub team is requesting documentation with a review period and Q&A session.  

In particular, we would like to understand the concern about sending emails/notifications to staging users during a production deployment and why that relationship exists. Additionally, we would like to understand what Justin and team see as critical steps of the existing CI/CD process as well as tips and tricks that may address common issues.

### Describe the solution you'd like
1) Documentation enumerating the steps and summary of each 
2) A recorded demo 
3) An hour long session to ask questions to clarify content of documentation and demo vide 
4) We suggest to timebox this effort to 8 hours / 2 pts, not including the hour Q&A/discussion session; please advise on feasibility of this 

### Additional Context

- Description from Justin: Add documentation and/or train on the relationship between staging and production and how CI deployed to these environments  Recommended 1
- [gitfloe-avh](https://github.com/petervanderdoes/gitflow-avh) based branch and release management 
- Referenced in the [April/May task sheet](https://docs.google.com/document/d/1OSCPSJSAiMOCoQjlG__bCEu4RyXBDMi6sGEct2KTMXg/edit#)

**Comment by obrienad** [comment]
@jwalgran - can you provide feedback on the proposed 8 hours suggested timebox?

**Comment by jwalgran** [comment]
The 8-hour time box for this task is feasible largely because CI process is scripted and those scripts and related deployment documentation exist in the repository as a foundation.

**Comment by obrienad** [comment]
Tagged as 2 given the above.
