### ISSUE TITLE
Transfer OAR Repo to OS Hub repo 

### ISSUE THREAD

**Issue by mariel-oar** [open-apparel-registry/open-apparel-registry#2396]
## Overview
User story: As an OS Hub developer, I want to transfer the OAR repository to into the Open Supply Hub GitHub repo so that I can refer to the full development history in the future. 

### Describe the solution you'd like
1) Add Klaus and/or Mariel as an admin/owner (whatever role is necessary) on the OAR repo; they are owners of the [Open Supply Hub](https://www.opensupplyhub.org/) repo and will be able to complete the transfer from there, based on the documentation linked below. 

### Additional Context
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by mariel-oar** [comment]
OAR repo is on it's own - Mariel / Klaus can be made owners of repo

**Comment by obrienad** [comment]
OS Hub is managing this, so closing this issue.
