### ISSUE TITLE
Attend 2 knowledge transfer meetings

### ISSUE THREAD

**Issue by obrienad** [open-apparel-registry/open-apparel-registry#2398]
Two 1-hour knowledge transfer meetings with OSH / S&F

**Comment by jwalgran** [comment]
@jwalgran Checking that this is 2 prep sessions x 2 hours = 4 hours total (time boxed)

**Comment by jwalgran** [comment]
@obrienad Checking that this is 2 prep sessions x 2 hours = 4 hours total (time boxed)

**Comment by obrienad** [comment]
Moving prep session to separate ticket because it will be filed under a different task.
