### ISSUE TITLE
Restore scroll position for facilties tab 

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#250]
## Overview

Currently there is no way to restore the scroll position for the facilities tab when returning from the details page. Since the result list can be long we should consider enabling a way to restore scroll position:

<img width="384" alt="Screen Shot 2019-10-28 at 9 01 46 AM" src="https://user-images.githubusercontent.com/17363/67695002-98ab0700-f961-11e9-83d5-c9eeb36ed0eb.png">

### Describe the solution you'd like

- After scrolling down a long list of search results, clicking a result to view the facility details, then clicking the ← arrow to return to the results list, the list is in the same scroll position.

**Comment by jwalgran** [comment]
Superceded by #753
