### ISSUE TITLE
A FacilityMatch is not created when all pending matches are rejected

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#255]
## Overview

When all pending matches for a FacilityListItem are rejected, a new Facility is created, however a FacilityMatch row is not being created, resulting in the contributor not appearing on the facility detail page.

### Expected Behavior

The facility detail page for a facility created after rejecting all pending matches displays the name of the contributor.

The tests are updated to verify that this works.

### Actual Behavior

The facility detail page for a facility created after rejecting all pending matches does not show the name of the contributor.

### Steps to Reproduce

NOTE: These specific steps depend on #248 and  #253

* ./scripts/manage resetdb
* Register an account
* Upload  ⁨src⁩/django⁩/api⁩/management⁩/commands⁩/facility_lists⁩/13.csv
* Fully process the CSV
  * `./scripts/manage batch_process --list-id 15 --action parse`
  * `./scripts/manage batch_process --list-id 15 --action geocode`
  * `./scripts/manage batch_process --list-id 15 --action match`
* Browse the list http://localhost:6543/lists/15?page=1&rowsPerPage=100
* Reject the "Workfield Knitwears" match and confirm the rejection
* Click the "Workfield Knitwears" link to browse the facility detail page

### Demo

<img width="1036" alt="screen shot 2019-03-05 at 12 35 30 pm" src="https://user-images.githubusercontent.com/17363/53831982-4d139b00-3f43-11e9-9dbd-d1b4d26ce443.png">

**Comment by kellyi** [comment]
I updated the issue to include a line about having a test to verify that the code works.
