### ISSUE TITLE
Link for signing up to mailing list is broken

### ISSUE THREAD

**Issue by rcheetham** [open-apparel-registry/open-apparel-registry#259]
## Overview
There is a "Sign Up" link on the home page of https://info.openapparel.org/ - the link is pointing to https://info.openapparel.org/getinvolved - the link is broken.

### Expected Behavior
The link is intended to go to a page that enables the user to sign up for a mailing list.

### Actual Behavior
The page is not found.

![image](https://user-images.githubusercontent.com/595431/53888063-8efb1a80-3ff1-11e9-8aef-5d92f612bd8d.png)

**Comment by katieashaw** [comment]
Thanks for flagging! This was obviously pointing to an old page. It's now pointing to https://info.openapparel.org/contactus
