### ISSUE TITLE
Move AWS hosting to an EU based data center

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#263]
## Overview

Move the AWS hosting to an EU-based data center

### Is your feature request related to a problem? Please describe.

Our contract requires us to host the site in an EU-based data center

### Describe the solution you'd like

Move to an EU-based data center. Confirm that the different services are all using an EU-based data center. I.e. uploading a list to S3 does not host it in a US based data center.

### Additional Context

Ideally, done by March 25 although March 18 would be even better.

**Comment by hectcastro** [comment]
Ensure that timesheet entries related to this work include references to GDPR:

- Enter as a separate entry in GMT
- Ensure that the entry note begins with GDPR

**Comment by hectcastro** [comment]
- [ ] Migrate development S3 buckets
- [ ] Update deployment README; root README
- [ ] ECR image migration?
- [ ] Update Batch AMIs
- [ ] Update Jenkinsfile
- [ ] Update Docker Compose
- [ ] Migrate research subdirectory contents?
- [ ] Create new Rollbar tokens
- [ ] Create new Google Geocoding API
- [ ] Add `NS` record for `preview.`
- [ ] No logs going to CloudWatch Logs?

**Comment by hectcastro** [comment]
I pulled https://github.com/open-apparel-registry/open-apparel-registry/issues/285 into this sprint since we may be able to take care of it as part of resolving the Google Geocoding API aspects of this issue.
