### ISSUE TITLE
Update text on GDPR notification

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#265]
## Overview

Update text on GDPR compliance notification

### Is your feature request related to a problem? Please describe.

Current text is a placeholder and needs to be updated.

### Describe the solution you'd like

Text is still pending

**Comment by dboyer** [comment]
Use this text:

The Open Apparel Registry uses cookies to collect and analyze site performance and usage. By clicking the Accept button, you agree to allow us to place cookies and share information with Google Analytics. For more information, please visit our Terms and Conditions of Use and Privacy Policy.

Link Terms and Conditions of Use and Privacy Policy to https://info.openapparel.org/tos/

**Comment by jwalgran** [comment]
I removed the design label because this is just a copy update.
