### ISSUE TITLE
Clicking "Accept" on compliance notification should opt users in to Google Analytics tracking

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#267]
## Overview

If users click reject in the cookie notification implemented as part of #218, we need to not track any info in Google Analytics

### Is your feature request related to a problem? Please describe.

GDPR requires an option to opt out of analytics tracking

### Describe the solution you'd like

If a user clicks reject, we need to not send any of their information to Google Analytics or store tracking cookies

### Additional Context

These posts may have helpful info:

https://www.blastam.com/blog/gdpr-need-consent-for-google-analytics-tracking
https://www.blastam.com/blog/5-actionable-steps-gdpr-compliance-google-analytics

**Comment by dboyer** [comment]
We should use Google Tag Manager - https://www.portent.com/blog/analytics/gtm-gdpr-consent.htm

**Comment by kellyi** [comment]
It does not appear that Google Analytics is set up in the application at all yet, so we may need to do that as part of this work too.

**Comment by kellyi** [comment]
After discussing this we determined that the proper behavior is to only start GA tracking after the user has clicked "Accept" on the notification bar rather than "always unless the user has clicked 'Reject'". Going to update the title to reflect that change.

**Comment by kellyi** [comment]
@dboyer reminder that we also need some updated text for the notification dialog.
