### ISSUE TITLE
Hide the public column on /lists / make the values of the active column Yes or No / Use style to emphasize active lists

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#274]
## Overview

Clean up the display of the /lists page by

- Hiding the "Public" column as we are not yet implementing private lists
- Changing the values of the "Active" column to the more person-friendly, "Yes" or "No."
- Using styling to make active lists more prominent than inactive lists (Would appreciate a suggestion rom @designmatty)

**Comment by designmatty** [comment]
You might consider doing something along these lines:
![image](https://user-images.githubusercontent.com/1928955/54045347-5c8f2000-419f-11e9-9c78-af3e37a1bdad.png)

**Comment by dboyer** [comment]
In conversation with the client, we decided to go  with Active/Inactive in the Active column rather than Yes/No in order to be very clear.

**Comment by kellyi** [comment]
> we decided to go with Active/Inactive in the Active column rather than Yes/No in order to be very clear

This makes sense. I will create another pull request for this issue to do that work rather than having to create another issue.
