### ISSUE TITLE
Testing Feedback Black Box [EMPTY]

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#277]

**Comment by jwalgran** [comment]
Removed 1 point for https://github.com/open-apparel-registry/open-apparel-registry/issues/278

**Comment by jwalgran** [comment]
Removed 1 point for #281

**Comment by jwalgran** [comment]
Removed 1 point for #301

**Comment by jwalgran** [comment]
Removed 1 point for #366

**Comment by kellyi** [comment]
Removed 1 for #361

**Comment by kellyi** [comment]
Removed 1 for #376 and a collection of other tiny fixes

**Comment by jwalgran** [comment]
Removed 1 for #288

**Comment by kellyi** [comment]
-1 for #394

**Comment by rajadain** [comment]
-1 for #396

**Comment by jwalgran** [comment]
-1 for #391

**Comment by rajadain** [comment]
-1 for #399
