### ISSUE TITLE
Facilities List is Incorrectly Cached

### ISSUE THREAD

**Issue by rajadain** [open-apparel-registry/open-apparel-registry#278]
## Overview

If, after logging out from an account A, I login as a second account B, go to my Lists and click My Facilities, I am shown the facilities contributed by A, not by B.

### Expected Behavior

When My Facilities is clicked, the facilities contributed by the currently active account are shown.

### Actual Behavior

Facilities cached from last time are shown.

### Steps to Reproduce

* Have two accounts, A and B.
* Log in as A. Go to My Lists, then My Facilities. Note the URL and the contributor filter value.
* Log out. Log in as B. Go to My Lists, then My Facilities. Note the URL and the contributor filter correspond to A, instead of B.

### Demo

![2019-03-07 17 46 36](https://user-images.githubusercontent.com/1430060/53994889-7ed26080-4101-11e9-8968-407c1d95f3d3.gif)

Note the URL and the value in the filter.

### Additional context

The link from My Facilities is correct, but the change happens somewhere during routing. Thus, if the link for A is `/facilities/?contributor=100` and the list for B is `/facilities/?contributor=101`. The My Facilities link for B will point to `101`, and then navigate to `101`, but then somehow everything will shift to `100` and the URL will be updated to match.

**Comment by kellyi** [comment]
I wonder if it makes sense to add a listener for the `COMPLETE_SUBMIT_LOGOUT` action in every reducer -- besides maybe the one for filter options -- which would reset that reducer back to its initial state. That should cure this and other similar bugs related to stale data.
