### ISSUE TITLE
Configure billing for Google Maps API keys

### ISSUE THREAD

**Issue by hectcastro** [open-apparel-registry/open-apparel-registry#289]
Currently, we are using free tier Google Maps API keys. We should ensure that the 2.0 release makes use of client provided Google Maps API keys that are associated with a valid billing account.

**Comment by dboyer** [comment]
Updating to note that we can create the keys and do not need to wait for the client to do so.

**Comment by jwalgran** [comment]
Changing the title to reflect the fact that we will be sticking with the keys we have already created and that we just need to set up billing for them.

<img width="1291" alt="Screen Shot 2019-03-13 at 9 55 28 AM" src="https://user-images.githubusercontent.com/17363/54298650-5f5e8c00-4576-11e9-8da6-9a727f36ef27.png">

**Comment by dboyer** [comment]
Closing as we have billing set up for the keys already created.
