### ISSUE TITLE
Site not loading in IE 11

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#297]
## Overview

A script error is preventing the application from loading in IE11.

### Expected Behavior

Browsing the app working in IE 11

### Actual Behavior

An unhandled script error causes the app to fail

```
SCRIPT5009: 'Promise' is undefined
1.chunk.js (59631,34)
```

### Steps to Reproduce

* Browse the root url with IE11

**Comment by kellyi** [comment]
Promise polyfill was quick but now it's encountering this: https://github.com/zloirock/core-js/issues/193

Going to try adding the function name polyfill too.
