### ISSUE TITLE
Update fixture generator and committed fixtures to be more realistic

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#301]
## Overview

We will soon be taking screen captures for promotional videos and asking for design feedback from some trusted contributors. Attempt to avoid questions and confusion by making the fixture data more closely resemble actual data.

### Describe the solution you'd like

- Geocode the facility address so that they show up at real locations rather than randomized points around Philladelpha.
- Generate contributor names that match the type of the contributor, rather than random names i.e. Brand A, Brand B, Manufacturer Group A, Service Provider B 
   - Create a roughly equal distribution of contributors in each type.

**Comment by katieashaw** [comment]
Adding an additional request to this task for the screen record for the launch animation, scheduled for this Friday 15th at 9.30am EDT.

I've shared the storyboard for the animation with @jwalgran and @dboyer We will want to capture screen records for the following slides in the storyboard:

_Possibly_ slide 15: Easily upload your data (happy to visualise this differently, if you prefer not to have a screen record of this yet)
Slide 16: Search by facility
Slide 17: Filter by contributor
Slide 18: Identify facility affiliations

For the purposes of the screen record, I only need to be able to run one search using dummy, but logical, data - i.e. addresses plotting in the correct country, showing multiple versions of the address that have been matched, and a few affiliations for the facility.

The video production company has said that animating fake data over the top of the screen record will be difficult for them, so is there a way you can create a search for me to carry out that matches this criteria, and let me know what to search by on Friday?

**Comment by jwalgran** [comment]
I don't think there is any problem showing the data upload page (/contribute)

Our demo data already has associations built in so we will be able to provide you with a search that you can run and a facility that you can select that will show the relationships mentioned in the slite 18.

**Comment by katieashaw** [comment]
Wonderful, thank you!

**Comment by kellyi** [comment]
I think we should drop the `fake.url()` from the website part of the fixture generator -- https://github.com/open-apparel-registry/open-apparel-registry/blob/develop/src/django/api/management/commands/makefixtures.py#L147 -- and instead just have it be a constant value, like `"https://info.openapparel.org"`.

**Comment by jwalgran** [comment]
After deploying #315 I ran commands to reload the database and run the demo data through the matching algorithm. Things are set up in a way that should allow us to record the demos mentioned in the storyboard.

**Slide 16: Search by facility
Slide 18: Identify facility affiliations**

If you search for "regina" there is a facility that has a nice 3-way match. This shows off both searching by facility and identifying affiliations.

![2019-03-14 19 40 29](https://user-images.githubusercontent.com/17363/54404605-56161200-4691-11e9-8a44-431cf509db40.gif)

**Slide 17: Filter by contributor**

Not all the contributors in the list have uploaded lists. "Brand C" is one that does.

![2019-03-14 19 44 06](https://user-images.githubusercontent.com/17363/54404709-ae4d1400-4691-11e9-8358-d01b2b74e1da.gif)

**_Possibly_ slide 15: Easily upload your data**

We have standardized the logins on the demo data. You can log into any of the demo data accounts with the email address `c{id}@example.com` and the password `password`. This will allow you to use the contribute page. For example, in this screenshot I am logged in as `c8@example.com`

<img width="1382" alt="Screen Shot 2019-03-14 at 7 47 58 PM" src="https://user-images.githubusercontent.com/17363/54404945-43500d00-4692-11e9-8df9-df3a4041c92d.png">

The `c8@example.com` also has some potential matches that require confirmation.

![2019-03-14 19 54 40](https://user-images.githubusercontent.com/17363/54405226-210abf00-4693-11e9-9041-6e9bfa9eaa90.gif)

**Comment by jwalgran** [comment]
The closing was accidental.

**Comment by katieashaw** [comment]
@jwalgran This is brilliant - thank you SO much! The screen recording was a little delayed, but I'm off to the video agency shortly. Really great to have this all set up, I'm very grateful!
