### ISSUE TITLE
Change map markers and clusters to match the branding

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#302]
## Overview

#284 implements using Google Maps and markerclusterer using the default markers from Google Maps for single facilities and a set of quickly-made icon images for the clusters.

We should update these markers to match the app's branding.

### Describe the solution you'd like

Update the facility markers and the cluster markers to match the branding.

### Additional Context

The images for markerclusterer are m1-m5.png in this directory: https://github.com/open-apparel-registry/open-apparel-registry/tree/develop/src/app/public/images

Updating those just requires dropping new png files in the directory with the same names. 1-5 are used differently by the library for clusters with different numbers of elements. The library will print the number of items in the cluster on top of the marker:

![Screen Shot 2019-03-13 at 1 38 47 PM](https://user-images.githubusercontent.com/4165523/54301474-65179a00-4595-11e9-8fd8-aa21b2311871.png)

![Screen Shot 2019-03-13 at 1 38 51 PM](https://user-images.githubusercontent.com/4165523/54301475-65b03080-4595-11e9-989e-b71871826138.png)

For the other markers, Google Maps affords using custom symbols: https://developers.google.com/maps/documentation/javascript/examples/marker-symbol-custom

This is where the app creates the markers: https://github.com/open-apparel-registry/open-apparel-registry/blob/develop/src/app/src/components/FacilitiesMap.jsx#L130

**Comment by jwalgran** [comment]
We will want to expedite this so that it is in place before the screen recording session at 9:30am Friday March 15

**Comment by kellyi** [comment]
Just realized there is one other place where we need to update the marker style:

https://github.com/open-apparel-registry/open-apparel-registry/blob/develop/src/app/src/components/FacilityDetailsStaticMap.jsx#L13

The static maps api allows you to request a marker to be placed in the image from the image url, which is what:

```
&markers=||${lat},${lng}
```

...is doing. The initial `||` is an empty placeholder which leads it to use the default marker but one is also able to pass in optional marker styles there, per: https://developers.google.com/maps/documentation/maps-static/dev-guide#Markers
