### ISSUE TITLE
Show the total number of facilities on the search tab

### ISSUE THREAD

**Issue by nataliegrillon** [open-apparel-registry/open-apparel-registry#323]
## Overview

~Add an "ALL contributors" Option: It would be nice to be able to see all the factories at once rather than only a selection.  By selecting all contributors in the drop down of contributors you could see all of the data and all of the facilities in the database.~ Perhaps we could also have a total facilities counter down in the lower right hand corner of the search bar so that a user knew how many facilities were in the database

### Is your feature request related to a problem? Please describe.

I can't see all the data in the database or know how  big the data set is.

### Describe the solution you'd like

~In the contributor drop down, have an "all contributors" option and~ have a counter in the bottom right hand corner of the search to see the total number of facilities in the database at any one point. 

@dboyer @katieashaw

**Comment by jwalgran** [comment]
It would be possible, and relatively easy, to show the total number of facilities on the "Search" tab.

There are over 10,000 unique facilities in the original set of 42 public supplier lists. With the current map design we are going to struggle to load and display that many points simultaneously. Like the previous version of the application, we are probably going to want to put a cap on the maximum number of results we will return from the API and display at one time.

**Comment by nataliegrillon** [comment]
There are over 10k in the database currently! That's great.

Understood on the results for the API- that makes sense and is no problem
from my perspective. The goal here is more to indicate to users what the
total database has just for their reference.

Best,

Natalie
----
Natalie Grillon
Project Director, Open Apparel Registry
+ 1 413 884 3355
*natalie@openapparel.org <natalie@openapparel.org> *
*Open Apparel Registry <http://openapparel.org>*

**Comment by jwalgran** [comment]
We only have about 900 in the demo data, but when I was working on training the matching algorithm using the public lists you provided the total number of rows was around 18 thousand and there were several thousand duplicates. Unless we load a fewer number of list or the revised versions of those lists have shrunk dramatically I would expect that we will have around 10k.

**Comment by jwalgran** [comment]
I am changing the title of this issue to reflect the change in scope.

**Comment by nataliegrillon** [comment]
ok awesome!

Best,

Natalie
----
Natalie Grillon
Project Director, Open Apparel Registry
+ 1 413 884 3355
*natalie@openapparel.org <natalie@openapparel.org> *
*Open Apparel Registry <http://openapparel.org>*
