### ISSUE TITLE
Cookie notification does not need to pop up every time you visit the site [SHARES POINT WITH 326]

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#324]
## Overview

The legally required pop-up re. tracking cookies that has been added to the site appears every single time you visit the site, rather than just the first time you access it. My understanding, and experience through using websites in Europe, is that the pop-up just needs to appear once, be accepted, and then that acceptance applies for all future visits to the site. 

### Expected Behavior

The cookies tracking pop-up should just appear the first time a site is visited. Having accepted that cookies will be tracked, the pop up should not appear again on future visits. 

### Actual Behavior

The pop up appears and has to be accepted every time you visit the OAR site.

### Steps to Reproduce

* Load the home page
* Accept the cookie popup
* Load the home page in a new tab or browser window

**Comment by jwalgran** [comment]
The accept/reject status is currently tracked in `sessionStorage` which only is discarded when the tab/window is closed. We should move the status persistence to `localStorage`.
