### ISSUE TITLE
Vietnam country filter not appearing correctly [SHARES POINT WITH 324]

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#326]
## Overview

Vietnam appears in the dropdown country filter as Viet Nam. When you type Vietnam into the country search box, it's not recognised.

### Expected Behavior

Users should be able to search the site using Vietnam (all one word).

### Actual Behavior

Vietnam is listed in the country drop down menu as Viet Nam. 

### Steps to Reproduce

* Visit staging.openapparel.org
* Search Vietnam in the country dropdown menu

### Demo

![Screenshot 2019-03-18 at 17 52 05](https://user-images.githubusercontent.com/46344729/54551768-a26d9480-49a6-11e9-8f87-6ca1658e1a45.png)
![Screenshot 2019-03-18 at 17 52 14](https://user-images.githubusercontent.com/46344729/54551781-a6011b80-49a6-11e9-986f-efc71f656169.png)

### Additional context

Optional. Add any other context about the problem here.

**Comment by jwalgran** [comment]
Good catch. Thank you. The wikipedia list of 2-character country codes listed used the 2-word form, which is how it got into our list.
<img width="951" alt="Screen Shot 2019-03-18 at 10 57 07 AM" src="https://user-images.githubusercontent.com/17363/54552174-b98f9080-496c-11e9-9d13-a6689c02cc56.png">

**Comment by katieashaw** [comment]
Gosh, how intriguing!
