### ISSUE TITLE
Unhandled error raised in staging when uploading a facility list

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#333]
## Overview

Unhandled error raised in staging when uploading a facility list

### Steps to Reproduce

This exception was raised on staging while creating a list named "Clarks Alpha Finsihed Goods Facility List January 2019"

[Clarks.csv.txt](https://github.com/open-apparel-registry/open-apparel-registry/files/2984354/Clarks.csv.txt)

### Demo

![Screen Shot 2019-03-19 at 09 04 30](https://user-images.githubusercontent.com/17363/54622077-1f8c1e80-4a26-11e9-942d-21a5ed3fd55a.png)

![Screen Shot 2019-03-19 at 09 04 51](https://user-images.githubusercontent.com/17363/54622087-261a9600-4a26-11e9-8687-82eaaf0371dc.png)

### Additional context

https://rollbar.com/OpenApparelRegistry/OpenApparelRegistry/items/34/

**Comment by rajadain** [comment]
This is possibly a file encoding issue

```bash
$ file Clarks.csv

Clarks.csv: Non-ISO extended-ASCII text, with CRLF, LF line terminators
```

It is possible that we _could_ read it with a `windows-1252` or other encoding (see https://stackoverflow.com/a/48067785).

One way to do it would be to keep trying different encodings on every failure, although we'd then have to maintain a list of nested encodings. Another would be to return an error that asks the user to upload a UTF-8 file, although that may be too complicated for some users to handle? It's probably easy to google "convert file to utf8" and find an online encoder like [this one](https://subtitletools.com/convert-text-files-to-utf8-online).

Recommendations on how to proceed?

**Comment by jwalgran** [comment]
That particular file would never be processed correctly because of all the breaks within the address

<img width="803" alt="Screen Shot 2019-03-20 at 1 50 02 PM" src="https://user-images.githubusercontent.com/17363/54718154-22b30780-4b17-11e9-87dd-5a8743be2d62.png">

I think the proper solution for now is to just catch `UnicodeDecodeError` and do two things:
- Return a message to the contributor that the file does not meet the requirements. We do explicitly say that it needs to be UTF-8 on the contribute page
<img width="1165" alt="Screen Shot 2019-03-20 at 1 52 26 PM" src="https://user-images.githubusercontent.com/17363/54718350-889f8f00-4b17-11e9-914b-18ac2dc75e3f.png">
- "Manually" post an error to Rollbar with the contributor details and file name so we can be proactive about supporting people who are having upload problems.
