### ISSUE TITLE
Error when retrieving list due to a gateway timeout

### ISSUE THREAD

**Issue by nataliegrillon** [open-apparel-registry/open-apparel-registry#335]
## Overview

I had uploaded a list and when I went back to my lists , I can no longer access it via clicking on "my lists" and then clicking on the list entry. I get the response, "unable to retrieve list - an error prevented fetching facility list items for 25" - please see screen recording

### Expected Behavior

I should have bene able to click on the list and have the entries load.

### Actual Behavior

"Unable to retrieve list - an error prevented fetching facility list items for 25"

### Steps to Reproduce

Mac, Chrome in incognito

- After a csv has been uploaded, leave it for several hours to let it parse
- refresh page
- click on my lists 
- Select list from table of my lists
- Error message appears

### Demo

![list_access_issue_3 19 2019_trimmed](https://user-images.githubusercontent.com/17363/54635116-bb2a8880-4a40-11e9-97f2-68d771eb8b11.gif)

### Additional Context

[Esprit_02_2019_converted.March.13.2019.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/2985222/Esprit_02_2019_converted.March.13.2019.xlsx)

**Comment by jwalgran** [comment]
To help with troubleshooting can you please attach the list that you uploaded? If you rename the file and add a `.txt` extension you will be able to attach it to this issue. Thanks.

**Comment by nataliegrillon** [comment]
Yes of course - sorry I didn't think of that. Added it as an excel file - hope that is OK

[Esprit_02_2019_converted March 13 2019.xlsx](https://github.com/open-apparel-registry/open-apparel-registry/files/2985059/Esprit_02_2019_converted.March.13.2019.xlsx)

**Comment by jwalgran** [comment]
Cool. I forgot that Github accepts xlsx. That works. Thanks.

**Comment by jwalgran** [comment]
The request to https://staging.openapparel.org/api/facility-lists/25/ is returning 504 Gateway Timeout. It is taking too long load the list. The source CSV has 1385 rows. 

Options:
- Implement server-side paging
- Delay loading the details for rows until they are clicked (with the exception of pending matches, which should be expanded by default.
