### ISSUE TITLE
Logging out from the list detail page shows a "no list found for that ID" message / browsing list when logged out shows technical error

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#343]
## Overview

Logging out from the list detail page shows a "no list found for that ID" message

Browsing a list page when not logged in shows a technical error message.

### Expected Behavior

The when logging out from a list page the app redirects to the map page

When visiting a list page when not logged in a login link is shown

### Actual Behavior

A not found message is displayed after logging out on a list page

A technical error is shown when browsing a list page when logged out.

### Steps to Reproduce

* Log in as c3@example.com
* Browse http://localhost:6543/lists/3
* Log out
* Refresh

### Demo

<img width="947" alt="Screen Shot 2019-03-20 at 9 44 40 AM" src="https://user-images.githubusercontent.com/17363/54702835-e1116500-4af4-11e9-85de-1f8787361fa4.png">

<img width="710" alt="Screen Shot 2019-03-20 at 10 23 41 AM" src="https://user-images.githubusercontent.com/17363/54705590-6a776600-4afa-11e9-9b8b-fb5d1d37a42b.png">

**Comment by kellyi** [comment]
Shares a point with #376
