### ISSUE TITLE
No apparent limits to map panning

### ISSUE THREAD

**Issue by ddohler** [open-apparel-registry/open-apparel-registry#365]
## Overview

In both Firefox and Chrome, it is possible to pan off the boundaries of the map both to the north and south.

### Expected Behavior

The map should refuse to pan past the northern and southern limits of its tiles.

### Actual Behavior

The map keeps panning, apparently without end.

### Steps to Reproduce

* drag the map southward until you can see all of Greenland
* keep going
* eventually it'll all be tileless and grey

### Demo

![panbug](https://user-images.githubusercontent.com/447977/54851656-0ce14600-4cc1-11e9-858a-968e99f89158.png)

**Comment by kellyi** [comment]
Shares a point with #376
