### ISSUE TITLE
Include country in facilities address in details sidebar

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#375]
## Overview

Add the country name to the address for a facility in the details sidebar

### Is your feature request related to a problem? Please describe.

Including the country name provides another reference for users who may be unfamiliar with the particular address structure

### Describe the solution you'd like

Add the country

**Comment by kellyi** [comment]
Shares a point with #375

**Comment by kellyi** [comment]
This data is already available in the client so it was pretty trivial to add:

![Screen Shot 2019-03-25 at 2 43 36 PM](https://user-images.githubusercontent.com/4165523/54945596-9f295a00-4f0c-11e9-97ab-be734fc84ed0.png)
