### ISSUE TITLE
Migrate application back to openapparel.org domain (3/27)

### ISSUE THREAD

**Issue by hectcastro** [open-apparel-registry/open-apparel-registry#377]
This may require:

- Importing the existing hosted zone into the Terraform state
- Update the remote Terraform variables
- Ensure that a Terraform plan/apply cycle applies cleanly

**Comment by rbreslow** [comment]
These are the rough steps as I see them, @hectcastro. Do you have anything to add or modify?

- [ ] Make sure we're targeting production, and the current Terraform plan is clean:
```bash
vagrant@vagrant:/vagrant$ docker-compose -f docker-compose.ci.yml run --rm terraform
bash-4.4# export OAR_SETTINGS_BUCKET=openapparelregistry-production-config-eu-west-1
bash-4.4# export OAR_DEPLOYMENT_ENVIRONMENT=production
bash-4.4# export GIT_COMMIT=...
bash-4.4# ./scripts/infra plan
...
No changes. Infrastructure is up-to-date.
...
bash-4.4# cd deployment/terraform/
```
- [ ] Apply these changes to the `.tfvars` file in the production S3 bucket:
```diff
diff --git a/openapparelregistry-production-config-eu-west-1.tfvars.bak b/openapparelregistry-production-config-eu-west-1.tfvars
index 6f2c321..906506e 100644
--- a/openapparelregistry-production-config-eu-west-1.tfvars.bak
+++ b/openapparelregistry-production-config-eu-west-1.tfvars
@@ -6,7 +6,7 @@ aws_availability_zones = ["eu-west-1a", "eu-west-1b"]
 aws_key_name = "oar-prd"

 r53_private_hosted_zone = "oar.internal"
-r53_public_hosted_zone = "preview.openapparel.org"
+r53_public_hosted_zone = "openapparel.org"

 cloudfront_price_class = "PriceClass_All"

@@ -46,7 +46,7 @@ rollbar_client_side_access_token = "48c79257c109447a85f44f74288fbedf"

 django_secret_key = "pql+t8ehhzgp)m5&&iyi60_##h@9p91g^j@vw%thuusqngs9@v"

-default_from_email = "noreply@preview.openapparel.org"
+default_from_email = "noreply@openapparel.org"

 batch_default_ce_spot_fleet_bid_percentage = 40
 batch_ami_id = "ami-00921cd1ce43d567a"
```
- [ ] Remove the `preview.openapparel.org` hosted zone from the Terraform state:
```bash
bash-4.4# terraform state rm aws_route53_zone.external
```
- [ ] Import the `openapparel.org` hosted zone:
```bash
bash-4.4# terraform import aws_route53_zone.external Z2FK682W87ON24 \
	-var-file=openapparelregistry-production-config-eu-west-1.tfvars
```
- [ ] Remove the CloudFront distribution and the ACM certificate from the Terraform state:
```bash
bash-4.4# terraform state rm module.cert_cdn.aws_acm_certificate.default
bash-4.4# terraform state rm aws_cloudfront_distribution.cdn
```
- [ ] Cycle Terraform plan and apply:
```bash
bash-4.4# cd ../../
bash-4.4# ./scripts/plan
bash-4.4# ./scripts/apply
```
- [ ] Clean up out-of-band `openapparel.org` -> `info.openapparel.org` CloudFront/S3 redirect
- [ ] Clean up `preview.openapparel.org` hosted zone, CloudFront distribution, and ACM certificate
- [ ] Setup `preview.openapparel.org` -> `openapparel.org` CloudFront/S3 redirect

--- 

- [ ] Verify SES configuration
- [ ] Verify Google Analytics 
- [ ] Verify redirects are functional

**Comment by hectcastro** [comment]
Looks good. The only area I don't feel super confident in is with the certificate and CloudFront distribution state removal steps—primarily because I've never done it that way, and don't have a strong sense for how it'll play out.

What I have done is apply the changes via Terraform, and then manually remove the ACM certificate associated from CloudFront, which allows Terraform to replace the certificate.

The only other thing would be to try and have the underlying components (S3 website redirect, CloudFront distribution with S3 website set as origin) for the `preview.` -> `openapparel.org` redirect in place prior to doing all of these steps. The certificate association and DNS record addition will have to happen after `openapparel.org` is serving the site.

**Comment by rbreslow** [comment]
Could you rearticulate the problem that you see arising if we were to leave the CloudFront and ACM certificates as they are, and cycle Terraform?

I do think what you're saying is more ideal, because we'll be able to reuse the existing distribution, but I'm not entirely confident that Terraform won't hit a snag trying to reuse the distribution.

**Comment by hectcastro** [comment]
> Could you rearticulate the problem that you see arising if we were to leave the CloudFront and ACM certificates as they are, and cycle Terraform?

The domain name change will cause the ACM certificate to be replaced (delete and recreate). It cannot be deleted until there are no resources associated with it (CloudFront). The disassociation with CloudFront takes a while, and that may cause Terraform to timeout, but it also prevents the new certificate from being created.

There may be a way to avoid this with a precise application of `create_before_destroy` on the ACM certificate, but I have not tested that yet. The idea there would be that the ACM certificate for `openapparel.org` would exist right away, which would allow it to be swapped in to CloudFront and unblock downstream operations that depend on the certificate.

**Comment by rbreslow** [comment]
Things that we weren't expecting:

- There was an existing CloudFront distribution that had `openapparel.org` associated as a CNAME
```bash
* aws_cloudfront_distribution.cdn: error updating CloudFront Distribution (E3JMJE8P617OQD): CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.
```
- We had to update Panopta notifications, although Hector knew the failure in **#oar** would prompt us
- Update the old `www.` redirect to resolve to the naked domain (?, possibly a comment we updated in the CloudFront distribution resource)
- Updated Google Analytics IDs across staging and production

Also, see https://github.com/azavea/terraform-aws-acm-certificate/issues/7, which we identified while going through the steps above.
