### ISSUE TITLE
There's a typo in the troubleshooting text on the Contribute page

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#381]
## Overview

A word is mis-spelt in the troubleshooting tips at the bottom of the Contribute page

### Expected Behavior

Separate should have an 'a" after the "p"

### Actual Behavior

The "a" after "p" in separate is missing. 

The font in this section also looks odd, so would be worth checking. 

### Steps to Reproduce

* Visit https://preview.openapparel.org/contribute and scroll to the bottom of the page to the Troubleshooting text. 

### Demo

![Screenshot 2019-03-25 at 16 48 02](https://user-images.githubusercontent.com/46344729/54939142-ba519500-4f1f-11e9-9a0b-50b59486fafc.png)

### Additional context

Optional. Add any other context about the problem here.

**Comment by kellyi** [comment]
Shares a point with #376
