### ISSUE TITLE
Text formatting on Facility List page is odd

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#382]
## Overview

The formatting of new text on the Facility List page is appearing justified right.

### Expected Behavior

The additional text should be justified left, under the other text on the page.

### Actual Behavior

The additional text is justified right. 

### Steps to Reproduce

* Log into a user account
* Navigate to https://preview.openapparel.org/lists/2

### Demo

![Screenshot 2019-03-25 at 16 48 22](https://user-images.githubusercontent.com/46344729/54939559-c853e580-4f20-11e9-89f0-f950538de23c.png)

### Additional context

Optional. Add any other context about the problem here.

**Comment by kellyi** [comment]
Shares a point with #376
