### ISSUE TITLE
Text in the Guide panel needs replacing

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#383]
## Overview

The copy in the Guide panel on the site is legacy copy, which needs replacing. 

### Expected Behavior

New copy needs to appear in the Guide panel on the preview site. Please replace with copy in this doc: https://docs.google.com/document/d/1uz1q6ORlNjknoMx7g1WYNzTBhFM2hLR_TSgqt_TTezU/edit

### Actual Behavior

Legacy copy is appearing in the Guide panel on the preview site.

### Steps to Reproduce

* Visit preview.openapparel.org
* Click the guide panel

### Demo

Optional. Screenshots, gifs, `curl` examples, console errors, log files, etc.

### Additional context

Optional. Add any other context about the problem here.

**Comment by kellyi** [comment]
Shares a point with #376

**Comment by dboyer** [comment]
Use the text:

The Open Apparel Registry (OAR) is an open source tool which maps garment facilities worldwide and assigns a unique ID number to each. Its goal is to become the go-to source for identifying apparel facilities and their affiliations by collating disparate supplier lists from industry stakeholders into one central, open source map and database.

The collated database of facility names, addresses and affiliated parties is powered by an advanced name and address-matching algorithm and will be available for use by any organization, for free.

To contribute to the database, users must create a free account. Anyone can sign up and contribute. Users interested in browsing the OAR are able to access it without creating an account.
