### ISSUE TITLE
Don't display contributors that have no lists or no active lists in search dropdown

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#413]
## Overview

Don't display contributors that have no lists or no active lists in search dropdown

### Describe the solution you'd like

Update the contributors endpoint to prevent returning contributors who have either

- no lists at all
- no active lists
- no public lists

Also ensure that users who are logged in and click on the "My Facilities" Link in various places in the app end up in a proper state: essentially the ID will "miss" the set of options for collating it on in the contributors response, so figure out how to handle that.

**Comment by kellyi** [comment]
I think we may also want to filter out contributors who have active/public lists if those lists do not have any facility matches. Otherwise the menu will display contributors whose lists are still in progress but as yet have no matches to display.

**Comment by kellyi** [comment]
> Also ensure that users who are logged in and click on the "My Facilities" Link in various places in the app end up in a proper state: essentially the ID will "miss" the set of options for collating it on in the contributors response, so figure out how to handle that.

This is already working in a correct way without changes. Essentially If I click "My Facilities" without having any lists, my contributor ID will not match any of the contributors sent back, so the search will return no facilities and show a message that no facilities were returned:

![Screen Shot 2019-03-28 at 1 35 18 PM](https://user-images.githubusercontent.com/4165523/55179688-61bc0b00-515e-11e9-9264-51569e31cbaa.png)

**Comment by jwalgran** [comment]
>This is already working in a correct way without changes.

I am not 100% happy with the way this is working as we are adding an invalid item to the contributor list and the fact that it is an integer looks broken. I can imagine a contributor thinking "My company is not named '1'. Why did it search for that."

We have enough information to show a more helpful message to the contributor.
- We know they are logged in
- We know they are searching for themselves
- We know that they have not active facility lists

With this information we could show a "You have no active facility lists. <a>Contribue</a> your facilities to see them on the map" message with a helpful link

This is a bit challenging and, if we agree to implement it this way, it may make sense to create a separate issue for it.

**Comment by kellyi** [comment]
>  I am not 100% happy with the way this is working as we are adding an invalid item to the contributor list and the fact that it is an integer looks broken. I can imagine a contributor thinking "My company is not named '1'. Why did it search for that."

This makes sense. One thing I considered and can do here is to add a `has_active_lists` property to the user serializer which we can check on in the navbar to determine whether to show the "My Facilities" link in the dropdown. If `has_active_lists` is false, we just don't show the link.

This would unfortunately not immediately make the link re-appear after the user has uploaded a list during the same session. We currently do not show the "My Facilities" link on the list page if there are no lists, but it does automatically show once a list has been uploaded.

**Comment by jwalgran** [comment]
I would prefer to guide them toward contributing rather than hide links.

**Comment by kellyi** [comment]
Made #431 for implementing the My Facilities behavior change.
