### ISSUE TITLE
Update test script to allow running only specifically named Django tests

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#429]
## Overview

The Django test suite has a long running time, which makes the process of writing new tests or updating old tests a little burdensome because the `test --django` option still goes through the whole suite by default.

We should allow passing an optional argument after `--django` that would name a specific test case to run without running all the others, like

```
./scripts/test --django OarIdTests.test_invalid_county
```

### Describe the solution you'd like

Allow passing an optional argument after `--django` that would name a specific test case to run without running all the others, like

```
./scripts/test --django OarIdTests.test_invalid_county
```

Running `./scripts/test` or `./scripts/test --django` without the optional argument should continue to run the full test suite.

**Comment by kellyi** [comment]
It appears that this will already work as a `manage` command:

```
./scripts/manage test api.tests.ContributorsListAPIEndpointTests
```

**Comment by jwalgran** [comment]
You can go down to a single test function, too

./scripts/manage test api.tests.DedupeMatchingTests.test_matches

**Comment by kellyi** [comment]
Cool. I'm going to close this, then, since we already have an easy way to do this.
