### ISSUE TITLE
Publish button

### ISSUE THREAD

**Issue by nataliegrillon** [open-apparel-registry/open-apparel-registry#440]
## Overview

This final button would allow the contributor to click a publish button after they had been able to see results of the geocoding and gone through confirm/reject process

### Is your feature request related to a problem? Please describe.

Specifically brands have wanted to review their lists and make sure it matches exactly to the lists they have published on their website. The publish button would allow them to do that review before it went live on the map. 

### Describe the solution you'd like

A publish button either on the my lists page or at the bottom of the confirm/reject process

### Additional Context

Optional. Add any other context, screenshots, gifs, etc about the feature request here.

**Comment by katieashaw** [comment]
Closing as no longer considered necessary. This feature not existing has not prevented brands from uploading their data to the OAR.
