### ISSUE TITLE
China + google maps and map display

### ISSUE THREAD

**Issue by nataliegrillon** [open-apparel-registry/open-apparel-registry#442]
## Overview

Google is not available in China,  need to confirm if factories/manufacturers location in China can/can't use the platform or what the workaround will be for this.  Will they be able to see everything else on the site but the map will be blocked?

Only brands/retailers are uploading their lists for now but soon with  the functionality for factories updating their information for validation and additional details how will they interact with the map?

### Expected Behavior

need users in China to be able to see the map

### Actual Behavior

Uncertain

### Demo

Optional. Screenshots, gifs, `curl` examples, console errors, log files, etc.

### Additional context

Optional. Add any other context about the problem here.

**Comment by kellyi** [comment]
The changes in #446 should allow rest of the application to run if the FacilitiesMap component crashes for whatever reason -- including if the Google Maps script has been blocked.

**Comment by nataliegrillon** [comment]
thanks @kellyi  - so to make sure I"ve understood the rest of the site will function even if the google script has been blocked?

I know we need to do some more research to know if the map/site will definitely be blocked. I am reaching out to two contacts

**Comment by dboyer** [comment]
The below screenshot was provided by a user in China. The map is not visible. And yes, @nataliegrillon - as answer to your previous comment on this issue, the site will work with the exception of the map.

![Catch](https://user-images.githubusercontent.com/516764/55561249-d1cb1380-56bf-11e9-89f6-7bb9624d7d00.jpg)

**Comment by dboyer** [comment]
Likely needs to be addressed as part of #474 as many facilities are located in China.
