### ISSUE TITLE
Button missing in header

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#448]
## Overview

The profile/user button (not sure of exact label) is missing from upper right menu bar when logged in

### Expected Behavior

I should be able to click and view options for my profile, etc. 

### Actual Behavior

I can click there and see a drop-down but the actual button is not displaying

### Steps to Reproduce

* Log in to the site - the issue is on both production and staging
* Go to top corner and see missing button next to "Select Language"
* chrome on Macbook Air

### Demo
![Screen Shot 2019-04-01 at 3 32 00 PM](https://user-images.githubusercontent.com/516764/55354567-170afd80-5494-11e9-81f2-bbb1793a84dc.png)

### Additional context

Optional. Add any other context about the problem here.

**Comment by kellyi** [comment]
This happens when the logged in user has no contributor name. For users who have signed up via the Registration form, we validate that that field is not-null, but I don't think we have done so for the staging admin account.

**Comment by jwalgran** [comment]
Closing this because it is only an issue with test/admin accounts.
