### ISSUE TITLE
Upgrade to Django 2.2.x

### ISSUE THREAD

**Issue by hectcastro** [open-apparel-registry/open-apparel-registry#455]
We are currently using Django 2.0.x, which is not an LTS release (extended support ends in [April 2019](https://www.djangoproject.com/download/#supported-versions)). The 2.2.x series is an LTS release and has extended support through 2021.

**Comment by jwalgran** [comment]
- Use`FROM quay.io/azavea/django:2.2-python3.7-slim` in `src/django/Dockerfile` and do some extensive 
- Verify that all of our requirements have 2.2 support
- Test all features for regressions
