### ISSUE TITLE
Download CSV button on search page should download all results

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#462]
## Overview

Clicking "Download CSV" after conducting a search should download all search results, not just the first 500

### Is your feature request related to a problem? Please describe.

It is confusing that the downloaded CSV does not return all the listed search results. Several brands and users have reported confusion around this feature.

### Describe the solution you'd like

Include all search results in the CSV

### Additional Context

@katieashaw and @nataliegrillon Please add any other pertinent information that users have reported about this issue.

**Comment by jwalgran** [comment]
Superseded by #743
