### ISSUE TITLE
Add static meta tags for improved social sharing and Google description of the home page

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#464]
## Overview

Add static meta tags to the application to support social media sharing. 

### Is your feature request related to a problem? Please describe.

Mentioning "openapparel.org" in a tweet is creating a "card" that points to "info.openapparel.org" and lacks a description.

### Describe the solution you'd like

- Add `<meta>` tags to `src/app/public/index.html`
  - `og:title`
  - `og:description` and `description` (Same content. See below.)
  - `og:image` 
  - `og:url`
  - `<meta name="twitter:card" content="summary_large_image">`
  - `og:site_name`
  - `twitter:image:alt`

#### Description

>The Open Apparel Registry (OAR) is an open source map and database of global apparel facilities, their affiliations and unique OAR IDs assigned to each facility.

### Additional Context

Issue #491 was merged with this issue.

Recommended tags taken from 
https://css-tricks.com/essential-meta-tags-social-media/

OpenGraph
http://ogp.me/

**Comment by kellyi** [comment]
Shares a point with #767
