### ISSUE TITLE
Update to text in "Guide" tab: request for inclusion in new site version being deployed Apr 11th

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#465]
## Overview

The text in the "Guide" tab on the map needs updating

### Expected Behavior

The text in the "Guide" tab needs to be updated in line with the live status of the map.

### Actual Behavior

"Guide" tab text is dated now that the OAR has launched.

### Steps to Reproduce

N/A

### Demo

Screenshot of the outdated text:

![Screenshot 2019-04-10 at 17 30 15](https://user-images.githubusercontent.com/46344729/55896595-95635000-5bb6-11e9-8011-f2d5f52b069d.png)

### Additional context

@nataliegrillon and I will post approved text to this issue asap.

**Comment by nataliegrillon** [comment]
Here is new guide text @jwalgran @dboyer 

**The Open Apparel Registry (OAR) is an open data tool for correctly identifying global apparel facilities and their affiliations. The OAR collates disparate supplier lists from industry stakeholders into one global map and registry and assigns each unique facility an OAR ID.

The collated database of facility names, addresses and affiliated parties, pulled from public and contributed data, is powered by an advanced name and address-matching algorithm, developed by geospatial software firm, Azavea. The free-to-use, open source tool can be used by any organization to update and standardize a supplier list against the database, view facility affiliations and use the OAR ID as a unique and shared ID across software systems and databases. 

To contribute to the database, users must create a free account at the Register tab on the main toolbar. Anyone can sign up and contribute. Users interested in browsing the OAR are able to search the site without creating an account.**
