### ISSUE TITLE
Implement claim a facility functionality

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#474]
## Overview

Facility owners should be able to claim a facility

### Is your feature request related to a problem? Please describe.

Facility owners do not have an opportunity to add information about their facilities. 

### Describe the solution you'd like

Facility owners can submit information to claim a facility already in OAR or submit information about a new facility. This will likely include several related issues such as

- Verifying facility ownership

- Selecting data fields for the owner to edit

- Resolving differences in facility data provided by owner and brands

**Comment by jwalgran** [comment]
Superseded by #520
