### ISSUE TITLE
Implement facility verification process

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#476]
## Overview

Users requesting to claim a facility will need to be verified to confirm they are the owner of the facility. 

### Is your feature request related to a problem? Please describe.

Without a verification process, multiple individuals could claim the same facility. 

### Describe the solution you'd like

Criteria for verification will be selected as part of #475. There will likely be some form that facility owners need to submit. 

### Additional Context

Part of #474

**Comment by jwalgran** [comment]
Software support implemented in #563. Establishing the criteria used is a non-software task.
