### ISSUE TITLE
Admins should be able to view all lists

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#483]
## Overview

Admin users should be able to view all lists uploaded by users to support troubleshooting

### Is your feature request related to a problem? Please describe.

Several users have had issues with the upload process. Providing admins with access to the list page of any user would make it easier to assist with troubleshooting.

### Describe the solution you'd like

Admins can view all lists. We will need to decide if this should be limited to active lists due to privacy concerns and/or limited to view but not edit privileges (i.e. admins can't confirm or deny matches).

**Comment by jwalgran** [comment]
Implemented in #584

**Comment by jwalgran** [comment]
Superseded by #547
