### ISSUE TITLE
Research existing MSI systems and potential points of integration via OAR API

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#488]
## Overview

Integration via the OAR API is a feature planned for later in 2019

### Is your feature request related to a problem? Please describe.

Large data management systems may more efficiently interact with OAR via API integration

### Describe the solution you'd like

Coordinate with @nataliegrillon and @katieashaw to determine MSIs that may be resources for learning more about data management systems.

**Comment by jwalgran** [comment]
We have discussed integration requirements and received example data from MSIs
