### ISSUE TITLE
Add "(organization)" in between "Contributor" and "Name" field on Registration page 

### ISSUE THREAD

**Issue by nataliegrillon** [open-apparel-registry/open-apparel-registry#489]
## Overview

Users continue to put their personal name rather than the organization or full contributor name in the "Contributor Name" Field on the registration page. Suggest we change text from "Contributor Name" to " Contributor (Organization) Name"

### Expected Behavior

Users should opt for their organization name rather than their individual names to be listed on the site under contributor search field.

### Actual Behavior

Users are still listing their personal names rather than their organization's names

### Steps to Reproduce

n/a

### Demo

Optional. Screenshots, gifs, `curl` examples, console errors, log files, etc.

### Additional context

Optional. Add any other context about the problem here.

**Comment by jwalgran** [comment]
We added explanatory text as part of https://github.com/open-apparel-registry/open-apparel-registry/pull/622

<img width="888" alt="Screen Shot 2019-10-28 at 10 01 33 AM" src="https://user-images.githubusercontent.com/17363/67699888-1ffc7880-f96a-11e9-86fb-e550e2fc9dc0.png">
