### ISSUE TITLE
Claim a facility design

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#490]
## Overview

Hold meetings and document findings and implementation details for the claim a facility feature

### Describe the solution you'd like

- Planning meeting notes
- Feature request issues in github

**Comment by kellyi** [comment]
We met and generated a list of questions to help clarify how this feature should work.

I'm going to sketch out some hypothetical models related to claiming a facility and meet with Justin to discuss.

**Comment by kellyi** [comment]
Justin and I met & discussed some hypothetical models I diagrammed related to claiming a facility and thought through the implications of the feature a bit more.

I'm going to document what we discussed along with some revised hypothetical models in advance of further discussion.
