### ISSUE TITLE
Google descriptor of website is pulling through cookie info

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#491]
## Overview

The Google descriptor when you search OAR is pulling through cookie info. 

### Expected Behavior

The descriptor should contain our boilerplate text and keywords for OAR.

### Actual Behavior

Info is being pulled through which displays cookie info. 

### Steps to Reproduce

* Search Open Apparel Registry on Google. 

### Demo

![IMG_0259](https://user-images.githubusercontent.com/46344729/56568655-5f0ed300-65af-11e9-9dc1-bb7561c68a88.PNG)

### Additional context

@nataliegrillon The following text is taken from the Squarespace homepage - please flag if you'd like something different.

Please update text to:

The Open Apparel Registry (OAR) is an open source map and database of global apparel facilities, their affiliations and unique OAR IDs assigned to each facility.

**Comment by jwalgran** [comment]
I am merging this issue with #464 because adding the appropriate `<meta name="description>` tag to the page should give us control over the snippet that Google shows in their search results.
