### ISSUE TITLE
Investigate django-reversion & alternatives as possibilities for audit tracking model changes

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#500]
## Overview

As part of the claim a facility feature, we'll want to keep an audit trail of changes made to verified facility data, facility claims, and potentially other models.

We previously used django-reversion in another project, but that project was not used very heavily in production so we weren't fully able to evaluate it.

For this issue we should investigate django-reversion and some alternatives, including the possibility of writing our own implementation.

### Describe the solution you'd like

Investigate django-reversion and some alternatives, including the possibility of writing our own implementation. Document the outcome of the investigation and make a recommendation about how to proceed.

### Additional Context

We have previously used Django-Reversion.

OTM has a custom audit trail implementation.

We've also previously implemented a sort of audit log for the credit appeals tracking application.

We may want some sorts of changes -- such as changes to facility names -- to be full-text searchable.

**Comment by kellyi** [comment]
This has a pretty extensive list of alternatives: https://djangopackages.org/grids/g/model-audit/

**Comment by kellyi** [comment]
django-simple-history looks potentially interesting: https://django-simple-history.readthedocs.io/en/2.7.2/

**Comment by kellyi** [comment]
Trying out django-simple-history by applying it to the Facility table and then making edits through the Django admin:

Having the model opted into simple-history adds a `History` button for the object in the Django admin UI:

![Screen Shot 2019-05-13 at 2 16 29 PM](https://user-images.githubusercontent.com/4165523/57644359-f1d8d700-7589-11e9-8ec8-e0d787eb9f96.png)

Clicking on history shows an audit log:

![Screen Shot 2019-05-13 at 2 18 41 PM](https://user-images.githubusercontent.com/4165523/57644397-06b56a80-758a-11e9-9a05-20c84d59a191.png)

Going to check what's stored in the audit log table and also whether it's possible to enable reverting through the Django admin UI.

**Comment by kellyi** [comment]
![Screen Shot 2019-05-13 at 2 38 09 PM](https://user-images.githubusercontent.com/4165523/57645654-c3103000-758c-11e9-9556-f11a43369420.png)

Is the custom UI. Clicking on one of the list items gives you the option to revert to it:

![Screen Shot 2019-05-13 at 2 38 51 PM](https://user-images.githubusercontent.com/4165523/57645706-dde2a480-758c-11e9-82a9-7e23e293cc5b.png)

Reverting conses a new entry to the list:

![Screen Shot 2019-05-13 at 2 39 41 PM](https://user-images.githubusercontent.com/4165523/57645753-fa7edc80-758c-11e9-85ac-ef884f04553f.png)

The model that's been opted in will now have a `.history` queryset available, and you can walk through the history for each object by doing `prev_record` or `next_record`:

![Screen Shot 2019-05-13 at 2 42 38 PM](https://user-images.githubusercontent.com/4165523/57645986-93155c80-758d-11e9-9074-1f143d3e62b2.png)

**Comment by kellyi** [comment]
Tried out opting the contributor model into this and then making changes via the profile page and also via the django admin. It correctly recorded the user responsible for each change:

![Screen Shot 2019-05-13 at 3 14 26 PM](https://user-images.githubusercontent.com/4165523/57647784-e5f11300-7591-11e9-9e21-1706e99116b8.png)

**Comment by kellyi** [comment]
There's an `update_change_reason` utility function which enables recording the change reason:

```
diff --git a/src/django/api/views.py b/src/django/api/views.py
index 0215273..f5a5732 100644
--- a/src/django/api/views.py
+++ b/src/django/api/views.py
@@ -28,6 +28,7 @@ from rest_auth.views import LoginView, LogoutView
 from allauth.account.models import EmailAddress
 from allauth.account.utils import complete_signup
 import coreapi
+from simple_history.utils import update_change_reason
 
 from oar.settings import MAX_UPLOADED_FILE_SIZE_IN_BYTES, ENVIRONMENT
 
@@ -230,6 +231,8 @@ class UserProfile(RetrieveUpdateAPIView):
             user_contributor.other_contrib_type = other_contrib_type
             user_contributor.save()
 
+            update_change_reason(user_contributor, 'User edited the contributor profile page.')
+
             if new_password != '':
                 user_for_update.set_password(new_password)
 ```

![Screen Shot 2019-05-13 at 3 40 05 PM](https://user-images.githubusercontent.com/4165523/57649197-9280c400-7595-11e9-8715-e2a4983cf1c1.png)

I haven't been able to find an easy way to toggle it "on" for the built-in Django admin display, but conceivably we can build a custom template to use which included that as a field.

**Comment by kellyi** [comment]
Although it is not immediately surfaced in the UI, it appears that simple-history also enables restoring deleted objects from backups by reverting even though the deleted object no longer exists.

After deleting one:

![Screen Shot 2019-05-13 at 4 12 30 PM](https://user-images.githubusercontent.com/4165523/57650930-00c78580-759a-11e9-8ba8-49cd92890b93.png)

You can still visit a URL like http://localhost:8081/admin/api/contributor/100/history/ and see the audit log:

![Screen Shot 2019-05-13 at 4 13 25 PM](https://user-images.githubusercontent.com/4165523/57650946-1046ce80-759a-11e9-85fb-88d5258f779f.png)

And then restore it to whatever point, which will create a new object:

![Screen Shot 2019-05-13 at 4 14 02 PM](https://user-images.githubusercontent.com/4165523/57650973-248acb80-759a-11e9-94bd-3dd69524a797.png)

**Comment by kellyi** [comment]
I checked to see what happens to in migrations when a field is added or changed in a model with a related `Historical...` model because I was curious what would happen when reverting to an object from before a migration. Adding a field and then running `makemigrations` will automatically update the `Historical...` model, too:

```
# Generated by Django 2.0.13 on 2019-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190513_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='hello',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcontributor',
            name='hello',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
```

and then I assume we would just write the forwards function as usual.

**Comment by kellyi** [comment]
I tried out Django-Reversion a bit (and re-read the ADR we wrote about it for another project) and it seems like it works similarly with one major positive and one major drawback:

The positive is that it groups changes made simultaneously to multiple models into "revisions" which can be rolled back together like a transaction or a git commit. We would have to write custom code for this in django-simple-history.

The drawback is that it appears not to support revering objects across migrations. In this issue -- https://github.com/etianen/django-reversion/issues/643 -- the maintainer notes typically deleting revisions when changing a model via migration, but that that won't work for treating this as an audit trail.

**Comment by kellyi** [comment]
# Django Audit Libraries

For this issue I evaluated two Django auditing libraries for use in OAR as a
means of creating an audit trail of changes to existing models:

- [django-reversion](https://github.com/etianen/django-reversion)
- [django-simple-history](https://github.com/treyhunner/django-simple-history)

I created branches of OAR on my workstation to try installing and using both of
them, then registered the `Facility` and `Contributor` models to keep auditing
records and tried out making changes through the OAR application and through
the Django admin on each branch.

We had previously evaluated both of them as options for creating an audit trail
and version history on a closed-source project, opting there to use
django-reversion because it enabled gathering sets of changes to related models
into "revisions" which could be reverted simultaneously.

For OAR I recommend that we use django-simple-history specifically because the
library enables us to directly interact with historical versions of model
instances and enables keeping those historical model instances in a revertable
state across migrations: in other words, these instances will remain revertable
even if a migration has caused a model's fields to have changed in some way.
Neither of these features are available with django-reversion.

## [django-reversion](https://github.com/etianen/django-reversion)

django-reversion is very easy to install and we have previous experience using
it on a closed-source project. Enabling it entails decorating models with a
`register()` call, after which changes to those models will be stored in a
`Revision` table as a JSON string. The library has some associated templates
which can be included in the Django Admin to enable viewing historical model
instances, reverting to prior versions of model instances, and restoring
deleted model instances.

The library seems to have two big quirks which would make it difficult to use
here:

- since revisions are stored as JSON strings, it's not possible to interact
with them directly the way one would interact with a `Facility` model instance.

- likewise, migrations made to a model instance are not also directly applied
to prior revisions -- which makes it not easy to revert across migrations.

## [django-simple-history](https://github.com/treyhunner/django-simple-history)

django-simple-history is also extremely easy to install. In place of decorating
models, one adds a

```
history = HistoricalRecords()
```

field to any model one wants to opt into simple-history, then runs a migration.
For `Facility`, this would create a sibling `HistoricalFacility` model in which
stored prior Facility objects. One can interact with the model & its objects
the same way one would interact with `Facility`, and there are some extra
method fields which allow one to find the previous or next historical instance.

Creating a migration for models with `HistoricalRecords()` set will also update
the related `Historical...` model: for example, adding a field to `Facility`
and then creating a migration will also add that field to `HistoricalFacility`.
This makes it possible to revert to historical instances stored prior to a
migration.

Like django-reversion, django-simple-history also has templates for the Django
Admin which enable viewing and reverting changes. Reverting to a prior instance
will actually create a new `Historical...` record, so the intervening instances
won't get discarded.

Each `Historical..` model instance also has a `changeReason` text field which
can be used to add a reason -- either programmatically or from user input --
for the change.

**Comment by jwalgran** [comment]
Excellent writeup 👍
