### ISSUE TITLE
High pageCount for /facilities endpoint causes service deadlock

### ISSUE THREAD

**Issue by hectcastro** [open-apparel-registry/open-apparel-registry#501]
## Overview

When a high `pageCount` is supplied to the `/facilities` endpoint, the application server spins and eventually gets taken offline (runs out of resources?).

### Expected Behavior

Supplying a large `pageCount` should not cause the application services to deadlock.

### Actual Behavior

Supplying a large `pageCount` (12737) to the application services causes the service to deadlock.

### Steps to Reproduce

* Navigate to https://staging.openapparel.org/api/docs/#!/facilities/facilities_list
* Use 12737 for `pageCount`; click Try it out
* Observe application service deadlock

**Comment by jwalgran** [comment]
We did follow the DRF documentation and declare a pagination class with a `max_page_size`
https://github.com/open-apparel-registry/open-apparel-registry/blob/956c17ff22ef7850e83a9e90b77013f0057ecfe5/src/django/api/pagination.py#L8

And declare in our settings that it should be used as the default
https://github.com/open-apparel-registry/open-apparel-registry/blob/956c17ff22ef7850e83a9e90b77013f0057ecfe5/src/django/oar/settings.py#L130

This may not be wired up completely correctly, or it is not rejecting invalid page sizes as I would have expected. This is where I would start investigating the issue.

**Comment by kellyi** [comment]
Appears that the max page size setting isn't being observed:

![Screen Shot 2019-05-13 at 5 12 00 PM](https://user-images.githubusercontent.com/4165523/57654490-4daf5a00-75a2-11e9-9df6-868729c48b13.png)

**Comment by kellyi** [comment]
Turns out that while we had set a `page_size` for the facilities geojson response, we did not set a `max_page_size`. Going to set that to be the same as the default.
