### ISSUE TITLE
Show a count of the total number of facility list items in each workflow status

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#502]
## Overview

Show a count of the total number of facility list items in each workflow status

### Describe the solution you'd like

* Count the number of items in each status and return them from the facility list API (be mindful of the NEW_FACILITY "meta-status")
* Show the counts on the facility list page
* Add help text explaining what each status means. Show it in a popover when hovering, clicking on a status count

**Comment by kellyi** [comment]
I tried out adding every status in table cells but it's going to be tough to fit them all, even after increasing the table width:

![Screen Shot 2019-05-14 at 2 38 50 PM](https://user-images.githubusercontent.com/4165523/57723235-35007c00-7656-11e9-9c0d-e4a6cb8420cf.png)

It seems like the most important info to surface here would be the number of `POTENTIAL_MATCH`es, as that's the thing that's actionable via the UI.

It seems like it might be worthwhile to fuse the following sets of statuses for display in this UI into one column for each set:

- `MATCHED`, `CONFIRMED_MATCH`, and `NEW_FACILITY`
- all the `ERROR...` statuses
- `GEOCODED` and `GEOCODED_NO_RESULTS`

**Comment by kellyi** [comment]
Aggregates:

![Screen Shot 2019-05-14 at 2 51 47 PM](https://user-images.githubusercontent.com/4165523/57723989-d3411180-7657-11e9-9b51-8070d07f07d3.png)

**Comment by kellyi** [comment]
![Screen Shot 2019-05-14 at 3 24 43 PM](https://user-images.githubusercontent.com/4165523/57725974-6e3bea80-765c-11e9-8017-8344578f51b5.png)
![Screen Shot 2019-05-14 at 3 24 47 PM](https://user-images.githubusercontent.com/4165523/57725976-6e3bea80-765c-11e9-929e-0b0abf1cd472.png)

**Comment by jwalgran** [comment]
Grouping the statuses makes sense in this context. 👍
