### ISSUE TITLE
Allow free text search of facility list items

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#503]
## Overview

On the facility list details page, allow free text searching of names and addresses.

### Describe the solution you'd like

* Add a `search` parameter to the `/api/facility-lists/{id}/items/` API endpoint
  * Filter the results based on a basic case-insensitive substring match against the name and address
* Add a search text box to the facility list page. Pass its value to the API as the `search` parameter 
* Add a reset / show all button that clears the search.

**Comment by rajadain** [comment]
Where should I add the search box? Beside the filter box (and the related controls) (red) or below it (blue)?

![image](https://user-images.githubusercontent.com/1430060/58499061-5892ee80-814d-11e9-99f5-f35125664011.png)

**Comment by jwalgran** [comment]
My first instinct is to put it before the status filter dropdown (orange arrow)

![search](https://user-images.githubusercontent.com/17363/58501061-5bcfaf80-8138-11e9-8ca8-ca86e42a4ec1.png)

The label and button to the right of the status filter dropdown disappear. The left edge is a less volatile location

Putting it on a new line is also less volatile but it may look a little unbalanced and it pushes the start of the actual content even further down the page.
