### ISSUE TITLE
Release 2.4.0

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#522]
- [x] Start a new release branch:
```bash
$ git flow release start 2.4.0
```
- [x] Rotate `CHANGELOG.md` (following [Keep a Changelog](https://keepachangelog.com/) principles)
- [ ] Ensure outstanding changes are committed:
```bash
$ git status # Is the git staging area clean?
$ git add CHANGELOG.md
$ git commit -m "2.4.0"
```
- [x] Publish the release branch:
```bash
$ git flow release publish 2.4.0
```
- [x] Test the release branch on staging
- [x] Start a new [release pipeline job](http://civicci01.internal.azavea.com/view/oar/job/Open%20Apparel%20Registry%20Release%20Pipeline/build?delay=0sec) with the SHA (see command below) of `release/2.4.0` that was tested on staging
```bash
$ git rev-parse --short HEAD
```
- [x] Run migrations, if applicable (see the `showmigrations` release pipeline stage):
```bash
$ ./scripts/manage.py ecsmanage -e production migrate
```
- [x] Run the django-simple-history management command to create initial versions of existing facilities (https://django-simple-history.readthedocs.io/en/2.7.2/quick_start.html#existing-projects)
**Note** Running this management command requires passing an `--auto` flag, which means we cannot use the current version of `ecsmanage`, which tries to interpret this flag rather than pass it along.
- [x] Finish and publish the release branch:
    - When prompted, keep default commit messages
    - Use `2.4.0` as the tag message
```bash
$ git flow release finish -p 2.4.0 
```

**Comment by kellyi** [comment]
I created this issue to document that django-simple-history has some additional work to get set up. https://github.com/open-apparel-registry/open-apparel-registry/pull/521 adds a migration to run to create a `HistoricalFacility` model.

There is also a Django management command to set up `HistoricalFacility` objects from the existing `Facility` objects:

https://django-simple-history.readthedocs.io/en/2.7.2/quick_start.html#existing-projects

**Comment by jwalgran** [comment]
I added a checklist item to the issue description, noting that we can't use `ecsmanage`.
