### ISSUE TITLE
Discuss addressing matching algorithm

### ISSUE THREAD

**Issue by hectcastro** [open-apparel-registry/open-apparel-registry#53]
Set aside to consult with @jeancochrane regarding her past experience with addressing matching.

@mmcfarland, is there a good place to get familiar with the OAR specific address matching problems?

**Comment by jeancochrane** [comment]
Had a short meeting this morning to assess preliminary steps for address matching. My high-level takeaways were:

* Ideal solution: probablistic fuzzy matching, likely with Dedupe library
    * Concerns include:
        * Built-in usaddress address parser may not work for international addresses, in which case we'd have to build a custom address parser (probably on top of pypostal)
        * Unclear how this would scale to a large (>1 million rows) master list
        * Library has a steep learning curve
* Naive solution: address normalization, likely with libpostal/pypostal, plus simpler matching rules like string distance
    * Concerns include:
        * Not terribly different from what old vendor was doing; may not improve performance much
* Solution I haven't tested: lieu library for address deduplication
* Next steps:
    * Evaluate potential solutions in sandboxed environment
    * Implement the simplest working solution for February scope, and focus on ironing out UI bugs; save the best-case, high-risk solution for a larger scope

**Comment by jwalgran** [comment]
@kellyi @mmcfarland @jeancochrane please let me know if you have any corrections to my discussion [notes](https://github.com/open-apparel-registry/open-apparel-registry/issues/53#issuecomment-456510086) or if I have omitted anything. Thanks.

**Comment by jwalgran** [comment]
Thanks for including your notes, Jean. They line up with mine and provide some valuable extra detail.
