### ISSUE TITLE
Data fields for claiming a facility

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#533]
## Overview

Facility owners/managers need to provide additional details when claiming a facility. 

### Is your feature request related to a problem? Please describe.

Facility owners/managers must provide information in order to verify they are facilities owners and add information to display as part of the facility profile.

### Describe the solution you'd like

Possible fields include the options below. Only login name, email address of facility, and official name of LLC or facility registered would be required.

Login Name
Email
Phone number
Contact email (if different from email they’ve registered the account with) 
Website
Address of office
Region
Country
Address of facility
Region 
Country
Latitude and longitude
Bio - tell us more about your facility
Official name of LLC or company registered 
Owner name
Contact person name
Certifications
Type of products they make 
Type of production they do on site
Minimum Order quantities
Average lead time
Trade association membership?
Any other information

### Additional Context

This list is subject to change based on feedback from the facilities. We would like to show them the field within the context of the wireframes.

**Comment by dboyer** [comment]
@designmatty See list of possible facility related fields in this issue.

**Comment by jwalgran** [comment]
Claim fields were implemented and revised

https://github.com/open-apparel-registry/open-apparel-registry/pull/575
https://github.com/open-apparel-registry/open-apparel-registry/pull/650
