### ISSUE TITLE
Prevent users who have a pending claim on a facility from submitting another claim on that facility

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#555]
## Overview

Prevent users who have a pending claim on a facility from submitting another claim on that facility

Depends on #515 

### Describe the solution you'd like

Two options I imagined:

1. adjust the facility details serializer to also send back a list of contributor IDs who have pending claims on the facility, then show a "you have already submitted a claim for this facility" notice if the currently-signed-in contributor is in that list

2. adjust the user serializer to include a list of the facilities a user has claimed and then show the same "you have already submitted a claim" notice, but this time checking the OAR ID against the current facility details ID

Option 1 is technically easier but unfortunately seems to leak some information, so option 2 might be preferable.

**Comment by jwalgran** [comment]
I agree that "adjust the user serializer to include a list of the facilities a user has claimed" is a preferable approach.

**Comment by kellyi** [comment]
As part of this work we should also make the following updates to the API endpoint:

- the server endpoint should reject posted facility claims when the user sending the claim already has a pending claim
- the server endpoint should also reject posted facility claims when there is already an approved facility claim for that facility
