### ISSUE TITLE
URLs Should Represent Application State

### ISSUE THREAD

**Issue by rajadain** [open-apparel-registry/open-apparel-registry#560]
## Overview

Currently, the routing mechanism matches the most it can and ignores the rest. For example, `/dashboard`, `/dashboard/abc`, and `/dashboard/xyz` all route to the same page. This is because `/dashboard` is a real route, and the rest is ignored.

But this is confusing, because the user doesn't know what is being ignored. They may associate the ignored parts of the route with some meaning.

To prevent this, we should have the URLs always represent the present app state. Thus, if a URL has parts of a route that should be ignored, then they should also be discarded. In this way, all three of the above routes would "redirect" to `/dashboard`.

### Expected Behavior

When the user goes to `/dashboard/abc`, the URL should become `/dashboard`.

### Actual Behavior

When the user goes to `/dashboard/abc`, the URL stays the same, but the route of `/dashboard`.

### Steps to Reproduce

* Go to `/dashboard/abc`
* See the URL does not change

### Demo

![image](https://user-images.githubusercontent.com/1430060/58904113-dbc7bd80-86d4-11e9-863b-7e3cdbc2800e.png)

### Additional context

Original Discussion here: https://github.com/open-apparel-registry/open-apparel-registry/pull/557#issuecomment-498776435

**Comment by kellyi** [comment]
Instead of programmatically redirecting, I think it'd be simper to just have non-existing routes show `NoRouteMatch`. That'd prevent needing to add machinery for doing the redirects and minimize changes to just the existing `Switch` components.

**Comment by kellyi** [comment]
Superseded by #621
