### ISSUE TITLE
The profile page for a non-existant contributor ID should say not found

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#565]
## Overview

The profile page for a non-existent contributor ID shows empty fields rather than not found

### Expected Behavior

Loading the profile page for non-existent contributor ID shows the standard not found page

### Actual Behavior

A few empty fields are shown

### Steps to Reproduce

* Browse http://localhost:6543/profile/987654321

### Demo

<img width="1056" alt="Screen Shot 2019-06-07 at 8 29 34 AM" src="https://user-images.githubusercontent.com/17363/59115623-840c9a80-88fe-11e9-89bc-78809d05c86d.png">

**Comment by kellyi** [comment]
Shares points with https://github.com/open-apparel-registry/open-apparel-registry/issues/569
