### ISSUE TITLE
Add Terraform configuration for ECR; publish container images to ECR from CI

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#58]
* Bootstrap `deployment/terraform` directory structure and initialize Terraform S3 backend
* Add `infra` script
* Using https://github.com/azavea/terraform-aws-ecr-repository, instantiate an ECR repository
* Add `cipublish` script that publishes container images to ECR
* Add support for `cipublish` and `infra` stages in `Jenkinsfile` (gated to develop and release branches)

**Comment by jwalgran** [comment]
We will be going with AWS. See #68.
