### ISSUE TITLE
Add Terraform configuration for staging environment

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#59]
* ECS with Fargate
* Include VPC with [terraform-aws-vpc](https://github.com/azavea/terraform-aws-vpc)
* Include PostgreSQL RDS with [terraform-aws-postgresql-rds](https://github.com/azavea/terraform-aws-postgresql-rds)
* Include log aggregation with CloudWatch Logs
* Layer in CloudFront distribution to front ALB

The result should essentially mirror the Terraform configuration in https://github.com/azavea/maiden.

**Comment by jwalgran** [comment]
We will be going with AWS. See #68.
