### ISSUE TITLE
Associate AWS environments with OAR provided domains

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#60]
The `openapparel.org` domain was transferred and lives in our name.com account (which is in LastPass).

* Ask in `#oar` if it'd be acceptable to change the nameservers on the domain (this would take down Sourcemap's instance of the Open Apparel Registry)
* Setup Route 53 hosted zone 
* Modify existing (if any) Terraform configuration

**Comment by jwalgran** [comment]
We will be going with AWS. See #68.

**Comment by hectcastro** [comment]
Resolved through https://github.com/open-apparel-registry/open-apparel-registry/issues/95.
