### ISSUE TITLE
Contributor names and type in the filter dropdowns are being translated

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#606]
## Overview

Contributor names and types in the filter dropdowns are being translated. The translate library tries to translate all text on a page unless it encounters a a `notranslate` class.

### Expected Behavior

Contributor names and types are not translated in the map page filter dropdown.

### Actual Behavior

Contributor names and types are translated in the map page filter dropdown.

### Steps to Reproduce

* Browse the map page
* Choose a non-English language
* Open the contributor filter dropdown
* Open the contributor type dropdown

### Demo

<img width="528" alt="Screen Shot 2019-06-17 at 7 43 16 AM" src="https://user-images.githubusercontent.com/17363/59614607-f5560580-90d5-11e9-9e10-29dacf585c1a.png">

<img width="237" alt="Screen Shot 2019-06-17 at 7 57 24 AM" src="https://user-images.githubusercontent.com/17363/59614701-17e81e80-90d6-11e9-8464-0812f52c9789.png">

### Additional context

It looks like setting the `notranslate` class on parent element applies to all child elements, so this should be a relatively simple fix.

**Comment by kellyi** [comment]
Shares points with https://github.com/open-apparel-registry/open-apparel-registry/issues/569
