### ISSUE TITLE
Text Changes for Claim a Facility Feature

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#607]
## Overview

Text changes for Claim a Facility feature. Here are places where we display text:

- facility claim wizard form
- claimed facility profile form
- email sent for claim a facility form submission
- email sent for FacilityClaim status change
- email sent to contributors on approving a facility claim
- email sent to contributors on the claimed facility profile data changing
- details sidebar for claimed facilities

### Describe the solution you'd like

- [x]  On edit version of facility profile page, add "If different from facility address" next to "office information" section

- [x] The below text should be at /about/claimedfacilities and at the top of Step 1 in the claim a facility process. If it's too lengthy to fit there, could we have an initial text page in the wizard that people read before proceeding to Step 1?

<b> The Claim a Facility function </b>
Owners or senior management at facilities listed on the OAR are able to “claim” their facility’s profile on the site and add business information to it. 

If you are a facility owner or senior management, please work your way through the following three preliminary steps to verify your identity. This process should take no more than 5 minutes to complete.

Once your claim has been reviewed and approved, you will be able to:

- Update facility location and address details
- Specify production details and certifications
- Share order minimums and average lead times
- Add information about your head office and parent company

This information will be shown publicly on the facility details page. 

<b> Disclaimer </b>
For verified facility claims, OAR staff has verified through a three-step process that the claimant has a genuine connection to the facility it is claiming and sufficient authority to make the claim. However, OAR staff does not verify each detail the claimant subsequently adds about a facility, e.g. production capabilities, certifications, MOQs etc.

If you believe that some claimed facility data is inaccurate or incorrect, please send an email to info@openapparel.org with a link to the facility details page and an explanation of the problem.

- [x] In claim a facility process step 4, text should say:

Your request to claim the facility was submitted successfully! To manage the profile information for your facility, we'll need to verify your connection to the facility. Once verified, you will be able to:

- Update facility location and address details
- Specify production details and certifications
- Share order minimums and average lead times
- Add information about your head office and parent company

- [x] My claimed facilities page - https://staging.openapparel.org/claimed - text should read:

You do not have any approved facility claims. Search for your facility and make a request to claim it. Claiming your facility will enable you to add business information, including production details, certifications, minimum order quantities and lead times.

- [x] On facility details sidebar in owner view, replace “Update this facility” with “Update facility details”

- [x] Add "Best wishes," as the valediction before Open Apparel Registry at the end of each email

- [x] At the end of the claimed facility approval email, use this text:

Here's the reason for the approval:
 
You are approved! You can now complete your profile, adding business information including production capabilities, certifications, MOQs and more. Visit openapparel.org/claimed to view your approved facility and complete your profile.
 
Best wishes,
Open Apparel Registry

- [x] At the end of the claimed facility denial email, use this text:

Here's the reason for the denial:

The claim information is inaccurate. If you believe this denial to be inaccurate, you can reach out to the OAR team to provide additional, clarifying information at: info@openapparel.org The team will review your claim and get back to you.

Best wishes,
Open Apparel Registry

- [x] At the end of the claimed facility revocation email, use this text:

Here's the reason for it was revoked:

We have discovered your claim is actually inaccurate. If you believe your claim should not have been revoked, you can reach out to the OAR team to provide additional, clarifying information at: info@openapparel.org The team will review your claim and get back to you.
 
Best wishes,
Open Apparel Registry

**Comment by kellyi** [comment]
@dboyer question about the email updates to change the "reason":

The current behavior is that the status change reason is written on the dashboard page by an administrator, then sent through to the recipient in the email. In #642 I replaced displaying this with the updated text above for the approve, deny, and revoke emails, but I wanted to double check that we should replace the administrator-written status change reason with the text above instead of:

- showing both the text above along with the administrator-written status change reason
or
- showing the administrator-written status change reason or, if it doesn't exist, then show the text above

**Comment by dboyer** [comment]
@kellyi In reading this again, I think I know the answer. We should place the administrator-written status change reason in the space after the colon (e.g. "Here's the reason for the denial: Your website doesn't work and we can find no proof of your existence").

Then include the next paragraph ("The claim information is inaccurate....") by default.

**Comment by kellyi** [comment]
Great, thanks! I'll set it up to work that way.
