### ISSUE TITLE
Facility claim API does not have API documentation

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#613]
## Overview

The facility claim API does not have API documentation.

### Expected Behavior

The API documentation for the claim endpoint includes a description and a sample request

### Actual Behavior

The default text from the FacilitiesViewSet is shown

### Steps to Reproduce

* Browse http://localhost:8081/api/docs/#!/facilities/facilities_claim

### Demo

<img width="1174" alt="Screen Shot 2019-06-17 at 3 07 25 PM" src="https://user-images.githubusercontent.com/17363/59640003-ab8b1080-9111-11e9-9b52-13b6a7ab50e1.png">

**Comment by kellyi** [comment]
Alternatively: we could also just remove the claimed endpoints from the API docs.

**Comment by kellyi** [comment]
Shares points with https://github.com/open-apparel-registry/open-apparel-registry/issues/569
