### ISSUE TITLE
Add a parent company to claim and allow it to be edited on the profile

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#618]
## Overview

Add a "Parent Company" field to both the claim form and the profile form where the claimant can select a single, existing `Contributor` from a select box. Show the name of the contributor on the facility details page as a link to a search of all of the facilities for that Contributor.

### Describe the solution you'd like

- Add a nullable `parent_company` to the claim as a foreign key to `Contributor`. PROTECT on delete.
- Add a non-required choice field to the claim form to allow selecting a `Contributor`.
- Ad a non-required choice field to the profile form that allows editing the `Contributor`
- If a `parent_company` is specified, show a link on the facility details page. Clicking the link runs a search for all of that contributors facilities.

### Additional Context
<img width="513" alt="Screen Shot 2019-06-21 at 8 31 00 AM" src="https://user-images.githubusercontent.com/17363/59933944-3d8b6580-93ff-11e9-9229-43c1103bd033.png">

**Comment by kellyi** [comment]
For this we're going to have to move the place where we call the fetch contributors options function. It currently is only called on the `/` and `/facilities/` routes, but not the facilities detail route or the claims route. I think we can just move it up to the top level of the app and have it live there.
