### ISSUE TITLE
Add support for Rollbar on Django

### ISSUE THREAD

**Issue by rbreslow** [open-apparel-registry/open-apparel-registry#62]
See: https://docs.rollbar.com/docs/python/

**Comment by hectcastro** [comment]
Ensure that we create a new Rollbar account specifically for OAR.

**Comment by jwalgran** [comment]
My `jwalgran` Rollbar account does not have access to OAR yet. Could I please be added to the team?

![Screen Shot 2019-02-07 at 1.24.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5411f642c8d7f1020040676f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216454f46b7191a379f1102f4f5a565ecc3c4a4356bcbbd671f3e57862804e0ee8833c5771c13811aabc8349ed05be208b4bd1b0edd919d2f42f67b6d5db1063474f4dcbed5727a19141c95df242e44a54a5103666ee722431.png)

**Comment by rbreslow** [comment]
* I created a new Rollbar account named `OpenApparelRegistry`
* I created a new Rollbar project named `OpenApparelRegistry`
* I added `hcastro@azavea.com` to the `Owners` team
* I setup a source control integration with our GitHub organization with a default branch of `develop`
* I disabled email notifications
* I configured Slack notifications to post to the #oar Slack channel
* I removed `New Version` notifications
* I added a `Deploy -> Post Message` notification for the `staging` environment
* I added `10^nth Occurrence` notifications
* I added the Rollbar server side access token to the staging `terraform.tfvars` file
