### ISSUE TITLE
Log all non-app API requests in the database by  user ID

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#637]
## Overview

Depends on #636

To allow reporting on API usage, log all requests made with an API token to the database.

### Describe the solution you'd like
- Create a `RequestLog` table
  - ~`requested_at`~ `created_at` timestamp (opted to reuse our conventional timestamp field name)
  - `user_id` FK to api_user, indexed, cascade delete
  - `token` indexed ~(both alone and compound index with user_id)~ (Opting to not add speculatively add a multicolumn index) NOT an FK because tokens can be rotated.
  - `url` string
  - `response_code` int
- Create middleware (https://docs.djangoproject.com/en/2.2/topics/http/middleware/#writing-your-own-middleware) that writes a row to the table if an API request is made with a token

**Comment by hectcastro** [comment]
Do we have a sense for how many requests this will be? Surfacing minor concern over the possibility of:

- Adding functionality that could lead to a large database table (over time)
- Introduces a step in the request/response cycle that has the potential to compromise the success of a request if this particular step fails

**Comment by jwalgran** [comment]
Thanks for raising these concerns. 

We don't know just how successful our APIs will be, but we are actively engaged with multi-supplier initiatives to build integrations with their systems. I would guess the order of magnitude would be thousands per week.

We are obligated to report on API usage to our stakeholders, so we need to keep a count somewhere. I don't think we can avoid introducing a step in the request/response cycle, but I would definitely want to implement it so that a failure to count does not fail the request. 

I'm open to using an alternate data store. We don't need real time access to these counts so that could give us some flexibility.

One advantage to using the database is that we can maintain a foreign key to the user table and cascade delete when and if a user exercises their "right to be forgotten" under the GDPR.

**Comment by hectcastro** [comment]
Thanks for the follow-up. Not super interested in pursuing an alternate data store at this time. GDPR makes it difficult to use the existing logging structure, which would have been great to reuse. I guess we just need to keep an eye on the size of this table over time.
