### ISSUE TITLE
Add Product Type field to claim a facility profile

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#651]
## Overview

Add Product Type field to claim a facility profile

### Describe the solution you'd like

Add Product Type field to claim a facility profile

We'll need to clarify how the Product Type field should work. We've discussed making it have a user-generated set of tags including some derived from pre-seeded values, but we'll need to make sure that that's correct before adding it.

Per #617, "Product Type" should appear between "Facility Type" and "Production Type" on the list of claimed facility fields displayed on the facility details page.

**Comment by jwalgran** [comment]
>a user-generated set of tags including some derived from pre-seeded values

This is correct. We will be allowing arbitrary values as tags and we will be providing an auto-completing list list of suggested tags derived from:
- A static table of well-known products
- Tags entered by other facility claimants.

@dboyer please double-check my description of the feature.

**Comment by dboyer** [comment]
That is correct. I've asked N/K for a list of values with which to seed the lists.

**Comment by dboyer** [comment]
Initial items. Users can add to this list. Please alphabetize it.

Accessories
Bags & Soft Cases 
Belts 
Caps 
Fur 
Gloves 
Handbags 
Head Bands 
Headwear 
Leather Goods 
Leggings 
Legwear 
Neckwear/Ties 
Robes 
Scarves 
Socks/Hosiery 
Active Wear
Bike Shorts 
Body Wear 
Bra Tops 
Dance Exercisewear 
Flatlock Activewear 
Golf 
Jogging Suits 
Swimwear 
Evening
Bridal 
Cocktail Dresses 
Couture 
Evening Dresses 
Home
Aprons 
Bedskirts 
Bumpers 
Chair Covers 
Comforters 
Curtains 
Decorative Pillows 
Infant/Baby Bedding 
Sheets 
Table Cloths 
Innerwear/Lingerie
Boxer Shorts 
Bras 
Briefs 
Robes 
Sleepwear 
Slips 
Knits
Fleece Bottoms 
Fleece Tops 
Full/Half Zips 
Hand Loomed Knitwear 
Knit Headwear 
Knit Shirts/Tops 
Knit Tops 
Loungewear 
Polar Fleece 
Polo Shirts 
Sweaters 
T-Shirts 
Sportswear
Blouses 
Coats/Outerwear 
Denim Product 
Dress Shirts 
Dresses 
Pants 
Rainwear 
Shorts 
Skirts 
Unconstructed Jackets 
Vests 
Woven Shirts 
Tailored
Bottoms 
Formal Wear 
Jackets/Blazers 
Suits 
Uniforms
Athletic Uniforms 
Disposable Uniforms 
Workwear 
Footwear 
Costume 
Other
Lining
Buttons 
Trims
Zippers
Lace
Interlinings
