### ISSUE TITLE
Add Production Type field to claim a facility profile

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#652]
## Overview

Add Production Type field to claim a facility profile

### Describe the solution you'd like

Add Production Type field to claim a facility profile.

We'll need to clarify how this should work: will it be a select/option input from which the user chooses one of a pre-existing set of options or will it be a user-generated set of tags with pre-seeded values.

Per #617 the field should appear between "Product Type" and "Minimum Order Quantity" on the facility details screen's claimed section.

**Comment by dboyer** [comment]
The field should function the same as Product Type with a pre-seeded list of options to choose, the ability to create new options, and an auto-complete feature where we suggest previously chosen options when the user begins typing.

**Comment by dboyer** [comment]
Seeded list of options. Users can add others.

Cutting 
Denim Services 
Embroidery 
Fabric Dyeing 
Fabric Sourcing 
Fabric Weaving
Ginning 
Hand Sewing 
Knitting 
Laundry
Marker Making 
Packing
Pattern Grading 
Pattern Making 
Pleating 
Printing 
Sample Making 
Scouring
Sewing 
Shoe stitching
Spinning
Tanning
Trimming/Embellishment
