### ISSUE TITLE
Add Certifications to claimed facility profile

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#653]
## Overview

Add Certifications to claimed facility profile

### Describe the solution you'd like

Add Certifications to claimed facility profile. This should be a select/option input using React-Select with autocomplete. I believe it should also be a multiselect.

~We're waiting on the enumerated set of options, and~ I think we should treat it as a closed set for now.

Per #617 this should be displayed between "Percentage of Female Workers" and "Membership Bodies" in the facility details screen's claim info section.

**Comment by kellyi** [comment]
This is blocked because we are still awaiting the list of options.

**Comment by dboyer** [comment]
The following options should be listed in a drop-down. Users cannot add new options.

BCI
B Corp
Bluesign
Canopy
Cradle to Cradle
EU Ecolabel
FSC
Global Recycling Standard (GRS)
GOTS
Green Screen for Safer Chemicals
Higg Index
IMO Control
International Wool Textile Organisation (IWTO)
ISO 9000
IVN leather
Leather Working Group
Nordic Swan
Oeko-Tex Standard 100
Oeko-Tex STeP
Oeko-Tex Made in Green
Oeko-Tex Eco Passport
PEFC
REACH
Responsible Down Standard (RDS)
Responsible Wool Standard (RWS)
SA8000
Soil Association Organic
Tessile e Salute
USDA Biobased
Woolmark
Worldwide Responsible Accredited Production (WRAP)
Zero Discharge of Hazardous Chemicals (ZDHC) Gateway

**Comment by dboyer** [comment]
@kellyi The field name should be changed to Certifications/Standards/Regulations
