### ISSUE TITLE
Add Affiliations field to claim a facility profile

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#654]
## Overview

Add Affiliations field to claim a facility profile

### Describe the solution you'd like

Add Affiliations field to claim a facility profile

This should be a select/options input using React Select, likely a multiselect. ~We're awaiting the list of options to include~, but I believe we should treat it as a closed/fixed set and not allow free-form user input.

Per #617 this should be displayed between "Certifications" and "Office Info" on the facility details screen's claim info section.

**Comment by kellyi** [comment]
This is blocked because we are awaiting the list of options.

**Comment by dboyer** [comment]
These options should be available in a drop-down. Users cannot add other options.

Benefits for Business and Workers (BBW)
Better Mills Programme
Better Work (ILO)
Canopy
Ethical Trading Initiative
European Outdoor Group
Fair Labor Association
Fair Wear Foundation
SEDEX
Social and Labor Convergence Plan (SLCP)
Sustainable Apparel Coalition
Sweatfree Purchasing Consortium

**Comment by dboyer** [comment]
@kellyi The field name should be changed to Affiliations
