### ISSUE TITLE
Decide where we will deploy staging and production

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#68]
## Overview

Decide on the deployment environments for staging and production.

### Describe the solution you'd like

The two options are Heroku and AWS. Dev and Ops should collaborate to determine which service we will use for staging and production.

#### Considerations
  - Background processing of uploaded files. If we use Celery, what will we use for the broker?
  - Cost.

**Comment by jwalgran** [comment]
A primary reason for considering Heroku was for simplified managed hosting of services that Azavea has little to no experience deploying and maintaining (MongoDB, Elasticsearch). We have since decided to rewrite the backend using the PostGIS/Python/Django/DRF stack and Azavea has extensive experience deploying and maintaining these services on AWS. As a result, we are opting to not take on the uncertainty of using Heroku for this project.

**Comment by hectcastro** [comment]
Thanks for summarizing your thoughts here, and I agree with your line of reasoning.
