### ISSUE TITLE
The map does not update when a filter is applied to a search

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#686]
## Overview

When a filter is applied to a set of search results, the list of facilities updates but the map does not. 

### Expected Behavior

The map should update in line with the facility list

### Actual Behavior

The map continues to show the results of the original search

### Steps to Reproduce

* Search by Contributor "AGT" and country "India"
* In the search results, enter the filter "Tamil Nadu"
* The list of facilities will update, but the map does not

### Demo

![Screenshot 2019-07-17 at 18 05 05](https://user-images.githubusercontent.com/46344729/61395484-6fd49980-a8bd-11e9-9a4c-3b67acf51d89.png)

### Additional context

The OAR stakeholder team was made aware of this bug by a site user.

**Comment by jwalgran** [comment]
The filter field was removed when we switched to the new map and switched to showing an infinite scroll list of all matching facilities.
