### ISSUE TITLE
Add bounding box search to facilities API endpoint

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#698]
## Overview

Add bounding box search capability to facilities API endpoint

### Is your feature request related to a problem? Please describe.

There's currently not really a way to search by subregion, such as searching for facilities within a specific province or state of a country. The UI only returns the first 500 results, but some countries have thousands of results. China, for instance, currently has 6300 facilities.

### Describe the solution you'd like

Add bounding box search param to the facilities API endpoint which will return only facilities whose locations are within the bounding box.

Looks like this is the filter arg: https://docs.djangoproject.com/en/2.2/ref/contrib/gis/geoquerysets/#bbcontains

### Additional Context

This card should only affect the API params; I'll create a separate issue for the UI.

**Comment by jwalgran** [comment]
Superceded by polygonal search #793.
