### ISSUE TITLE
Enable users to search for facilities by drawing a bbox on the map

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#699]
## Overview

Following https://github.com/open-apparel-registry/open-apparel-registry/issues/698 we should enable users to draw a rectangle on the map to be used for searching facilities using the bbox API query parameter.

### Is your feature request related to a problem? Please describe.

There is currently no good way to search facilities by subregion, and the single-country search results can return much more than the 500 facilities we're displaying in the UI. It'd be worthwhile for users to be able to narrow searches down geographically.

### Describe the solution you'd like

Once https://github.com/open-apparel-registry/open-apparel-registry/issues/698 has been completed:

- add a "Draw Bounding Box" button to the search filters sidebar somewhere, which has a button to toggle drawing a shape and a cancel/clear button for removing the client-box filter

![Screen Shot 2019-07-20 at 11 21 55 AM](https://user-images.githubusercontent.com/4165523/61580484-b0602d00-aae0-11e9-8906-e24ee2727667.png)

- persist the bbox somehow in the querystring params; this could just be a list of four coordinates like `&bbox=1,2,3,4`

- send the bbox to the API in the correct format, returning only facilities that are within the drawn shape

- when refreshing a URL that has the `&bbox` string applied, re-draw the bounding box on the map and indicate that it has been applied in the UI

### Additional Context

Without a drawn bbox we may want to consider having an implicit filter applied that would be the bbox comprising the map's existing scope. This would potentially be a way to solve https://github.com/open-apparel-registry/open-apparel-registry/issues/686

**Comment by dboyer** [comment]
FYI that we created a feature for OTM to draw a bounding box on the map. That code may be reusable.

**Comment by jwalgran** [comment]
Superceded by polygonal search #793
