### ISSUE TITLE
DRAFT: Support GPS alias

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#701]
# Draft

This is a draft issue, and it will need to clarify specs and formalize what
counts as "done" before work begins on it.

Check with the issue's creator before starting work on this issue.

## Overview

Users may submit alternative location suggestions when an on-the-ground audit results in geographic coordinates that differ from what Google's geocoder suggests. 

### Is your feature request related to a problem? Please describe.

Users occasionally contact us with suggested location coordinates. Our general policy is that contributors can add to facility info (a name alias, etc) but not overwrite the original data. This is challenging when coordinates are different since a facility cannot exist in two different locations.

### Describe the solution you'd like

Not sure yet. Need to talk to design about how to display ambiguous locations.

### Additional Context

Optional. Add any other context, screenshots, gifs, etc about the feature request here.

**Comment by jwalgran** [comment]
Concept:

- Collect an alias via an admin form
- Show the points from matches as well as aliases in the details sidebar
  - Distance from current canonical point
  - "popup" or other visualization of the point on a map
- Moderation tool to promote an alias point (match promotion already handles the point in that case)

**Comment by katieashaw** [comment]
Updating to note that the Dutch Covenant (AGT) has now also requested this enhancement.

**Comment by jwalgran** [comment]
Implemented in #814
