### ISSUE TITLE
Replace Google Map component with React-Leaflet using Google basemap

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#706]
## Overview

Replace Google Map component with React-Leaflet using Google basemap.

This is prep work for displaying more facilities on the map, but it will also make it easier to undertake future map-related changes like polygonal search.

### Describe the solution you'd like

Replace Google Map component with React-Leaflet using Google basemap.

Ensure that the new map component has feature parity with the existing Google Map component.

Ensure that the new component requests its tiles from the correct URL, based on the user's country.

### Additional context

As much as is possible, I think we should stick with using React-Leaflet idioms for handling map interactions rather than going through refs & using imperative code. The current Google Map component uses a lot of imperative code and it's therefore comparatively difficult to reason about.

**Comment by kellyi** [comment]
We also need to ensure that the basemap request routes correctly by country so that the map will continue to work in China.

**Comment by kellyi** [comment]
Looks like this library does what we need as far as setting the region conditionally:

https://www.npmjs.com/package/react-leaflet-google-layer

**Comment by jwalgran** [comment]
👍 	

On the surface it looks like a well managed solo project that is a simple mash up of Carrooi/Js-GoogleMapsLoader and IvanSanchez/Leaflet.GridLayer.GoogleMutant

The GoogleMutant docs say that it needs a promise polyfill for IE 11. Presumably we already have this in our pipline since we are making use of promises already.

**Comment by kellyi** [comment]
For my reference here is what the existing multiple-facilities-at-point popup looks like:

<img width="604" alt="Screen Shot 2019-07-29 at 4 33 21 PM" src="https://user-images.githubusercontent.com/4165523/62080440-a6e06e80-b21e-11e9-982d-3a042146a2ba.png">
