### ISSUE TITLE
Information on the "processing" page of the app talks about "accept" or "reject" matches. Options are "confirm" or "reject".

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#712]
## Overview

On the "Processing" page, which explains how the OAR matching algorithm works, the explanation includes this sentence: 

_If one or more potential matches to an existing facility are found, but the application is not confident enough to make the match automatically, the contributor will be asked to “Accept” or “Reject” the match using buttons within the application._

### Expected Behavior

The options are "Confirm" or "Reject". 

### Actual Behavior

The sentence reads _If one or more potential matches to an existing facility are found, but the application is not confident enough to make the match automatically, the contributor will be asked to “Accept” or “Reject” the match using buttons within the application._

### Steps to Reproduce

Visit: https://openapparel.org/about/processing

**Comment by jwalgran** [comment]
Try to combine this small text correction with another issue.
