### ISSUE TITLE
Users can now upload to the OAR using either CSV or Excel files, but there is only a CSV contributor template

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#714]
**NOTE:** See the desired changes in the [comment](https://github.com/open-apparel-registry/open-apparel-registry/issues/714#issuecomment-547069939) below

## Overview

Users are now able to upload to the OAR using either a CSV file or an Excel file, but there is currently only a Contributor template in CSV format. Some users are encountering issues when converting this to CSV, which is causing upload errors. 

### Expected Behavior

There should be contributor templates in both CSV and Excel formats. 

### Actual Behavior

There is only a Contributor template in CSV format. 

### Steps to Reproduce

Visit the "Contribute" page and download the Contributor template.

**Comment by katieashaw** [comment]
We've had a couple of users get confused and try to upload using a CSV, when Excel would be their preference. Could we boost this up the list to incorporate into another deployment, to avoid more users getting confused please?

**Comment by jwalgran** [comment]
I have moved this into our priority backlog. It is a relatively small issue that we should be able to resolve quickly once we get past our MSI integration work.

**Comment by jwalgran** [comment]
## Requested Changes
- Unzip and add this XLSX template file based to `src/app/public` [OAR_Contributor_Template.xlsx.zip](https://github.com/open-apparel-registry/open-apparel-registry/files/3779986/OAR_Contributor_Template.xlsx.zip)
- Add an additional button to the contribute page that downloads this file from `/OAR_Contributor_Template.xlsx`
