### ISSUE TITLE
Facility vector tile layer infrastructure

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#722]
## Overview

Set up an API endpoint for returning unfiltered, unaggregated facility vector tiles and a feature flagged map component to display them.

### Describe the solution you'd like

- Add [Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid)  / [react-leaflet-vectorgrid](https://github.com/mhasbie/react-leaflet-vectorgrid) as dependencies.
- Create a React map component that is swapped in when a Waffle switch is enabled
  - Create a data migration that adds a `vector_tile_map` [django-waffle switch](https://waffle.readthedocs.io/en/stable/types/switch.html)
  - Create a React map component that just shows the Google basemap. 
  - Conditionally load the component when the Waffle switch is on.
- Create a `/tile/{layer}/{z}/{x}/{y}/` endpoint
  - Return 400 if `layer` is something other than `facilities`. 
  - Convert z/x/y to a bounding box
  - Build a Facility values queryset that uses the bounding box as a filter and selects just the ID column.
  - Get the `query` from the queryset, wrap it with [ST_AsMVT](https://postgis.net/docs/manual-dev/ST_AsMVT.html) and [run the query via a cursor](https://docs.djangoproject.com/en/2.2/topics/db/sql/#executing-custom-sql-directly)
  - Return the result with a content-type of `application/vnd.mapbox-vector-tile`
- Add a VectorGrid layer to the feature flagged map component and load the facility vector tile layer.

### Additional Context

The goal is to get the simplest possible, end-to-end vector tile implementation in place. We will create additional issues to implement filtering and zoom-level-based aggregation.

**Comment by kellyi** [comment]
We should consider using https://www.npmjs.com/package/react-leaflet-vectorgrid for the vector grid. If for some reason we don't want to use that library, we should try to subclass React-Leaflet's `TileLayer` for use with the vector grid.

**Comment by jwalgran** [comment]
I added a reference to react-leaflet-vectorgrid to the issue description.

**Comment by kellyi** [comment]
Cool. It also occurred to me that we may also want to wrap whatever new React component is made for the vector tile layer in a thing that has access to the Redux store -- so that it can directly access the store to see what query params have been applied & just use those in its tile requests urls.

**Comment by kellyi** [comment]
#730 has an implementation of the React stuff, along with a feature flag set up for `vector_tile`

I scheduled some time to pair tomorrow on the API endpoint.

**Comment by kellyi** [comment]
We should consider adding https://github.com/mapbox/mercantile to handle transforming the x/y/z values into a bbox.

**Comment by kellyi** [comment]
I pushed a commit to #730 which adds mercantile along with a basic `/tile` endpoint to the API.

This blog post has an example of using `mercantile.bounds` with `ST_AsMVT` that might be helpful:

https://www.zimmi.cz/posts/2017/serving-mapbox-vector-tiles-with-postgis-nginx-and-python-backend/
