### ISSUE TITLE
Restrict permissions on `/tile` endpoint

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#735]
## Overview

https://github.com/open-apparel-registry/open-apparel-registry/pull/730 adds a `/tile` endpoint that currently has `AllowAny` permissions. However, we want to restrict things such that only the OAR's React client can make requests to this endpoint.

### Describe the solution you'd like

https://github.com/open-apparel-registry/open-apparel-registry/pull/730 adds a `/tile` endpoint that currently has `AllowAny` permissions. However, we want to restrict things such that only the OAR's React client can make requests to this endpoint.

Outcome of this should be that:

- the React client can consume the endpoint successfully
- ~no other client can successfully use it~ it's difficult for other clients to use it; they cannot just drop the URL in as the map endpoint and have it work
- there is an automated test that demonstrates this working

**Comment by jwalgran** [comment]
We should be able to reuse the "client key" and request header validation we implemented to protect unauthenticated requests to to the rest of the API

https://github.com/open-apparel-registry/open-apparel-registry/blob/3e4a64ba1cfba3400e050b7d2248afe7d011f90f/src/django/api/permissions.py#L27-L49

We may just need to factor out the "web client" bits into a new `BasePermission` subclass and then decorate our tile view with it.

**Comment by rajadain** [comment]
Unfortunately, it seems non-trivial to configure `VectorGrid` to specify header values in its requests, which only supports adding query parameters by default: http://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html. Should we invest the time to make this possible, or would it be enough to only have a Referer check for now?

**Comment by kellyi** [comment]
@jwalgran should confirm but I think referrer check might be enough.

It appears that the protobuf class of the VectorGrid library -- http://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html#vectorgrid-protobuf -- also does afford passing along a `token` or `key` property with the tile requests but it also seems like these values can be seen just as easily as the tile URL when using the developer tools, so spending time adding it there wouldn't really do anything except make it possible to switch out the key on a redeploy. That may be enough but I dunno. Additionally, putting the key in the URL like that would affect the tile caching.
