### ISSUE TITLE
Allow superusers to add alternate location and promote it to replace the facility location

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#738]
NOTE: I recommend a pairing session to start this off that covers the implementation of the models and the API design.

## Overview

Build a data model, superadmin UI, and public UI for submitting, displaying, and promoting updated locations.  

### Is your feature request related to a problem? Please describe.

Facilities can have non-specific addresses that the Google geocoder cannot plot correctly. Contributors have submitted corrected lat/lng coordinates to our moderation team. 

### Describe the solution you'd like

- Add a `FacilityLocation` model to store alternate coordinates
  - facility_id - non_null foreign key to Facility
  - location - non-null point geometry
  - notes - null text 
  - admin_id - non-null user id of the admin adding the record
  - contributor_id - nullable contributor who submitted the correction
  - created_at
  - updated_at
- Add admin-only view function
  - Add view for POSTing alternate locations to create a new `FacilityLocation model instance and promote the new location to the `Facility` object.
    - Set a text summary of the action in the `changeReason` field on the `Facility` before saving with the updated location (several other moderation dashboard pages do this).
- Add a superadmin dashboard page
  - That accepts new locations
    - Loads a facility by OAR ID and shows the existing detail we already do this for other superadmin dashboard pages)
    - Accepts lat/lng coordinate values and previews them on a side-by-side static map (similar to the existing facility merge UI.
    - Submit button calls the new API to save the location. 
    - On a successful post, reload the facility details
  - And allows `FacilityLocation` rows to be promoted
    - Show a button next to each alternate location that comes from a `FacilityLocation` row.
    - On click show a confirmation dialog similar to the ones already shown on dashboard pages summarizing the action.
    - On confirmation, post to the promote endpoint then refresh the summary.
~- Update facility details endpoint to list alternate locations (coordinates that do not match the top-level facility coordinates).~ 
 ~- Similar to how we already show alternate names and addresses~
 ~- Show both alternate coordinates from other geocoded list items and results from the `FacilityLocation` table~

This last item will be extracted to a separate feature after discussing it with Katie.

### Additional Context

An example of showing multiple locations on the facility detail page.
<img width="372" alt="Screen Shot 2019-09-09 at 9 59 05 AM" src="https://user-images.githubusercontent.com/17363/64550854-a12f7b80-d2e8-11e9-9bd9-9f54fa92b6c1.png">

**Comment by kellyi** [comment]
To simplify things: I think this feature should *not* include the ability to select a point by clicking on a map. Instead, the user should have to input lat lng coordinates in input fields and then these coordinates can be rendered by in a new panel or dialog by the existing static map image component.

**Comment by dboyer** [comment]
Consider how this might interact with #794 where contributors would like to update facility address data on their own lists.
