### ISSUE TITLE
The zoom on the OAR map is behaving in an inconsistent manner

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#757]
## Overview

The zoom on the OAR map is behaving in an inconsistent manner, in that sometimes it zooms right into the detail of a facility profile a user is viewing, and other times it does not. 

### Expected Behavior

The map zoom should be more consistent and always zoom into the detailed view of an OAR facility a user is looking at. 

### Actual Behavior

Sometimes the map zooms right into the detail of a facility, other times it does not. 

### Steps to Reproduce

* Search multiple different facilities in the tool and note the inconsistencies in the way the zoom is performing. 

### Demo

Zoom working:

![Screenshot 2019-09-02 at 17 00 48](https://user-images.githubusercontent.com/46344729/64125862-7783cb00-cda3-11e9-8dbf-6b4521ef6e86.png)

Zoom not performing as it should:

![Screenshot 2019-09-02 at 17 00 43](https://user-images.githubusercontent.com/46344729/64125871-7fdc0600-cda3-11e9-9481-69a73026702c.png)

Zoom not performing as it should:

![Map not zooming bug](https://user-images.githubusercontent.com/46344729/64125885-8bc7c800-cda3-11e9-84c2-711de76fc7fc.png)

### Additional context

The first two screenshots are taken today, subsequent to changes being rolled out in version 2.10.0 of the OAR, whilst the third screenshot was taken from version 2.9.0 of the app.

**Comment by katieashaw** [comment]
Zoom not performing as it should again: 

![Screenshot 2019-09-02 at 17 00 48](https://user-images.githubusercontent.com/46344729/64126249-fcbbaf80-cda4-11e9-9e74-e2607fd59d0b.png)

**Comment by katieashaw** [comment]
Zoom performing as it should be:

![Screenshot 2019-09-02 at 17 14 24](https://user-images.githubusercontent.com/46344729/64126290-2543a980-cda5-11e9-98f2-41ebc6a53da5.png)

**Comment by katieashaw** [comment]
Zoom not behaving correctly x2:

![Screenshot 2019-09-03 at 11 17 14](https://user-images.githubusercontent.com/46344729/64165197-7b176080-ce3c-11e9-99dc-7f719c9a82bb.png)

![Screenshot 2019-09-03 at 11 17 19](https://user-images.githubusercontent.com/46344729/64165215-85d1f580-ce3c-11e9-9a40-b0d27d66f68f.png)

**Comment by kellyi** [comment]
I think the desired behavior here is:

- if I visit the OAR with a URL containing the OAR ID for a facility details page, zoom to that facility
- if I click on a list item for a facility in the sidebar, zoom to that facility
- if I click on a marker representing a facility on the map, *do not* zoom to that facility

This behavior would replicate how Google Maps generally works.

I'm going to try to ensure this behavior in the new vector tile version of the map and then check into backporting it, since I don't think we'll make another release before the vector tile release.

**Comment by katieashaw** [comment]
Thanks @kellyi ! I agree with the first two bullets, but not necessarily the final one. If I click on a marker on the map, I would expect it to zoom to that facility - and I think our community would, as well. Happy to chat through, as I may be mis-understanding what you're getting at / the functionality on Google Maps.

**Comment by kellyi** [comment]
> If I click on a marker on the map, I would expect it to zoom to that facility - and I think our community would, as well.

Makes sense to me! I'll adjust things to work this way, which will essentially be:

- whenever the OAR ID changes in the URL, pan and zoom the map to the selected location

**Comment by jwalgran** [comment]
@katieashaw I would like to suggest fixing the zooming bug, but holding off on panning the map every time a marker is clicked for a few reasons.

  - If a person has zoomed the map to a specific are of interest every selection shifts the map away from their intentionally focused area.
  - On a relatively large desktop map, a lot of extra map movement can be disorienting.

This example of the behavior I am suggesting in Google maps. Very similar to our interface, results on the left, big map on the right.

![2019-09-10 08 07 42](https://user-images.githubusercontent.com/17363/64626382-9df8c600-d3a2-11e9-867e-e66cd24080a6.gif)

If person searching for facilities selects an item from the sidebar that is not currently visible on the map, we would continue zooming the map to that offscreen facility.

**Comment by katieashaw** [comment]
Got it! This makes total sense, thank you @jwalgran Happy to go ahead with your suggestion.
