### ISSUE TITLE
The OAR map is frequently returning an error message when scrolling through a set of results

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#758]
## Overview

When scrolling through a set of results on the left hand side of the site, the map is frequently returning an error message. 

### Expected Behavior

The map should remain steady / constant whilst scrolling through a list of search results.

### Actual Behavior

The map produces an error message - see screenshots. 

### Steps to Reproduce

* Run a search on the OAR
* Scroll through results

### Demo

![Screenshot 2019-09-02 at 12 59 37](https://user-images.githubusercontent.com/46344729/64128634-62ad3480-cdaf-11e9-8e50-1ac965dc7e43.png)

![Screenshot 2019-09-02 at 17 35 07](https://user-images.githubusercontent.com/46344729/64128643-693bac00-cdaf-11e9-93a0-9b1e41283f25.png)

![Screenshot 2019-09-02 at 17 40 19](https://user-images.githubusercontent.com/46344729/64128649-6fca2380-cdaf-11e9-8c70-8278c70168b7.png)

### Additional context

This appears to be a new bug since the deployment of version 2.10.0 of the tool. It happened several times whilst I was doing a big piece of moderation work (around 4.5 hours or so of work).

**Comment by dboyer** [comment]
I also saw this issue on production when viewing the map in Firefox on a Macbook. I can't replicate a reliable set of steps that always causes it, however. It's some combination of scrolling, zooming, and clicking on assets.

**Comment by kellyi** [comment]
I believe this is related either to react-infinite-any-height or to the new Leaflet map implementation. I was able to trigger it with the new vector tiles map on staging, too.

**Comment by jwalgran** [comment]
Sidebar appears to continue working after the error. If we can find a solution quickly, catching and logging a warning to Rollbar may be a way to fix production.

**Comment by kellyi** [comment]
Hypothesis: the MapAndSidebar component encompasses both the map and the infinite scroll component, and I believe has an ErrorBoundary above it. If the infinite scroll throws a non-fatal error, it could be that the ErrorBoundary is catching the infinite scroll error and setting the fallback for broken map states.

**Comment by kellyi** [comment]
I was able to re-create this using the vector tile feature infinite scroll on staging. The specific error is:

https://reactjs.org/docs/error-decoder.html/?invariant=185

**Comment by kellyi** [comment]
I used the React devtools to find the common parent ErrorBoundary where the `hasError` prop is toggleable. When I toggle `hasError` to be false, the map still appears to work as it should.
