### ISSUE TITLE
Incorporate search parameters into cache key

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#762]
# Draft

This is a draft issue, and it will need to clarify specs and formalize what
counts as "done" before work begins on it.

Check with the issue's creator before starting work on this issue.

## Overview

Include a new segment in the cache key that encodes the filter query string parameters.

### Is your feature request related to a problem? Please describe.

We want to cache tiles produced from searches, because they can be more expensive to build than unfiltered tiles.

### Describe the solution you'd like

- Sort query string filter arguments by key
- Sort any array values
- Stringify the normalized object, compute the SHA1 hash, and take the first 7 characters
- Include the short hash as another hypen-separated segment in the cache key.

**Comment by kellyi** [comment]
I checked and the way the querystring builds in the client already guarantees the order the distinct parameters are listed, but it does not yet sort within a param. e.g. `q=hello` will always appear before `countries=AF` but `countries=AF` will not always appear before `countries=CN`
