### ISSUE TITLE
Add a facility history endpoint

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#766]
## Overview

Add a feature-flagged API endpoint that returns a reverse, chronological list of changes to a facility over time.

### Describe the solution you'd like

- Add a `facility-history` waffle switch
- Add an `/api/facilities/:id/history/` endpoint
  - Return 404 if the `facility-history` switch is disabled.
  - Return an array of objects, one for each change to a facility
```
[
  {
    "updated_at": "2019-09-12T02:43:19Z",
    "action": "DELETE",
  },
  {
    "updated_at": "2019-09-05T13:15:30Z",
    "action": "UPDATE",
    "changes": {
      "location": {
        "old": { "type": "Point", "coordinates": [125.6, 10.1] },
        "new": { "type": "Point", "coordinates": [125.62, 10.14] },
      }
    }
  },
  {
    "updated_at": "2019-09-02T21:04:30Z",
    "action": "MERGE",
    "detail": "Merged with US2019123AG4RD",
  }
]
```
  - Use the `HistoricalFacility`, `HistoricalFacilityMatch` tables as needed to create the history content. 
  - Include split and merge as distinct action types.
  - Support getting history for deleted facilities.

**Comment by kellyi** [comment]
The historical tables are available via `Facility.history.whatever` and `Facility.match.whatever`. Finding a deleted facility's records works like:

```
Facility.history.filter(id=oar_id)
```

**Comment by kellyi** [comment]
@jwalgran I mentioned this in Slack but it appears that the `split` action doesn't create a new history entry for the facility which has had the match split from it. It will create a single historical facility record for the match which has been split into its own facility, but the data there is just an entry for creating the object.

We do make several updates to the facility when the `promote` endpoint gets used, so I've included that one. Should I try to assemble something for `split`s?

**Comment by kellyi** [comment]
For split we'll have to do something like:

- select all the facility list items whose processing results include a `SPLIT_FACILITY` action in their processing results and whose `previous_facility_oar_id` record matches the relevant facility id
- add that to the rest of the history list then sort (or interleave it at the appropriate temporal place)
