### ISSUE TITLE
Open pop-ups on map don't clear with a new search

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#796]
## Overview

A pop-up displayed on the map from a previous search does not clear when a new search is run and there is no way to get rid of the box. 

### Expected Behavior

The pop-up box should either disappear when a new search is run or the X to close the box should always be visible and operational.

### Actual Behavior

The pop-up remains when a new search is run and it is impossible to pan up on the map to close the box. 

### Steps to Reproduce

Tested in Firefox on a Mac but reproduced in other browsers.

1. Search Saitex in the facility name field and view results on the map
2. Click the bubble with a 7 in it
3. Map will zoom in
4. Click the bubble with a 6 in it to get a pop-up
5. Click Reset in the search filters
6. Map resets but popup remains
7. Search toy in the facility name field and select AGT from the contributor list
8. Map loads search results but pop-up remains
9. Attempting to pan up the map to use the X to close the search box just causes the map to bounce back to a view where the top of the box is not visible

### Demo

![Screen Shot 2019-09-10 at 10 00 58 AM](https://user-images.githubusercontent.com/516764/64620470-ea97cd80-d3b1-11e9-8da7-9a231fc027b9.png)

### Additional context

Optional. Add any other context about the problem here.

**Comment by katieashaw** [comment]
I experienced this issue in Chrome on my Mac, FYI.
