### ISSUE TITLE
Grid rendering issue at low zoom levels

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#801]
## Overview

Slivers of markers appear in adjacent tiles

### Expected Behavior

Tiles should not have edge artifacts

### Actual Behavior

Slivers of markers appear in adjacent tiles

### Steps to Reproduce

* Load the map and zoom in once to zoom level 3

### Demo

<img width="483" alt="Screen Shot 2019-09-10 at 12 19 08 PM" src="https://user-images.githubusercontent.com/17363/64644248-12456080-d3c7-11e9-843d-be2d7f722573.png">

### Additional information

- Experiment with using web mercator in ST_AsMVTGeom call
- Experiment with ST_AsMVTGeom buffer size (try reducing and expanding)

Time box this to no more than a day.

**Comment by rajadain** [comment]
After doing the following modifications to show the entire grid:

```diff
diff --git a/src/django/api/tiler.py b/src/django/api/tiler.py
index 0770aa2..3e75c95 100644
--- a/src/django/api/tiler.py
+++ b/src/django/api/tiler.py
@@ -47,16 +47,12 @@ def get_facility_grid_vector_tile(params, layer, z, x, y):
     join_query = (
         'SELECT '
         '  hex_grid.mvt_geom, '
-        '  count(location), '
+        '  500, '
         '  ST_XMin(ST_Envelope(hex_grid.geom)) as xmin, '
         '  ST_YMin(ST_Envelope(hex_grid.geom)) as ymin, '
         '  ST_XMax(ST_Envelope(hex_grid.geom)) as xmax, '
         '  ST_YMax(ST_Envelope(hex_grid.geom)) as ymax '
-        'FROM hex_grid '
-        'JOIN api_facility ON ST_Contains(hex_grid.geom, location) '
-        ' {where_clause} '
-        'GROUP BY hex_grid.mvt_geom, '
-        '  xmin, ymin, xmax, ymax')
+        'FROM hex_grid ')
     join_query = join_query.format(where_clause=where_clause)
 
     st_asmvt_query = \
```

We can see the grid isn't spaced evenly:

![image](https://user-images.githubusercontent.com/1430060/65625552-01d1e000-df9a-11e9-951e-d2d4759fab9a.png)

This is similar to the artifacts we saw in with the box version.
