### ISSUE TITLE
Colour change when a facility is selected is too subtle 

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#806]
## Overview

Feedback from users at the recent N3XTCODER hackathon is that the colour change on the marker when a facility is selected is too subtle. The majority of people in the room didn't notice the switch.

### Expected Behavior

The colour change should be more significant, to ensure that users notice the change. 

### Actual Behavior

The colour change is subtle, so many people don't notice that there has been a change. 

### Steps to Reproduce

* Run a search in the tool
* Select one facility by clicking on its marker on the map
* Note only subtle change of colour

### Demo

![Screenshot 2019-09-11 at 17 38 01](https://user-images.githubusercontent.com/46344729/64716791-f28f6480-d4ba-11e9-9e17-b4e892af6ba6.png)

### Additional context

This feedback came from the team who worked on the OAR challenge at the N3XTCODER hackathon.

**Comment by katieashaw** [comment]
This feedback was shared again by a brand in response to the embedded map wire frames

@lederer @dboyer

**Comment by lederer** [comment]
One approach that might solve this in a way that also scales to themed embeds would be to use a gray as the default marker color and then use OAR blue (or the theme color for themed embeds) for the selected marker. 

The main downside is that gray isn't a particularly inviting marker color. But it ought to be fine. And any other solution would likely require us to prompt for two colors in the embed config screen – a default color and a highlight color – which will create friction for that workflow.

**Comment by jwalgran** [comment]
@lederer 2 questions:

- Do you have a suggestion for grey shade
- The current markers in the app are png files. (https://github.com/open-apparel-registry/open-apparel-registry/blob/develop/src/app/public/images/marker.png) Are there original vector source files in a design repo/folder? Can we get an SVG version?

**Comment by lederer** [comment]
Let's try `#838BA5` for the gray. It has a very slight tint of OAR blue in it, for good measure.

No source files, but pasting an SVG version below that ought to work.

Holler if any additional tweaks are needed.

```svg
<svg height="506" viewBox="0 0 384 506" width="384" xmlns="http://www.w3.org/2000/svg"><path d="m0 192c0-106.039 85.961-192 192-192s192 85.961 192 192c0 70.692667-64 175.359373-192 314.00012-128-138.640747-192-243.307453-192-314.00012zm192 80c44.183 0 80-35.817 80-80s-35.817-80-80-80-80 35.817-80 80 35.817 80 80 80z"/></svg>
```
