### ISSUE TITLE
Searching picks wrong circle on map

### ISSUE THREAD

**Issue by rajadain** [open-apparel-registry/open-apparel-registry#821]
## Overview

In some cases, when searching for a facility at a lower zoom level, the map picks the wrong circle to show, _even when there is a better alternative_. For example, in the following case, searching for "Pratibha" should show the circle pointed to by the green arrow. Instead it shows the circle pointed to by the red arrow:

![image](https://user-images.githubusercontent.com/1430060/65260254-131b7800-dad4-11e9-8d3f-5297c75bb683.png)

### Expected Behavior

The map picks the right circle to show after searching.

### Actual Behavior

It picks a nearby, but not the correct circle.

### Steps to Reproduce

* Open the app, and search for Pratibha
* See the circle picked is not the closest to the actual facility

### Demo

By clicking:

![2019-09-19 11 56 09](https://user-images.githubusercontent.com/1430060/65260656-b53b6000-dad4-11e9-8e48-a84ff050524b.gif)

By searching:

![2019-09-19 11 57 06](https://user-images.githubusercontent.com/1430060/65260670-ba001400-dad4-11e9-8df6-087a81a26ed1.gif)

### Additional context

Technically, one _can_ find the facility even with the "wrong" circle. However, the "right" circle is much closer to the facility, and should be the one that is shown. It is possible we are picking the first match to show, rather than the closest one.

**Comment by jwalgran** [comment]
This was resolved by switching the tiler to use web mercator coordinates.
