### ISSUE TITLE
App crashes when logging in after zooming in

### ISSUE THREAD

**Issue by rajadain** [open-apparel-registry/open-apparel-registry#822]
## Overview

If the vector tile layer is turned on, and you zoom in all the way and pick a facility, then click "Log In" in the top right, the app crashes.

Unhandled Rejection (TypeError): layer is undefined
https://github.com/open-apparel-registry/open-apparel-registry/blob/8b262ae7619b40045c1e720d23d8e93aa52f3941/src/app/src/components/VectorTileFacilityGridLayer.jsx#L97

### Expected Behavior

The app does not crash, and allows logging in.

### Actual Behavior

The app crashes.

### Steps to Reproduce

* Have the vector tile layer turned on
* Zoom all the way in to the facility level and select one
* Click "Log In" in the top right
* Wait a few seconds
* See the app crash

### Demo

![image](https://user-images.githubusercontent.com/1430060/65261402-321b0980-dad6-11e9-83bd-bca0fa0e3c66.png)

![2019-09-19 12 09 00](https://user-images.githubusercontent.com/1430060/65261647-b9687d00-dad6-11e9-9da6-32a777b20cc7.gif)

**Comment by kellyi** [comment]
This should be pretty straightforward to fix and we'll need to do that before releasing vector tiles to production.
