### ISSUE TITLE
Temporary pop-up on map site about community survey

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#855]
## Overview

We plan to send out a community survey to users in the next week or so, to gather feedback 6 months on from launch. Could we add a temporary pop-up to the site as part of the next update (whenever that is) directing people to the survey please. 

### Is your feature request related to a problem? Please describe.

We'd like to drive responses to the user survey by directing users to it from the map. 

### Describe the solution you'd like

Could we have a temporary pop-up on the map site directing users to the community survey. We will provide text and a link to the survey, once it's ready and add to this issue. 

- Add a component based on [the GDPR notification component](https://github.com/open-apparel-registry/open-apparel-registry/blob/fdb5f062e55fe4b44fbaf0f0614d02a36e7af6f6/src/app/src/components/GDPRNotification.jsx)
  - Show the [text](https://github.com/open-apparel-registry/open-apparel-registry/issues/855#issuecomment-541139410) provided by @katieashaw and a "Close" button.
- Similar to the GDPR notification, use local storage to remember that the close button was clicked and stop showing the notice.
- Add a date check. After November 10 2019, do not show the popup.

### Additional Context

We'll be promoting the survey via newsletters, social etc as well, but a pop-up on the site should be a good way to increase the number of responses.

**Comment by katieashaw** [comment]
Text for pop-up:

<header> Help us help you
<body copy> We prioritize developments & new features on the OAR based on user feedback. Got something you'd like to see on the tool? Share your feedback through our survey: http://bit.ly/OARSurvey

The long version of the URL is: https://openapparelregistry.typeform.com/to/OVtfvL

**Comment by jwalgran** [comment]
@katieashaw is there a date after which we can stop showing the popup?

**Comment by katieashaw** [comment]
@jwalgran Yes! Good point. From 10th November onwards it can come down.
