### ISSUE TITLE
OAR does not currently recognise "People's Republic of China" as a country

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#868]
## Overview

The OAR does not currently recognise "People's Republic of China" as a country and returns “Status – Error_Parsing”; “Could not find a country code for “People’s Republic of China” message. 

### Expected Behavior

The tool needs to recognise this way of referring to China in user uploads. 

### Actual Behavior

The OAR will not process lists with "People's Republic of China" listed as the country. 

### Steps to Reproduce

* Prepare a list of facilities which have "People's Republic of China" in the country column
* Upload to Staging

N.B. Katie tested this process in Staging today. 

### Demo

![Screenshot 2019-10-11 at 18 14 15](https://user-images.githubusercontent.com/46344729/66670988-f990ca80-ec52-11e9-9a4d-ffacb62a0846.png)

### Additional context

This issue was flagged by a user who had tried to upload a file using this country name.

**Comment by jwalgran** [comment]
We should be able to resolve this by adding "People’s Republic of China" as an additional name in `countries.json`.

https://github.com/open-apparel-registry/open-apparel-registry/blob/4a0f691a48e9121643780ca0bad428f900a878e2/src/app/src/data/countries.json#L182-L185
