### ISSUE TITLE
Create Swagger docs for API

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#88]
## Overview

Currently the API has some documentation here https://info.openapparel.org/apiinstructions

We should add Swagger docs for the DRF version.

### Describe the solution you'd like

Swagger docs for the DRF API.

**Comment by dboyer** [comment]
A note that the original api instructions page has been removed, pending relaunch of the site.

**Comment by jwalgran** [comment]
[Django REST Swagger](https://marcgibbons.com/django-rest-swagger/) is a popular option that is mentioned in the list of options on the DRF site, supports Token authentication, and should allow us to quickly bootstrap some interactive API documentation.
