### ISSUE TITLE
New contributor has added 1 facility. The total facility count has gone up by 3. 

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#92]
## Overview

A new contributor, Andrew Rogers, joined the site on 8th Jan. He uploaded one facility to the site. However, the total facility number on the site has increased by 3 from 69,374 to 69,377 from w/e 6th Jan to w/e 13th Jan. See "Weekly facility numbers" tab for tracking here: ****

As far as we can see (and our access is limited) no other contributors have uploaded facilities during this time, which suggests that the the addition of this one facility has created three entries. 

### Expected Behavior

The total number of facilities on the site should only have increased by one.

### Actual Behavior

It appears that the addition of one facility has created three new facilities on the site. 

### Steps to Reproduce

- Filter site by Contributor -> Andrew Rogers
- 1 facility is returned
- Note that total number of facilities on the site is 69,377
- Using the site on Chrome on a 2017 MacBook Air

### Additional context

We are aware of this issue on the site already, but thought this new occurrence might be a helpful one to dig into!

**Comment by kellyi** [comment]
I'm closing out some old issues which have either been addressed or have been superseded. I believe we generally fixed this bug while rewriting the API.

I'm going to close this issue, but if we observe the bug again we can re-open it.
