### ISSUE TITLE
Search for contributor overlap ("AND" search of multiple contributors)

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#921]
## Overview

Allow searching facilities by multiple contributors using "AND" instead of "OR."

### Is your feature request related to a problem? Please describe.

Finding the "overlap" between the facility lists from two or more contributors is a useful feature that has been requested by contributors. Combining searches with "AND" was also the default for the v1 application.

### Describe the solution you'd like

- When more than one contributor is selected, display a checkbox to enable searching for "shared facilities."
- Include the state of this checkbox in the search URL and restore it when loading a bookmarked search
- Add a `combine-contributors` parameter to the API. When set to "AND" (case insensitive) change the contributor filter to use "and" instead of "or."

### Additional Context

Winning hackathon project that implemented this idea using a static data set.

https://github.com/flache/hyper-oar/
http://hyper-oar.s3-website.eu-central-1.amazonaws.com/

**Comment by jwalgran** [comment]
Scheduled a discussion with @designmatty to talk about the design.

**Comment by designmatty** [comment]
Continuing the conversation from our call, I think the following UI should support this request without requiring drastic changes:

**Comment by designmatty** [comment]
@jwalgran let me know if I missed anything.

**Comment by jwalgran** [comment]
Thanks. This is great. We talked about including an information popup to include some inline documentation explaining in more detail what "shared facilities" means. How would you suggest implementing that help popup?

**Comment by designmatty** [comment]
Oh good catch. I updated my previous comment and screenshot. There is now an "info" icon. On hover of the icon utilize the tooltip component, which I linked to in the above comment.

**Comment by jwalgran** [comment]
@katieashaw and/or @nataliegrillon 

Matt and I discussed the overlapping contributor feature and came up with this design that includes a "i" help icon which gives us a place to show some popover text explaining what the checkbox does. 

![69988990-b3e4d580-1510-11ea-82bd-127a503b3133](https://user-images.githubusercontent.com/17363/70481054-9f6b8480-1a9e-11ea-858a-f7ad36e9f3a0.png)

Could you please post the short bit of help text you would like us to show?

**Comment by katieashaw** [comment]
Oh, this is great - so simple, I love it!

Won't take long to write this. When do you need the text by @jwalgran ?

**Comment by jwalgran** [comment]
Thanks. Missing texts is not blocking any development tasks, so there is no real rush. Would it work with your schedule to have it done by the end of the UK day on Wednesday?

**Comment by katieashaw** [comment]
Certainly would!

**Comment by nataliegrillon** [comment]
Awesome! So exciting!

Best,

Natalie
----
Natalie Grillon
Project Director, Open Apparel Registry
natalie@openapparel.org // + 1 413 884 3355
Search the map here <https://openapparel.org/>
Watch a 90 second explainer about the Open Apparel Registry here
<https://youtu.be/hrqQc3CVdHQ>
Learn more about the tool here <https://info.openapparel.org/>
twitter <https://twitter.com/openapparelreg> / Instagram
<https://www.instagram.com/openapparelregistry/> / LinkedIn
<http://linkedin.com/company/open-apparel-registry>

**Comment by katieashaw** [comment]
Text is ready for you here @jwalgran 

https://docs.google.com/document/d/12Y8JmIOpGP6d56CF2nxjvfWg2lehFpBm-wDltnedrKU/edit?usp=sharing
