### ISSUE TITLE
Display number of users per Contributor type in the Contributor dropdown menu

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#930]
## Overview

A user has contacted me to express interest in being able to see the number of Contributors to the OAR by Contributor type, e.g. 31 Brands / Retailers, 28 Civil Society Organisations etc. Could we explore making this information visible through the front end of the OAR? 

### Is your feature request related to a problem? Please describe.

These figures are currently only available to the OAR team through our monthly reports. Users would have to reach out to the OAR team to request this information 

### Describe the solution you'd like

Would it work to display the figure in brackets by each Contributor type in the Contributor dropdown menu and have this information update automatically when new Contributors upload to the tool?

**Comment by dboyer** [comment]
@katieashaw Do you know anything more about the potential use case? Is a number sufficient or would they also want a list of the names of each brand, CSO, etc?

**Comment by katieashaw** [comment]
I think at a minimum, displaying the numbers would be helpful for many users. Being able to navigate to then see the list of each brand, CSO etc is a nice to have, so would depend on how tricky that would be to build.

cc @nataliegrillon for info

**Comment by katieashaw** [comment]
I'm doing a detailed review of feedback from our user survey and noting here that an additional user has requested this feature, also requesting the figures on a per-country basis. (The user also requests it at a regional level, which will be covered by polygonal search.)
