### ISSUE TITLE
Namespace DRF API routes under /api/<route>

### ISSUE THREAD

**Issue by kellyi** [open-apparel-registry/open-apparel-registry#94]
## Overview

To distinguish between React-Router routes & DRF routes, we should namespace the DRF routes beneath `/api/`

### Describe the solution you'd like

Namespace DRF routes in `/api/`

**Comment by jwalgran** [comment]
I started doing this in https://github.com/open-apparel-registry/open-apparel-registry/pull/86
It is trivial to mount a view multiple times, so we can keep the old routes in place during our backend transition.

**Comment by jwalgran** [comment]
This was implemented in #86
