### ISSUE TITLE
Disable access to the currently deployed application by redirecting openapparel.org to info.openapparel.org

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#95]
**NOTE:** This is labeled `question` because we are waiting for confirmation that this is an acceptable approach.

## Overview

Set up a temporary redirect from openapparel.org to info.openapparel.org. 

### Is your feature request related to a problem? Please describe.

The application currently hosted at openapparel.org contains outdated information and the stakeholders do not trust the existing application will correctly update the data. They would like the existing application to be inaccessible.

### Describe the solution you'd like

  * Deploy a web server to **temporarily** redirect all requests to info.openapparel.org. 
  * Update the DNS for openapparel.org to point to the new web server.

**Comment by hectcastro** [comment]
`www.` -> to `openapparel.org`

```
$ http --headers https://www.openapparel.org
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 0
Date: Fri, 18 Jan 2019 21:38:24 GMT
Location: https://openapparel.org/
Server: AmazonS3
Via: 1.1 25d430acaef0ba8e2a9fff8bf278cedb.cloudfront.net (CloudFront)
X-Amz-Cf-Id: kPB2M10b8x78L_a-soxCeZpILQytLyaj6ASX-NtVRZE7enYvQ7HEKQ==
X-Cache: Miss from cloudfront
```

`openapparel.org` -> `info.`

```
$ http --headers https://openapparel.org
HTTP/1.1 302 Moved Temporarily
Age: 4510
Connection: keep-alive
Content-Length: 0
Date: Fri, 18 Jan 2019 20:23:58 GMT
Location: https://info.openapparel.org/
Server: AmazonS3
Via: 1.1 7b4e9d5d88fa096864c64d469a1fc524.cloudfront.net (CloudFront)
X-Amz-Cf-Id: OhlrLiH_H5SYIWj-N8hKsjlhZDdlMhLgAqKZc049yqvbzUhRnxbO3A==
X-Cache: Hit from cloudfront
```

Also, the Squarespace site is still operational at https://info.openapparel.org.
