### ISSUE TITLE
Open to search tab on initial page load

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#977]
## Overview

When visiting the OAR map page, have the search tab visible instead of the facilities tab

### Is your feature request related to a problem? Please describe.

Currently, the page loads with the first tab (the facilities tab) visible and it is not immediately obvious what the user should do. Loading the search tab immediately showcases the search functionality.

### Describe the solution you'd like

The search tab should be visible when accessing the main openapparel.org page. Consult @designmatty in regards to whether the tabs should be reordered so Search is first or if just opening to the Search tab is sufficient.

### Additional Context

Currently, the number of total facilities/search results is at the bottom of the Search tab. Consult with @designmatty on where it could be placed higher up on the page so it is more visible.

**Comment by designmatty** [comment]
Please switch the order of the tabs, Search first, then Facilities

**Comment by TaiWilkin** [comment]
@designmatty Do you have thoughts on where we can place the number of total facilities/search results higher on the page so it is more visible?

**Comment by designmatty** [comment]
I think we could do one of the following:

**Option A**
![image](https://user-images.githubusercontent.com/1928955/76109541-a4ab7300-5faa-11ea-9214-a1842be99bc7.png)

**Option B**
![image](https://user-images.githubusercontent.com/1928955/76109826-4632c480-5fab-11ea-9b5d-f9fb6bc4a149.png)

@dboyer any preference?

**Comment by jwalgran** [comment]
We have discussed the possibility of removing that big blue bar, so I would vot for option A

![image](https://user-images.githubusercontent.com/1928955/76109541-a4ab7300-5faa-11ea-9214-a1842be99bc7.png)

**Comment by TaiWilkin** [comment]
@dboyer @jwalgran Currently, the facilities count shown on the search tab is the count of total facilities (NOT the count of search results), but the count on the facilities tab is the count of search results. Which number do we want to show in the tab bar? And do we want to remove the total count (on search tab) and/or the search results count (on facilities tab)?

**Comment by jwalgran** [comment]
I think we get a 2-for-1 here. It is important to engagement/marketing efforts that we prominantly show the total number of facilities when you arrive at https://openapparel.org/. I think we should connect the count in the tab bar to the current number of search results since that will also be the full count when arriving on the site with no filters. The separation between the full count and the filter count is a leftover from when we were capping search results at 500.
