### ISSUE TITLE
Enable users to filter down to individual list level

### ISSUE THREAD

**Issue by katieashaw** [open-apparel-registry/open-apparel-registry#983]
## Overview

Enable users to filter down to the individual list level on a Contributor page

### Is your feature request related to a problem? Please describe.

Whilst Contributors are already able to upload multiple lists to their OAR accounts, when searching the OAR users cannot filter down to the individual list level. 

### Describe the solution you'd like

- Add a `facility-lists` API that returns the active lists for one or more contributors
  - If multiple contributor IDs are passed, the response should contain all active lists from all specified contributors
  - Return the list name, and list ID for each list. Sort by list name.
- When one or more contributors are selected on the search page show a contributor list filter dropdown below it
  - Indent it to emphasize that it is related to the contributors list (and consider indenting the existing "Show only shared facilities" checkbox to match)
  - Populate it with the list API response
- Add a `lists` query string filter parameter that behaves like the `contributors` query string filter parameter.
- Add filtering by list ID(s) to `GET /api/facilities`
  -  Ensure that the option appears correctly in `/api/docs/#!/facilities/facilities_list`
- Add links to the lists shown on the contributor profile page that set the contributor and list query string arguments appropriately so that clicking the link runs the appropriate search. 

### Additional Context

Examples for use of this filtering would be the Accord on Fire and Building Safety in Bangladesh consolidating their two separate accounts into one, with users being able to filter to each separate upload; users being able to filter by the different lists for tiers of supply chains uploaded by brands; certification schemes having separate lists for different levels of certification, e.g. Gold, Silver, Bronze, which users can then filter by.

**Comment by katieashaw** [comment]
A question for @jwalgran on this: would it make any sense to incorporate this into the work on the map plug-in?

**Comment by jwalgran** [comment]
If we are talking about the "embedded map" feature, where contributors can add an OAR-created map of their facilities to their own website, then yes. We plan to allow country and contributor type filters to still work on the embedded map, and it would make sense to also include this new list filter.

**Comment by katieashaw** [comment]
Yes, that's what I meant - so that's great to hear, thank you!

**Comment by dboyer** [comment]
Related to #454

**Comment by katieashaw** [comment]
During the first week of February, we received two enquiries in quick succession relating to historical data in the OAR. Where organisations choose to have multiple active lists associated with their accounts, the ability to filter down to the individual list level would provide those users with the information they are looking for.

Also noting for @jwalgran and @dboyer the reference in our exchanges on this issue to integrating this work with the development of the embedded map plug-in, which is now in progress.

**Comment by jwalgran** [comment]
@TaiWilkin I updated "Describe the solution you'd like" to include the decisions made in our design meeting. Please review and let me know if there are any omissions or ambiguities that we should correct.

**Comment by TaiWilkin** [comment]
@jwalgran This accurately covers everything we discussed. I'm not seeing any ambiguities currently.
